/* Level 06 (Blarg Station (Nebula G34)) code following fastfunc; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L06_002172B0);
