/* Level 11 (Pokitaru) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

extern void func_0020D678(void *);
extern float func_001FA748(float, float);
extern float func_001F9D48(void *, void *);
extern int func_0020BFC8(int, int);
extern int func_L00_00203F20(int, int);
extern float D_0015EE6C MACRO_ADDR;
extern unsigned char D_0013D5CA[];
extern unsigned char D_0013D5EB[];
extern char D_0013E633[];

/* Per-frame update of a pickup moby: waits for the player to come near, then grants the item. */
void func_L11_002CC828(char *moby) {
    switch ((unsigned char)moby[0x20]) {
    case 0:
        if (gHaveHeliPack[4] != 0) {
            DeleteMoby(moby);
        } else {
            *(float *)(moby + 0x18) += 0.75f;
            *(unsigned short *)(moby + 0x34) |= 1;
            moby[0x20] = 1;
        }
        break;
    case 1:
        break;
    case 2:
        FastAddRots(*(float *)(moby + 0x48), D_0015EE6C * 4.7123890f);
        if (func_001F9D48(moby + 0x10, D_0013E633 + 0xE9D) < 2.0f) {
            gHaveHeliPack[4] = 1;
            gHavePersuader[0xB] = 1;
            memcard_Save(0, -1);
            Help_Request(0x2AF8, 0x3A);
            DeleteMoby(moby);
        }
        break;
    }
}
extern char *func_0020D348(int);
extern float func_001FA790(float, float);
extern float func_L00_0025CE58(float *p, float a, float *v, float b, float c, float d);
extern float D_0015EE70 MACRO_ADDR;

// Update for a moby that spawns a child copy once, then eases along a path and changes state.
void func_L11_002CC9D0(char *moby) {
    char *data = *(char **)(moby + 0x78);
    int state = (unsigned char)moby[0x20];
    switch (state) {
    case 0:
        moby[0x20] = 1;
        *(float *)(data + 4) = *(float *)(moby + 0x48);
        if ((*(unsigned short *)(moby + 0x34) & 0x8000) == 0) {
            char *c = func_0020D348(0x41);
            *(short *)(c + 0x32) = *(short *)(moby + 0x32);
            c[0x30] = moby[0x30];
            *(unsigned short *)(c + 0x34) = *(unsigned short *)(moby + 0x34) | 0x8000;
            qcopy(c + 0x10, moby + 0x10);
            qcopy(c + 0x40, moby + 0x40);
            *(char **)(data + 8) = c;
            *(float *)(*(char **)(c + 0x78) + 4) = *(float *)(moby + 0x48);
        }
        break;
    case 1:
        break;
    case 2: {
        float f;
        if ((*(unsigned short *)(moby + 0x34) & 0x8000) == 0)
            f = func_001FA748(*(float *)(data + 4), 0.20769417f);
        else
            f = func_001FA790(*(float *)(data + 4), 0.20769417f);
        if (func_L00_0025CE58((float *)(moby + 0x48), f, (float *)data, D_0015EE70 * 0.34906584f, D_0015EE70 * 0.34906584f, D_0015EE6C * 0.7853982f) == 0.0f)
            moby[0x20] = 3;
        break;
    }
    }
}
extern struct { unsigned char value; char pad[3]; } D_0013D4EA;

void func_L11_002CCB50(char *moby) {
    char *state = *(char **)(moby + 0x78);
    if (*(short *)(moby + 0xA6) == 0x41 && (unsigned char)moby[0x20] == 1) {
        char *child;
        D_0013D4EA.value = moby[0x20];
        moby[0x20] = 2;
        child = *(char **)(state + 8);
        if (child) child[0x20] = 2;
    }
}
INCLUDE_ASM("asm/overlays", func_L11_002D18D0);
extern void func_L02_002E2110(void *);
extern float func_001F9D10(void *, void *);
extern float D_L11_00167840[];
extern void func_L00_0025B178(void *);
extern void func_L11_002D21F0(char *);
extern void func_L11_002D2500(void *);
extern void func_L11_002D2670(void *);
extern void func_L11_002D3970(void *);

void func_L11_002D2168(unsigned char *moby) {
    func_L02_002E2110(moby);
    if (moby[0x31] && FastVecDist(moby + 0x10, D_L11_00167840) < 38.0f) {
        func_L00_0025B178(moby);
        moby[0x7F] = 30;
    }
    func_L11_002D21F0(moby);
    func_L11_002D2500(moby);
    func_L11_002D2670(moby);
    func_L11_002D3970(moby);
}
INCLUDE_ASM("asm/overlays", func_L11_002D21F0);
extern void func_L00_00259868(int, int, float, float, float, int);
extern void func_L00_00262DF0(float, void *, void *, void *);
extern void func_001F9BF0(void *, void *, void *);

/* moves the parts' positions and stores the moby's displacement since last frame */
void func_L11_002D2500(void *mp) {
    unsigned char *moby = mp;
    char *d = *(char **)(moby + 0x78);
    float A[4];
    float B[4];
    qcopy(A, moby + 0x10);
    qcopy(B, d + 0x130);
    func_L00_00259868((int)moby, (int)B, 0.5f, 0.3f, 0.0f, 0x10);
    if ((moby[0x20] >= 4 && moby[0x20] <= 6) || (moby[0x20] == 7 && *(int *)(d + 0x15C) == 3)) {
        func_L00_00262DF0(0.3f, *(void **)(d + 0x60 - -(*(int *)(d + 0x158) * 4)), moby + 0x10, moby + 0x10);
        switch (*(int *)(d + 0x158)) {
        case 2:
            func_L00_00262DF0(0.3f, *(void **)(d + 0x80), moby + 0x10, moby + 0x10);
            func_L00_00262DF0(0.3f, *(void **)(d + 0x84), moby + 0x10, moby + 0x10);
            func_L00_00262DF0(0.3f, *(void **)(d + 0x88), moby + 0x10, moby + 0x10);
            break;
        case 3:
            func_L00_00262DF0(0.3f, *(void **)(d + 0x80), moby + 0x10, moby + 0x10);
            func_L00_00262DF0(0.3f, *(void **)(d + 0x84), moby + 0x10, moby + 0x10);
            break;
        }
    }
    FastVecSub(d + 0x140, moby + 0x10, A);
}
INCLUDE_ASM("asm/overlays", func_L11_002D2670);
INCLUDE_ASM("asm/overlays", func_L11_002D3248);
extern int func_L00_0025A778(void *, void *, int);
extern int func_L01_00277FD8(int *, int, int, void *, void *, void *, float);
extern int *D_L11_001B11B0[];

struct TgtData {
    char pad0[0x60];
    int a[4];
    int b[4];
    int c[4];
    char pad1[0x90];
    char e[0x38];
    int idx;
};

// Checks a target against the current entry and runs the follow-up test.
int func_L11_002D3500(char *moby, char *other) {
    struct TgtData *d = *(struct TgtData **)(moby + 0x78);
    int *p = d->a;
    int *ent = D_L11_001B11B0[*(int *)((char *)p - (-(d->idx * 4)))];
    int buf[8];
    int n;
    if (func_L00_0025A778(other, ent + 4, *ent) == 0) return 0;
    buf[0] = *(int *)((char *)p - (-(d->idx * 4)));
    n = 1;
    switch (d->idx) {
    case 2:
        n = 4;
        buf[1] = d->c[0];
        buf[2] = d->c[1];
        buf[3] = d->c[2];
        break;
    case 3:
        n = 3;
        buf[1] = d->c[0];
        buf[2] = d->c[1];
        break;
    default:
        break;
    }
    return func_L01_00277FD8(buf, n, d->b[d->idx], moby + 0x10, other, d->e, 0.2f) != 0;
}
extern short D_L11_00160074;
extern int D_L11_00160074_m __asm__("D_L11_00160074") MACRO_ADDR;
extern short *D_L11_001AC540[];
extern int D_L11_00160058_m __asm__("D_L11_00160058") MACRO_ADDR;
extern int func_L11_00317598(char *);
extern float func_001F9D10(void *,void *);
/* tests nearby active objects in four selected class lists */
int func_L11_002D3620(char *moby) {
    int found = 0;
    char *data = *(char **)(moby + 0x78);
    char *groups;
    int i = 0;
    short *ids;
    int group;

    {
        char *first = data + 0x90;
        group = *(short *)(first + (*(int *)(data + 0x158) << 4));
    }
    if (group >= 0 && D_L11_00160074_m >= group) {
        do {
            groups = data + 0x90;
            ids = D_L11_001AC540[group];
            if (ids) {
                do {
                    unsigned int offset = (*(unsigned short *)ids & 0x7FFF) * 256;
                    char *other = (char *)(offset + D_L11_00160058_m);
                    if (other[0x20] >= 0 && (*(short *)(other + 0xA6) != 1246 || !func_L11_00317598(other))) {
                        found = 1;
                        if (func_001F9D10(moby + 0x10, (char *)D_L11_00160058_m + offset + 0x10) < 10.0f) return 2;
                    }
                } while (*ids++ >= 0);
            }
        } while (++i < 4 && (group = *(short *)(groups + (*(int *)(data + 0x158) * 16 + i * 4))) >= 0
                 && D_L11_00160074_m >= group);
    }
    return found;
}
extern int func_00215570(void *arg0, int arg1);
extern float func_001F9CB8(void *a);
extern void func_L00_001FF4B0(void *, void *, float);
extern void func_001F9BD8(void *, void *, void *);
extern float func_L00_0025A748_f(void *) __asm__("func_L00_0025A748");
extern float func_001F9B88(float);
extern int func_L00_001EFFF0(void *, void *, int, void *, int);
typedef int u128 __attribute__((mode(TI)));

/* Tests whether a moby can drop onto the ground, writing the landing point. */
int func_L11_002D37A8(char *m, float *out) {
    char *s = *(char **)(m + 0x78);
    int *p = (int *)(s + 0xF8);
    int i;
    int found = 0;
    float a[4];
    float b[4];
    float g;
    for (i = 0; i < 2; i++) {
        if (func_00215570(m + 0x10, *p)) {
            found = 1;
            break;
        }
        p++;
    }
    if (found) {
        float *pos = (float *)(m + 0x10);
        func_001F9BF0(a, out, pos);
        if (func_001F9CB8(a) > 4.0f) func_L00_001FF4B0(a, a, 4.0f);
        func_001F9BD8(a, a, pos);
        {
            int *q = D_L11_001B11B0[*(int *)(s - (-(*(int *)(s + 0x158) * 4)) + 0x60)];
            if (func_L00_0025A778(a, q + 4, *q)) {
                a[2] += 5.0f;
                g = func_L00_0025A748_f(a);
                if (func_001F9B88(g - *(float *)(m + 0x18)) > 0.5f) {
                    qcopy(b, pos);
                    b[2] += 0.15f;
                    a[2] = g + 0.15f;
                    if (func_L00_001EFFF0(b, a, 2, m, 0)) {
                        a[2] = g;
                        qcopy(out, a);
                        return 1;
                    }
                }
            }
        }
    }
    return 0;
}
INCLUDE_ASM("asm/overlays", func_L11_002D3970);
INCLUDE_ASM("asm/overlays", func_L11_002F21B0);
INCLUDE_ASM("asm/overlays", func_L11_002F3888);
extern void func_00215F80(int, int);

void func_L11_002F4040(char *moby) {
    char *data = *(char **)(moby + 0x78);
    switch (*(int *)(data + 0x10)) {
    case 0:
        try_set_help_message(0xB, 0x2B0D);
        break;
    case 3:
        try_set_help_message(0xB, 0x2B0B);
        break;
    case 1:
    case 2:
    case 4:
        try_set_help_message(0xB, 0x2B0C);
        break;
    default:
        try_set_help_message(0xB, 0);
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L11_002F40C8);
void func_L11_002F43B0(char *moby) {
    char *data = *(char **)(moby + 0x78);
    char **child = (char **)(data + 0x14);
    int count;
    int on;
    moby[0x31] = 1;
    *(unsigned short *)(moby + 0x34) &= 0xFFFE;
    *(int *)(moby + 0x94) = *(int *)(*(char **)(moby + 0x24) + 0x10);
    on = 1;
    count = 2;
    do {
        if (*child) {
            *(unsigned short *)(*child + 0x34) &= 0xFFFE;
            (*child)[0x31] = on;
            *(int *)(*child + 0x94) = *(int *)(*(char **)(*child + 0x24) + 0x10);
        }
        child++;
        count--;
    } while (count >= 0);
}
extern void func_0020D678(void *);
typedef struct {
    char pad0[0x88];
    float timer;
    char pad1[0x2FC - 0x8C];
    char *current;
    char pad2[0x30E - 0x300];
    short active;
    char pad3[0x2084 - 0x310];
    int mode;
    char pad4[0x22DA - 0x2088];
    unsigned short index;
} Globals;
extern Globals D_0013F450;

void func_L11_002F46C0(unsigned char *moby) {
    char *state = *(char **)(moby + 0x78);
    switch (moby[0x20]) {
    case 0:
        moby[0x30] = 0xFF;
        moby[0x20] = 1;
        if (*(int *)state == -1) DeleteMoby(moby);
        break;
    case 1:
        if (D_0013F450.timer > 194.0f && D_0013F450.mode != 0x32) {
            D_0013F450.index = *(unsigned short *)state;
        }
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L11_0030A748);
INCLUDE_ASM("asm/overlays", func_L11_0030AE90);
extern int func_001F9850(int);
extern void func_00213DE0(void *, int, int, int);

int func_L11_0030B850(unsigned char *moby) {
    char *current;
    if (moby[0x20] != 1) return 0;
    current = D_0013F450.current;
    if (current != (char *)moby || D_0013F450.active) return 0;
    current[0x20] = 2;
    if (((unsigned char *)current)[0x53]) {
        int value = scale_ticks(0x14);
        func_00213DE0(current, 0, 0, value);
    }
    return 1;
}
INCLUDE_ASM("asm/overlays", func_L11_0030B8D0);
int func_L11_0030BC00(unsigned char *arg) {
    return arg[0x20] == 5;
}

void func_L11_0030BC10(unsigned char *arg) {
    *(int *)(*(int *)(arg + 0x78) + 0xB8) = 1;
}
extern short *D_L11_001AC540[];
extern int D_L11_00160058_m __asm__("D_L11_00160058") MACRO_ADDR;
extern short D_L11_00160074;
extern int func_L11_00317598(char *);

// Returns 1 unless a listed moby in the group with state >= 0 and id 0x4DE fails the check.
int func_L11_0030BC20(char *m) {
    int idx = *(short *)(*(char **)(m + 0x78) + 0xB4);
    short *p;
    if (idx < 0 || *(int *)&D_L11_00160074 < idx) return 1;
    p = D_L11_001AC540[idx];
    if (p == 0) return 1;
    do {
        char *o = (char *)(((*p & 0x7FFF) << 8) + D_L11_00160058_m);
        if (o[0x20] >= 0 && *(short *)(o + 0xA6) == 0x4DE) {
            if (func_L11_00317598(o) == 0) return 0;
        }
    } while (*p++ >= 0);
    return 1;
}
INCLUDE_ASM("asm/overlays", func_L11_0030DBF8);
INCLUDE_ASM("asm/overlays", func_L11_0030E620);
INCLUDE_ASM("asm/overlays", func_L11_0030EC70);
INCLUDE_ASM("asm/overlays", func_L11_0030F188);
INCLUDE_ASM("asm/overlays", func_L11_0030F4F8);
extern void func_L01_002BA380(char *, int);
extern char D_L11_001DAB40[];
void func_L11_0030FBD0(void) {
    func_L01_002BA380(D_L11_001DAB40, 0x14);
}
INCLUDE_ASM("asm/overlays", func_L11_0030FBF8);
/* UpdateMoby_1159 (names.tsv role). Data block fields (+0x08 slot, +0x0C scale, +0x10, +0x14).
 * State 0: raises the moby by scale * 1.9, spawns a class 0x487 child that copies its position,
 * heading (func_001FA748 with pi), +0x34/+0x38 and the data block fields, and goes to state 1.
 * State 1: watches moby slot d[2]; when it is class 0x267 in state 4, or class 0x33E with byte
 * +0xBC set, marks a byte in the D_0013D355 + 0x13B table and goes to state 2. State 2: steps
 * the data block with func_00214D88 and moves the moby by the resulting vector.
 * The index-first sums (`idx + base`) and the Rec57 member are what keep retail's addressing. */
extern char *func_0020D348_c(int) __asm__("func_0020D348");
extern float func_001FA748_f(float, float) __asm__("func_001FA748");
extern void func_L00_00251E30_u(void *) __asm__("func_L00_00251E30");
extern void func_0022ED80_u(int, int, void *) __asm__("func_0022ED80");
extern float func_00214D88_f(float *, float *, float, float, float, float) __asm__("func_00214D88");
extern void func_L00_001FF4B0_u(void *, void *, float) __asm__("func_L00_001FF4B0");
extern void func_001F9BD8_u(void *, void *, void *) __asm__("func_001F9BD8");
extern unsigned char *D_L11_00160058_t __asm__("D_L11_00160058") MACRO_ADDR;
extern float D_0015EE6C_f __asm__("D_0015EE6C") MACRO_ADDR;
extern float D_0015EE70_f __asm__("D_0015EE70") MACRO_ADDR;
extern char D_0013D355_t[] __asm__("D_0013D355");
typedef struct { char pad[0x57]; char f57; } Rec57;

void func_L11_0030FE40(unsigned char *m) {
    char *d = *(char **)(m + 0x78);
    float v[4] __attribute__((aligned(16)));
    unsigned char *c;
    unsigned char *o;
    char *p;
    char *q;
    switch (m[0x20]) {
    case 0:
        *(float *)(m + 0x18) = *(float *)(m + 0x18) + *(float *)(d + 0xC) * 1.9f;
        c = (unsigned char *)func_0020D348_c(0x487);
        c[0x31] = 1;
        *(short *)(c + 0x32) = 0x40;
        *(long *)(c + 0x38) = *(long *)(m + 0x38);
        *(unsigned short *)(c + 0x34) = *(unsigned short *)(m + 0x34);
        qcopy(c + 0x10, m + 0x10);
        qcopy(c + 0x40, m + 0x40);
        *(float *)(c + 0x40) = func_001FA748_f(*(float *)(c + 0x40), 3.1415927f);
        func_L00_00251E30_u(c);
        p = *(char **)(c + 0x78);
        *(int *)(p + 8) = *(int *)(d + 8);
        *(float *)(p + 0x10) = *(float *)(d + 0x10);
        *(int *)(p + 0x14) = *(int *)(d + 0x14);
        q = *(char **)(m + 0x24);
        *(float *)(m + 0x2C) = *(float *)(q + 0x24) * *(float *)(d + 0xC);
        *(float *)(c + 0x2C) = *(float *)(q + 0x24) * *(float *)(d + 0xC);
        c[0x20] = 1;
        m[0x20] = 1;
        break;
    case 1:
        o = (unsigned char *)((*(int *)(d + 8) << 8) + (int)D_L11_00160058_t);
        if (*(short *)(o + 0xA6) == 0x267 && o[0x20] == 4) {
            goto go;
        }
        if (*(short *)(o + 0xA6) == 0x33E && o[0xBC] != 0) {
        go:
            m[0x20] = 2;
            ((Rec57 *)(*(int *)(d + 0x14) + (int)(D_0013D355_t + 0x13B)))->f57 = 1;
            func_0022ED80_u(0, 0, m);
        }
        break;
    case 2:
        func_00214D88_f((float *)d, (float *)(d + 4), *(float *)(d + 0x10), D_0015EE70_f, D_0015EE70_f, D_0015EE6C_f + D_0015EE6C_f);
        func_L00_001FF4B0_u(v, m + 0xD0, -*(float *)(d + 4));
        func_001F9BD8_u(m + 0x10, m + 0x10, v);
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L11_00310058);
INCLUDE_ASM("asm/overlays", func_L11_00310770);
extern char *func_0020D348(int);
extern float func_00214158(void);
extern void func_L00_00251E30(void *);
extern void func_L00_0025E210(void *);

char *func_L11_00310A70(void *position, void *vector, int id) {
    char *moby = CreateMoby(id);
    if (moby != 0) {
        char *data;
        float angle;
        ((unsigned char *)moby)[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        moby[0x31] = 1;
        moby[0x20] = 0;
        moby[0xBC] = 0;
        data = *(char **)(moby + 0x78);
        qcopy(moby + 0x10, position);
        qcopy(data + 0x10, vector);
        angle = random_angle_radians();
        *(int *)(moby + 0x40) = 0;
        *(float *)(moby + 0x48) = angle;
        *(float *)(moby + 0x44) = 0.7853982f;
        func_L00_00251E30(moby);
        func_L00_0025E210(moby);
    }
    return moby;
}
extern char *func_L11_00311260(char *);
extern void func_L00_00250800(void *, int, void *);
// Updates an attached object's transform or clears the unattached position state.
int func_L11_00310B28(char *owner, char *data) {
 char *child;
 if (!*(char **)(data + 0x34)) {
  *(char **)(data + 0x34) = func_L11_00311260(owner);
  if (!*(char **)(data + 0x34)) goto missing;
 }
 child = *(char **)(data + 0x34);
 if (*(unsigned char *)(child + 0x20) == 0xFE) goto missing;
 if (*(unsigned char *)(child + 0x20) == 0xFD) goto missing;
 qcopy(child + 0x10, owner + 0x10);
 qcopy(child + 0x40, owner + 0x40);
 func_L00_00251E30(child);
 func_L00_00250800(*(char **)(data + 0x34), 0, data);
 func_001F9BF0(data + 0x20, *(char **)(data + 0x34) + 0x10, data);
 return 1;
missing:
 qcopy(data, owner + 0x10);
 qzero(data + 0x20);
 return 0;
}
INCLUDE_ASM("asm/overlays", func_L11_00310BF0);
char *func_L11_00311260(char *owner) {
    char *moby = func_0020D348(0x4C3);
    if (moby != 0) {
        char *data;
        data = *(char **)(moby + 0x78);
        ((unsigned char *)moby)[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        moby[0x31] = 1;
        moby[0x20] = 0;
        moby[0xBC] = 0;
        qcopy(moby + 0x10, owner + 0x10);
        qcopy(moby + 0x40, owner + 0x40);
        *(char **)(data + 0x70) = owner;
        if ((unsigned char)moby[0x53] != 2) {
            func_00213DE0(moby, 2, 0xD, 0);
        }
        func_L00_00251E30(moby);
        func_L00_0025E210(moby);
    }
    return moby;
}
INCLUDE_ASM("asm/overlays", func_L11_00311318);
extern void func_L11_00311318(void *, void *, void *);
extern float func_0020D830(void *);

// Per-tick update of moby class 1219: state machine over states 0 to 4.
void func_L11_003114F0(unsigned char *moby)
{
    char *data = *(char **)(moby + 0x78);
    char *u = data + 0x20;
    unsigned char *t = *(unsigned char **)(data + 0x70);
    if (t == 0 || t[0x20] == 0xFE || t[0x20] == 0xFD) {
        if (moby[0x20] < 3) {
            moby[0x20] = 4;
        }
    }
    switch (moby[0x20]) {
    case 0:
        if (moby[0x53] != 1) {
            func_00213DE0(moby, 1, 0, 0xF);
        }
        moby[0x20] = 1;
        break;
    case 1:
        if (moby[0x70] & 2) {
            moby[0xA4] = 0xFF;
            moby[0x20] = 2;
        }
        break;
    case 2:
        func_L11_00311318(moby, data, u);
        if ((moby[0x70] & 2) && moby[0x53] != 1) {
            func_00213DE0(moby, 1, 0, 0xA);
        }
        break;
    case 3:
        if (moby[0x23] != 0) {
            moby[0x23]--;
        }
        if (func_0020D830(moby) > 13.5f) {
            moby[0x20] = 4;
        }
        break;
    case 4:
        DeleteMoby(moby);
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L11_00311648);
INCLUDE_ASM("asm/overlays", func_L11_00311B60);
