# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 the OpenRAC contributors
#
# The programs that open a window, and their libraries:
#
#   openrac_platform   SDL3: window and OpenGL 4.1 context, pads, audio, clock
#   openrac_renderer   the GPU renderer (OpenGL, loaded through the context;
#                      no SDL): per-subsystem renderers, the direct renderer,
#                      the texture pool
#   openrac-viewer     the native level viewer (docs/port/ROADMAP.md, P3)
#
# Included from port/CMakeLists.txt when OPENRAC_PORT_WINDOW is on.

include_guard(GLOBAL)
include(Dependencies)

# GLSL sources become C++ string constants in <name>_shaders.h / .cpp under
# the build directory: namespace <namespace>::shaders, one constant per file,
# named after it (direct.frag -> direct_frag). Shaders are part of the
# program, so a build never depends on files beside the executable. Editing a
# shader re-runs CMake's configure step, which rewrites only what changed.
function(openrac_embed_shaders target name namespace)
  set(dir "${CMAKE_CURRENT_BINARY_DIR}/generated")
  set(declarations "")
  set(definitions "")
  foreach(file IN LISTS ARGN)
    get_filename_component(base "${file}" NAME)
    string(REPLACE "." "_" symbol "${base}")
    file(READ "${file}" text)
    string(APPEND declarations "extern const char *const ${symbol};\n")
    string(APPEND definitions "const char *const ${symbol} = R\"glsl(${text})glsl\";\n")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${file}")
  endforeach()
  set(banner "// Generated by port/cmake/Window.cmake from GLSL sources; do not edit.\n")
  file(CONFIGURE OUTPUT "${dir}/${name}_shaders.h"
    CONTENT "${banner}#pragma once\n\nnamespace ${namespace}::shaders {\n${declarations}}\n"
    @ONLY)
  file(CONFIGURE OUTPUT "${dir}/${name}_shaders.cpp"
    CONTENT "${banner}#include \"${name}_shaders.h\"\n\nnamespace ${namespace}::shaders {\n${definitions}}\n"
    @ONLY)
  target_sources(${target} PRIVATE "${dir}/${name}_shaders.cpp")
  target_include_directories(${target} PRIVATE "${dir}")
endfunction()

# ---- platform ----
add_library(openrac_platform STATIC
  platform/audio.cpp
  platform/clock.cpp
  platform/input.cpp
  platform/pad.cpp
  platform/window.cpp
)
target_link_libraries(openrac_platform PUBLIC openrac_common openrac_sdl3)
openrac_warnings(openrac_platform)

# ---- renderer ----
add_library(openrac_renderer STATIC
  renderer/direct.cpp
  renderer/framebuffer.cpp
  renderer/gl.cpp
  renderer/renderer.cpp
  renderer/shader.cpp
  renderer/subsystems.cpp
  renderer/texture.cpp
  renderer/texture_pool.cpp
)
openrac_embed_shaders(openrac_renderer renderer openrac::renderer
  "${CMAKE_CURRENT_SOURCE_DIR}/renderer/shaders/direct.vert"
  "${CMAKE_CURRENT_SOURCE_DIR}/renderer/shaders/direct.frag"
)
target_link_libraries(openrac_renderer PUBLIC openrac_common)
openrac_warnings(openrac_renderer)

# ---- the world's renderers: renderer/world, shaders in renderer/shaders/world ----
file(GLOB world_sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/renderer/world/*.cpp")
if(world_sources)
  add_library(openrac_renderer_world STATIC ${world_sources})
  file(GLOB world_shaders CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/renderer/shaders/world/*.vert"
    "${CMAKE_CURRENT_SOURCE_DIR}/renderer/shaders/world/*.frag"
    "${CMAKE_CURRENT_SOURCE_DIR}/renderer/shaders/world/*.glsl")
  list(SORT world_shaders)
  openrac_embed_shaders(openrac_renderer_world world openrac::renderer::world ${world_shaders})
  target_link_libraries(openrac_renderer_world PUBLIC openrac_renderer)
  openrac_warnings(openrac_renderer_world)
  openrac_add_module_tests(world openrac_renderer_world openrac_platform)
endif()

# ---- the level viewer ----
# cgltf and stb are compiled once, as C, without the port's warnings.
add_library(openrac_viewer_third_party STATIC viewer/third_party.c)
target_link_libraries(openrac_viewer_third_party PUBLIC openrac_cgltf openrac_stb)
if(MSVC AND NOT CMAKE_C_COMPILER_ID MATCHES "Clang")
  target_compile_options(openrac_viewer_third_party PRIVATE /w)
else()
  target_compile_options(openrac_viewer_third_party PRIVATE -w)
endif()

add_library(openrac_viewer_lib STATIC
  viewer/camera.cpp
  viewer/json.cpp
  viewer/level.cpp
  viewer/level_renderer.cpp
  viewer/screenshot.cpp
)
openrac_embed_shaders(openrac_viewer_lib viewer openrac::viewer
  "${CMAKE_CURRENT_SOURCE_DIR}/viewer/shaders/mesh.vert"
  "${CMAKE_CURRENT_SOURCE_DIR}/viewer/shaders/mesh.frag"
  "${CMAKE_CURRENT_SOURCE_DIR}/viewer/shaders/sky.vert"
  "${CMAKE_CURRENT_SOURCE_DIR}/viewer/shaders/sky.frag"
)
target_link_libraries(openrac_viewer_lib PUBLIC openrac_renderer openrac_viewer_third_party)
openrac_warnings(openrac_viewer_lib)

add_executable(openrac-viewer viewer/main.cpp)
target_link_libraries(openrac-viewer PRIVATE openrac_viewer_lib openrac_platform)
openrac_warnings(openrac-viewer)

# ---- tests ----
# Tests that need an OpenGL context create one through SDL's offscreen
# driver (EGL; Mesa's llvmpipe on a machine without a GPU) and exit with 77,
# reported as skipped, when none can be made.
add_executable(platform_test tests/platform_test.cpp)
target_link_libraries(platform_test PRIVATE openrac_platform)
openrac_warnings(platform_test)
add_test(NAME platform COMMAND platform_test)
set_tests_properties(platform PROPERTIES ENVIRONMENT "SDL_AUDIO_DRIVER=dummy")

add_executable(renderer_texture_test tests/renderer_texture_test.cpp)
target_link_libraries(renderer_texture_test PRIVATE openrac_renderer)
openrac_warnings(renderer_texture_test)
add_test(NAME renderer_texture COMMAND renderer_texture_test)

add_executable(renderer_gif_test tests/renderer_gif_test.cpp)
target_link_libraries(renderer_gif_test PRIVATE openrac_renderer)
openrac_warnings(renderer_gif_test)
add_test(NAME renderer_gif COMMAND renderer_gif_test)

add_executable(renderer_direct_test tests/renderer_direct_test.cpp)
target_link_libraries(renderer_direct_test PRIVATE openrac_renderer openrac_platform)
openrac_warnings(renderer_direct_test)
add_test(NAME renderer_direct COMMAND renderer_direct_test)
set_tests_properties(renderer_direct PROPERTIES SKIP_RETURN_CODE 77)

add_executable(viewer_test tests/viewer_test.cpp)
target_link_libraries(viewer_test PRIVATE openrac_viewer_lib openrac_platform)
openrac_warnings(viewer_test)
add_test(NAME viewer COMMAND viewer_test "${CMAKE_CURRENT_BINARY_DIR}/viewer_test_level")
set_tests_properties(viewer PROPERTIES SKIP_RETURN_CODE 77)
