/* Level 14 (Oltanis) code following help; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

extern unsigned char D_0013E633[];
extern int D_0015EE84_m __asm__("D_0015EE84") MACRO_ADDR;
extern void func_001F99D8(void *, int);
extern int func_L00_001F10E0(float, void *, int, void *);
extern int func_L00_001F3958(void);
extern float func_001F9B88(float);
extern void func_L00_0020BFA8(void);
extern void func_L14_002306C8(int, int);

/* Resolve the hero's surface reaction for the frame from the previous state and flags. */
void func_L14_0021E3A8(void) {
    char *h;
    char *g = (char *)D_0013E633 + 0xE1D;
    int keep = *(unsigned char *)(g + 0x12ED);
    int st = *(short *)(g + 0x12E0);
    FastMemZero16(g + 0x12E0, 0x10);
    *(unsigned char *)(g + 0x12ED) = keep;
    *(short *)(g + 0x12E0) = -1;
    *(unsigned char *)(g + 0x20A9) = 0;
    *(short *)(g + 0x308) = 0;
    if (st == -1) return;
    if (st == 2) {
        if (*(short *)(g + 0x30C) == 0 || *(float *)(g + 0x2DC) < 0.3f) {
            *(unsigned char *)(g + 0x12E7) = 1;
            if (*(unsigned char *)(g + 0x20A4) == 0) {
                char *p = *(char **)(g + 0x10E0);
                if (p != 0 && *(short *)(p + 0xA6) == 0xAD) {
                    *(short *)(g + 0x308) = 1;
                }
            }
        }
    }
    if (D_0015EE84_m == 0xD) {
        char *q = (char *)D_0013E633 + 0xE1D;
        if (*(int *)(q + 0x2084) != 0x7B) {
            if (coll_sphere(*(float *)(q + 0x234) + 0.03f, q + 0xD0, 2, 0)) {
                if (CollType() == 0xB) {
                    func_L14_002306C8(0x7B, 1);
                    return;
                }
            }
        }
    }
    if (st == 0xB) { char *q = (char *)D_0013E633 + 0xE1D; *(unsigned char *)(q + 0x12EB) = 1; }
    if (st == 2) { char *q = (char *)D_0013E633 + 0xE1D; *(unsigned char *)(q + 0x12E7) = 1; }
    if (st == 7) { char *q = (char *)D_0013E633 + 0xE1D; *(unsigned char *)(q + 0x12E2) = 1; }
    if (st == 0xD) { char *q = (char *)D_0013E633 + 0xE1D; *(unsigned char *)(q + 0x12EC) = 1; }
    if (st == 8) { char *q = (char *)D_0013E633 + 0xE1D; *(unsigned char *)(q + 0x12EA) = 1; }
    if (st == 9) { char *q = (char *)D_0013E633 + 0xE1D; *(unsigned char *)(q + 0x12EE) = 1; }
    if (st == 0xC) { char *q = (char *)D_0013E633 + 0xE1D; *(unsigned char *)(q + 0x12EA) = 1; }
    h = (char *)D_0013E633 + 0xE1D;
    if (*(unsigned char *)(h + 0x12EC) != 0) {
        if (*(int *)(h + 0x2084) == 0x7F) return;
        if (FastAbsF(*(float *)(h + 0x2F0) - (*(float *)(h + 0x88) + 0.25f)) < 1.0f) {
            if (*(float *)(h + 0x2F0) - *(float *)(h + 0x88) > 0.0f) {
                if (*(float *)(h + 0x108) < 0.0f) {
                    func_L00_0020BFA8();
                    func_L14_002306C8(0x7F, 1);
                }
            }
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L14_00223140);
INCLUDE_ASM("asm/overlays", func_L14_002235D0);
INCLUDE_ASM("asm/overlays", func_L14_00229440);
