/* Level 14 (Oltanis) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L14_002ACCC0);
extern float func_L00_0025C918(float *p, float *v, float t, float u1, float u2, float eps);
extern int *D_L14_001B0F30[];

// Pick a keyframe vector from the moby's table and ease the moby position toward it per axis.
void func_L14_002AD4F8(char *moby) {
    char *data = *(char **)(moby + 0x78);
    float v[4];
    char *src;
    int *tab;
    tab = D_L14_001B0F30[*(int *)(data + 0xB4)];
    if (*(float *)(data + 0xA4) > 0.5f) {
        src = (char *)(tab[0] * 16 + (int)tab);
        qcopy(v, src);
    } else {
        src = (char *)tab + 0x10;
        qcopy(v, src);
    }
    func_L00_0025C918((float *)(moby + 0x10), (float *)(data + 0xD0), v[0], 0.005f, 0.2f, 0.0f);
    func_L00_0025C918((float *)(moby + 0x14), (float *)(data + 0xD4), v[1], 0.005f, 0.2f, 0.0f);
    func_L00_0025C918((float *)(moby + 0x18), (float *)(data + 0xD8), v[2], 0.005f, 0.2f, 0.0f);
}
INCLUDE_ASM("asm/overlays", func_L14_002AD858);
extern char *func_L00_0025B478(void *, int, int);
extern int func_L00_0025B4D0(void *, void *, void *, int, void *, void *, int, int);
extern void func_00213DE0(void *, int, int, int);
extern void func_L00_002584A8(void *, int, int);
extern void func_L00_0025E4B0(void *m, short *p);
extern void func_L00_0025E590(void *, void *);

/* per-frame update: runs the hit query, decays a timer, then dispatches on the hit result */
void func_L14_002AEAF8(char *moby) {
    char *data = *(char **)(moby + 0x78);
    int st;
    float t;
    int v;
    t = 0.0f;
    v = func_L00_0025B4D0(moby, func_L00_0025B478(moby, 0x330000, 0), data + 0x20, 0, &st, &t, 0, 4);
    if (st != 1 && ((unsigned char *)moby)[0x20] < 7) {
        float f = *(float *)(data + 0x20) - t;
        *(float *)(data + 0x20) = f;
        if (f <= 0.0f) v = 1;
        if (((unsigned char *)moby)[0x20] == 1) moby[0x20] = 2;
        if (st == 3) moby[0xBC] = 1;
        switch (v) {
        case 9:
        case 10:
            data[0x67] = 0x64;
            func_00213DE0(moby, 1, 0, 5);
            break;
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
            ((unsigned char *)data)[0x67] = 0xC8;
            func_00213DE0(moby, 1, 0, 5);
            break;
        case 1:
        case 2:
            moby[0x20] = 7;
            *(unsigned short *)(moby + 0x34) &= 0xEFFF;
            func_L00_002584A8(moby, 0, -1);
            break;
        case 0:
        case 11:
            break;
        }
        func_L00_0025E4B0(moby, (short *)(data + 0x60));
    }
    ((unsigned char *)moby)[0xA4] = 0xFF;
    func_L00_0025E590(moby, data + 0x60);
}
INCLUDE_ASM("asm/overlays", func_L14_002AEC58);
INCLUDE_ASM("asm/overlays", func_L14_002AEF88);
INCLUDE_ASM("asm/overlays", func_L14_002AF2E8);
typedef struct {
    float m[4][4];
    u32 col[4];
    float uv[8];
    u64 a, b, c, d;
} Pk_2af4a0;
extern char D_L14_001675C0[];
extern float D_L14_001D8940[4][4];
extern short D_L14_00161544;
extern short D_L14_00161548;
u64 func_001F4868(s32);
extern void func_00234C98(int, long);
extern void func_001F9BF0(void *, void *, void *);
extern float func_001F9CB8(void *);
extern void func_L00_001FF4B0(void *, void *, float);
extern void func_001F9BD8(void *, void *, void *);
extern void func_001F9C30(void *, void *, float);
extern void func_L00_001FD1D8(void *, void *, s32);

/* Draws the moby's glow quad, pulled toward the camera so it is not hidden by the moby. */
void func_L14_002AF4A0(char *m) {
    char *d = *(char **)(m + 0x78);
    float pos[4];
    Pk_2af4a0 pk;
    float v[4];
    float w[4];
    float len;
    u32 col;
    int j;
    qcopy(pos, d + 0x90);
    pos[2] += 0.01f;
    pos[3] = 1.0f;
    pk.b = func_001F4868(0xB);
    pk.c = 0x0000FF9000000260ULL;
    pk.d = 0x8000000048ULL;
    pk.a = 0;
    func_00234C98(0x4A, 0);
    func_00234C98(0x47, 0x51001);
    func_001F9BF0(v, D_L14_001675C0, pos);
    len = func_001F9CB8(v);
    if (0.0f < len) {
        float s = *(float *)(d + 0x218);
        float f = len - *(float *)&D_L14_00161544;
        if (f < s) {
            s = f;
            if (f < 0.0f) s = 0.0f;
        }
        func_L00_001FF4B0(w, v, s);
        func_001F9BD8(pos, pos, w);
    }
    pk.uv[2] = 0.0f;
    pk.uv[0] = 1.0f;
    pk.uv[1] = 1.0f;
    pk.uv[3] = 1.0f;
    pk.uv[4] = 1.0f;
    pk.uv[5] = 0.0f;
    pk.uv[6] = 0.0f;
    pk.uv[7] = 0.0f;
    if (*(short *)(d + 0x202) != 0) {
        col = 0x7F40407F;
        pk.col[3] = col;
        pk.col[2] = col;
        pk.col[1] = col;
        pk.col[0] = col;
    } else {
        col = *(u32 *)&D_L14_00161548;
        pk.col[3] = col;
        pk.col[2] = col;
        pk.col[1] = col;
        pk.col[0] = col;
    }
    for (j = 0; j < 4; j++) {
        func_001F9C30(pk.m[j], D_L14_001D8940[j], *(float *)(d + 0x214));
        func_001F9BD8(pk.m[j], pk.m[j], pos);
    }
    func_L00_001FD1D8(&pk, 0, 0);
}
extern int *D_L14_001B0F30[];
extern float func_001F9D10(void *, void *);
extern int func_L00_0025E860_2AF688(void *, void *, void *, void *, int, float) __asm__("func_L00_0025E860");

/* Measures the segments of the moby's three paths, sums two of them and places it on the first two. */
void func_L14_002AF688(char *m) {
    char *d = *(char **)(m + 0x78);
    int *p;
    int i;
    float len;
    p = D_L14_001B0F30[*(int *)(d + 0x78)];
    *(int *)(d + 0x16C) = 0;
    for (i = 0; i < p[0]; i++) {
        len = func_001F9D10((char *)p + (i * 16 + 0x10), (char *)p + (((i + 1) % p[0]) * 16 + 0x10));
        *(float *)((char *)p + (i << 4) + 0x1C) = len;
        if (i != p[0] - 1) {
            *(float *)(d + 0x16C) += len;
        }
    }
    p = D_L14_001B0F30[*(int *)(d + 0x74)];
    *(int *)(d + 0x190) = 0;
    for (i = 0; i < p[0]; i++) {
        len = func_001F9D10((char *)p + (i * 16 + 0x10), (char *)p + (((i + 1) % p[0]) * 16 + 0x10));
        *(float *)((char *)p + (i << 4) + 0x1C) = len;
        if (i != p[0] - 1) {
            *(float *)(d + 0x190) += len;
        }
    }
    p = D_L14_001B0F30[*(int *)(d + 0x204)];
    for (i = 0; i < p[0]; i++) {
        *(float *)((char *)p + (i << 4) + 0x1C) = func_001F9D10((char *)p + (i * 16 + 0x10), (char *)p + (((i + 1) % p[0]) * 16 + 0x10));
    }
    if (*(float *)(d + 0x210) != 0.0f) {
        int *q = D_L14_001B0F30[*(int *)(d + 0x78)];
        *(int *)(d + 0x84) = 0;
        *(float *)(d + 0x1CC) = 0.0f;
        func_L00_0025E860_2AF688(q, m + 0x10, d + 0x84, d + 0x1CC, *(short *)(d + 0x8A), *(float *)(d + 0x210) * *(float *)(d + 0x16C));
        *(float *)(d + 0x8C) = 0.0f;
        *(int *)(d + 0x80) = 0;
        func_L00_0025E860_2AF688(q, m + 0x10, d + 0x80, d + 0x8C, *(short *)(d + 0x8A), *(float *)(d + 0x210) * *(float *)(d + 0x190));
    } else {
        *(int *)(d + 0x80) = 0;
        *(int *)(d + 0x84) = 0;
        *(float *)(d + 0x8C) = 0.0f;
        *(float *)(d + 0x1CC) = 0.0f;
    }
}
extern float func_L00_0025C918(float *p, float *v, float t, float u1, float u2, float eps);
extern int func_L00_0025E860_2AF918(int *tab, float *out, int *a, float *b, int c, float d) __asm__("func_L00_0025E860");
extern int *D_L14_001B0F30[];
extern short D_L14_00161468;
extern short D_L14_0016146C;

// Run the lookup for the moby's track, ease three axes, and on a wrap-around reset and flip the direction.
void func_L14_002AF918(char *moby) {
    char *data = *(char **)(moby + 0x78);
    float v[4];
    float save = *(float *)(data + 0x1CC);
    int save2 = *(int *)(data + 0x84);
    int r = func_L00_0025E860_2AF918(D_L14_001B0F30[*(int *)(data + 0x78)], v, (int *)(data + 0x84),
                              (float *)(data + 0x1CC), *(short *)(data + 0x8A), *(float *)(data + 0x168));
    func_L00_0025C918((float *)(data + 0x170), (float *)(data + 0x180), v[0], *(float *)&D_L14_00161468, *(float *)&D_L14_0016146C, 0.0f);
    func_L00_0025C918((float *)(data + 0x174), (float *)(data + 0x184), v[1], *(float *)&D_L14_00161468, *(float *)&D_L14_0016146C, 0.0f);
    func_L00_0025C918((float *)(data + 0x178), (float *)(data + 0x188), v[2], *(float *)&D_L14_00161468, *(float *)&D_L14_0016146C, 0.0f);
    if (*(short *)(data + 0x8A) == 0) {
        if (r != 0) {
            *(float *)(data + 0x1CC) = save;
            *(int *)(data + 0x84) = save2;
            *(float *)(data + 0x168) = -*(float *)(data + 0x168);
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L14_002AFA18);
extern int func_L00_0025E860_2AFB40(void *, void *, void *, void *, int, float) __asm__("func_L00_0025E860");
extern float D_0015EE6C MACRO_ADDR;
extern short D_L14_001614C4;

/* Picks a target point from a list or searches for one, then eases the moby's position toward it per axis. */
void func_L14_002AFB40(char *moby, float a, float b, float c) {
    char *data = *(char **)(moby + 0x78);
    int *list = D_L14_001B0F30[*(int *)(data + 0x204)];
    float tmp[4];
    if (*(short *)(data + 0x208) != 0) {
        qcopy(tmp, (char *)list + list[0] * 16);
    } else {
        if (func_L00_0025E860_2AFB40(list, tmp, data + 0x80, data + 0x8C, 0, b * D_0015EE6C * c) != 0) {
            *(short *)(data + 0x208) = 1;
        }
    }
    func_L00_0025C918((float *)(moby + 0x10), (float *)(data + 0x194), tmp[0], a, *(float *)&D_L14_001614C4, 0.0f);
    func_L00_0025C918((float *)(moby + 0x14), (float *)(data + 0x198), tmp[1], a, *(float *)&D_L14_001614C4, 0.0f);
    func_L00_0025C918((float *)(moby + 0x18), (float *)(data + 0x19C), tmp[2], a, *(float *)&D_L14_001614C4, 0.0f);
}
extern void func_L00_00263B78(float, float, char *, float *, float *);
extern void func_L00_00263BF8(void *, char *, char *, float, float, float);
extern int func_001F9938(void *);
extern int func_001F9850(int);
extern int func_002140B0(int);
extern float func_001FA748(float, float);
extern float func_L00_0025C918(float *p, float *v, float t, float u1, float u2, float eps);
extern short D_L14_00161470;
extern short D_L14_00161474;
extern short D_L14_00161478;
extern short D_L14_0016147C;
extern short D_L14_00161480;
extern short D_L14_00161484;
extern short D_L14_00161488;
extern short D_L14_0016148C;
extern short D_L14_00161490;
extern short D_L14_00161494;

// Per-frame update of a moby's aim and turn state from level tuning constants.
void func_L14_002AFC48(char *moby) {
    char *data = *(char **)(moby + 0x78);
    float t;
    func_L00_00263B78(*(float *)&D_L14_00161470, *(float *)&D_L14_00161474, moby, (float *)(data + 0x1A0), (float *)(data + 0x1A4));
    func_L00_00263BF8(moby, data + 0x1A8, data + 0x1AC, *(float *)&D_L14_00161478, *(float *)&D_L14_0016147C, *(float *)&D_L14_00161480);
    if (*(unsigned char *)(moby + 0x20) == 1) {
        if (FastDecTimer(data + 0x1B4)) {
            *(short *)(data + 0x1B4) = scale_ticks(*(int *)&D_L14_00161484);
            t = *(float *)&D_L14_00161488;
            if (random_integer_below(2)) t = -t;
            *(float *)(data + 0x1B0) = FastAddRots(*(float *)(moby + 0x48), t);
        }
        func_L00_0025C918((float *)(moby + 0x48), (float *)(data + 0x1B8), *(float *)(data + 0x1B0),
                          *(float *)&D_L14_0016148C, *(float *)&D_L14_00161490, *(float *)&D_L14_00161494);
    }
}
extern short D_L14_00161464;
extern int func_002140B0(int);
extern float func_001FA888(int);
extern int func_L00_00200290(char *, float);
extern void func_0020DAF8(char *, int, void *);
extern void func_L00_001FF4B0(void *, void *, float);

/* Checks a flag and a position test, then sets up three vectors in the moby data. */
void func_L14_002AFD18(char *moby) {
    char *data = *(char **)(moby + 0x78);
    char *p;
    float v[4];
    if (random_integer_below(5)) {
        qcopy(v, moby + 0x10);
        v[3] = *(float *)&D_L14_00161464;
        if (FastBSphereCheck((char *)v, func_001FA888(*(short *)(moby + 0x32))) >= 0) {
            p = data + 0xA0;
            func_0020DAF8(moby, 1, p);
            func_L00_001FF4B0(p, p, 1.0f);
            func_L00_001FF4B0(data + 0xB0, data + 0xB0, 1.0f);
            func_L00_001FF4B0(data + 0xC0, data + 0xC0, 1.0f);
            *(int *)(data + 0x20C) = 2;
        }
    }
}
extern void func_001F9BF0(void *dst, void *a, void *b);
extern void func_001F9C30(void *, void *, float);
extern void func_001F9BD8(void *, void *, void *);
extern float func_001F9CB8(void *a);
extern float func_L00_001FF860(float, float);
extern float func_001FA790(float, float);
extern void func_L00_001FFED8(void *, int, float);
extern float func_001F9CE8(void *);
extern void func_001F49B0(void *, void *);
extern void func_L14_002AF4A0(char *);

// Sets up the moby's motion data from its vectors; returns whether it succeeded.
int func_L14_002AFDE0(char *moby, int flag) {
    int ok = 0;
    char *data = *(char **)(moby + 0x78);
    float w[4];
    float v[4];
    float t;
    func_001F9BF0(v, data + 0x170, data + 0xD0);
    func_001F9C30(v, v, 0.5f);
    func_001F9BD8(w, data + 0xD0, v);
    w[3] = func_001F9CB8(v) + 2.0f;
    if (func_L00_00200290((char *)w, func_001FA888(*(short *)(moby + 0x32))) >= 0) {
        func_0020DAF8(moby, 1, data + 0xA0);
        ok = 1;
        func_L00_001FF4B0(data + 0xA0, data + 0xA0, 1.0f);
        func_L00_001FF4B0(data + 0xB0, data + 0xB0, 1.0f);
        func_L00_001FF4B0(data + 0xC0, data + 0xC0, 1.0f);
        t = func_001FA790(func_L00_001FF860(v[0], v[1]), *(float *)(moby + 0x48));
        func_L00_001FFED8(data + 0xF0, 2, t);
        *(float *)(data + 0x1BC) = t;
        t = -func_L00_001FF860(func_001F9CE8(v), v[2]);
        func_L00_001FFED8(data + 0x130, 1, t);
        *(float *)(data + 0x1C0) = t;
        qcopy(data + 0x90, data + 0x170);
        if (flag != 0) {
            func_001F49B0(func_L14_002AF4A0, moby);
            *(int *)(data + 0x20C) |= 2;
        }
    }
    return ok;
}
extern int func_001FA898_r(float) __asm__("func_001FA898");
extern int D_L14_001D8510[];
extern int D_L14_001D83C8[];
extern short D_L14_001614E0;

/* Advance the blink phase and fade each light entry's alpha up and down. */
void func_L14_002AFF90(char *moby) {
    char *data = *(char **)(moby + 0x78);
    int step;
    int i;
    float f = *(float *)(data + 0x164) + 0.5f;
    *(float *)(data + 0x164) = f;
    step = func_001FA898_r(f);
    if (*(float *)(data + 0x164) >= 1.0f) *(int *)(data + 0x164) = 0;
    for (i = 0; i < *(int *)&D_L14_001614E0; i++) {
        int v = D_L14_001D8510[i];
        if (v != 0) {
            v += step;
            if (v > 0x90) v -= 0x80;
            D_L14_001D8510[i] = v;
            if (v > 0x50) v = 0xA0 - v;
            D_L14_001D83C8[i] = (D_L14_001D83C8[i] & 0xFFFFFF) | (v << 24);
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L14_002B0068);
extern float func_001F9D48(void *, void *);
extern short *D_L14_001AC2C0_2B0168[] __asm__("D_L14_001AC2C0");
extern int D_L14_001D8980[];
extern char D_L14_001675C0[];
extern char *D_L14_00160098_2B0168 __asm__("D_L14_00160098") MACRO_ADDR;

/* Returns the farthest moby in a list that is not in the excluded-id table, by distance from a point. */
char *func_L14_002B0168(int index) {
    short *p = D_L14_001AC2C0_2B0168[index];
    char *best = 0;
    float bestd = 0.0f;
    if (p == 0) return 0;
    do {
        char *moby = D_L14_00160098_2B0168 + ((*(unsigned short *)p & 0x7FFF) << 8);
        int found = 0;
        int i;
        for (i = 0; i < 20; i++) {
            if (*(short *)(moby + 0xB2) == D_L14_001D8980[i]) {
                found = 1;
                break;
            }
        }
        if (!found) {
            float d = func_001F9D48(D_L14_001675C0, moby + 0x10);
            if (bestd < d) {
                bestd = d;
                best = moby;
            }
        }
    } while (*p++ >= 0);
    return best;
}
/* counts table entries through the first negative terminator */
int func_L14_002B0288(char *moby) {
    short *table = D_L14_001AC2C0_2B0168[(unsigned char)moby[0x21]];
    int count = 0;
    if (table == 0)
        return 0;
    do {
        count++;
    } while (*table++ >= 0);
    return count;
}
INCLUDE_ASM("asm/overlays", func_L14_002B02B0);
INCLUDE_ASM("asm/overlays", func_L14_002B4E40);
extern void func_L00_0025E4B0(void *, short *);

// advances a moby's animation timer and picks its next state
void func_L14_002B5590(unsigned char *m) {
    unsigned char *d = *(unsigned char **)(m + 0x78);
    int loc0;
    float f4 = 0.0f;
    char *q;
    int k;
    float t;
    q = func_L00_0025B478(m, 0x330000, 0);
    if (q != 0) {
        if (*(int *)(q + 0x20) != 0) {
            int a = *(short *)(*(int *)(q + 0x20) + 0xA6);
            if (a == *(short *)(m + 0xA6) || a == 0x2A9) q = 0;
        }
    }
    k = func_L00_0025B4D0(m, q, d + 0x20, 0, &loc0, &f4, 0, 4);
    if (loc0 != 1 && *(unsigned char *)(m + 0x20) != 6) {
        t = *(float *)(d + 0x20) - f4;
        *(float *)(d + 0x20) = t;
        if (t <= 0.0f) k = 1;
        switch (k) {
        case 0:
        case 11:
            break;
        case 9:
        case 10:
            d[0x67] = 100;
            break;
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
            d[0x67] = 200;
            break;
        case 1:
        case 2:
            m[0x20] = 6;
            *(unsigned short *)(m + 0x34) &= 0xEFFF;
            d[0x67] = 0xF0;
            func_L00_002584A8(m, 0, -1);
            break;
        }
        func_L00_0025E4B0(m, (short *)(d + 0x60));
    }
    m[0xA4] = 0xFF;
    func_L00_0025E590(m, d + 0x60);
}
extern int *D_L14_001AC2C0[];
extern short D_L14_00160098;

// Marks each listed moby whose state is 1 by writing 1 into its data's field 0x88.
void func_L14_002B56F8(int idx) {
    short *p = (short *)D_L14_001AC2C0[idx];
    if (p != 0) {
        char *base = *(char **)&D_L14_00160098;
        do {
            unsigned char *moby = (unsigned char *)base + ((*p & 0x7FFF) << 8);
            int s = moby[0x20];
            if (s == 1) {
                *(short *)(*(char **)(moby + 0x78) + 0x88) = s;
            }
        } while (*p++ >= 0);
    }
}
INCLUDE_ASM("asm/overlays", func_L14_002B5750);
// Tests whether a vendor group has no active unready objects.
int func_L14_002B58C0(int index) {
 unsigned short *list = (unsigned short *)D_L14_001AC2C0_2B0168[index];
 int count = 0;
 char *base;
 if (list) goto scan;
success:
 return 1;
scan:
 base = D_L14_00160098_2B0168;
 do {
  unsigned short id = *list;
  char *moby = base + ((id & 0x7FFF) << 8);
  int state = *(signed char *)(moby + 0x20);
  char *data = *(char **)(moby + 0x78);
  if (state >= 0) count++;
  if (state >= 0 && *(short *)(data + 0x88)) goto success;
  list++;
  if ((short)id < 0) return count == 0;
 } while (1);
}
INCLUDE_ASM("asm/overlays", func_L14_002B58E4);
INCLUDE_ASM("asm/overlays", func_L14_002B5938);
/* Sibling of func_L14_002B5590 (84% similar): same collision step on the moby's data block, but
 * it is skipped for states 0 and 9, state 9 is what cases 1/2 set (6 in the sibling) and cases
 * 3-8 also start func_00213DE0 and store 1.75f at +0x58. Written from the sibling's C; f4 has to
 * be zeroed after the +0x2C store. */
void func_L14_002B64E0(unsigned char *m) {
    unsigned char *d = *(unsigned char **)(m + 0x78);
    int loc0;
    float f4;
    char *q;
    int k;
    float t;
    if (m[0x20] == 0 || m[0x20] == 9) {
        return;
    }
    *(float *)(m + 0x2C) = *(float *)(*(char **)(m + 0x24) + 0x24);
    f4 = 0.0f;
    q = func_L00_0025B478(m, 0x330000, 0);
    if (q != 0) {
        if (*(int *)(q + 0x20) != 0) {
            int a = *(short *)(*(int *)(q + 0x20) + 0xA6);
            if (a == *(short *)(m + 0xA6) || a == 0x370) q = 0;
        }
    }
    k = func_L00_0025B4D0(m, q, d + 0x20, 0, &loc0, &f4, 0, 4);
    if (loc0 != 1 && m[0x20] != 9) {
        t = *(float *)(d + 0x20) - f4;
        *(float *)(d + 0x20) = t;
        if (t <= 0.0f) k = 1;
        switch (k) {
        case 0:
        case 11:
            break;
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
            func_00213DE0(m, 2, 0, 5);
            *(float *)(m + 0x58) = 1.75f;
        case 9:
        case 10:
            d[0x67] = 0xFA;
            break;
        case 1:
        case 2:
            m[0x20] = 9;
            *(unsigned short *)(m + 0x34) &= 0xEFFF;
            d[0x67] = 0xFA;
            func_L00_002584A8(m, 0, -1);
            break;
        }
        func_L00_0025E4B0(m, (short *)(d + 0x60));
    }
    m[0xA4] = 0xFF;
    func_L00_0025E590(m, d + 0x60);
}
extern short D_L14_00161600;
extern short D_L14_00161604;
extern short D_L14_00161608;
extern short D_L14_0016160C;
extern short D_L14_00161610;

// Steers a moby's two smoothed angles toward their targets, unless it is in a dormant state.
void func_L14_002B6678(char *moby) {
    int raw = ((unsigned char *)moby)[0x20];
    unsigned char state = raw;
    char *data = *(char **)(moby + 0x78);
    float t;
    if (state == 0 || state == 9 || state == 1) return;
    t = *(float *)&D_L14_00161608;
    if ((raw >= 2 && raw <= 3) || state == 7) {
        t = t * 1.5f;
    } else {
        func_L00_0025C918((float *)(data + 0x168), (float *)(data + 0x16C), *(float *)&D_L14_00161604, 0.002f, 0.2f, 0.0f);
        func_L00_00263B78(*(float *)&D_L14_00161600, *(float *)(data + 0x168), moby, (float *)(data + 0xC0), (float *)(data + 0xC4));
    }
    func_L00_0025C918((float *)(data + 0x160), (float *)(data + 0x164), t, 0.003f, 0.2f, 0.0f);
    func_L00_00263BF8(moby, data + 0xC8, data + 0xCC, *(float *)(data + 0x160), *(float *)&D_L14_0016160C, *(float *)&D_L14_00161610);
}
extern int *D_L14_001B0F30[];
extern char D_0013E633[];
extern int func_L00_00260FB0(float a, char *m, char *b, int c, int d, int *e, int f);

// Updates a moby's effect from its table entry and latches a default word.
void func_L14_002B6780(char *moby) {
    char *data = *(char **)(moby + 0x78);
    if (((unsigned char *)moby)[0x20] != 0 && ((unsigned char *)moby)[0x20] != 9) {
        int *p = D_L14_001B0F30[*(int *)(data + 0xD4)];
        func_L00_00260FB0(255.0f, moby, data + 0x70, 0, 0, p + 4, *p);
        if (*(int *)(data + 0xB0) == 0) {
            *(int *)(data + 0xB0) = *(int *)(D_0013E633 + 0x2E9D);
        }
    }
}
extern float func_001F9D10(void *, void *);

/* Recomputes the per-segment lengths of three paths held by the moby, then clears a counter. */
void func_L14_002B6800(char *moby) {
    char *data = *(char **)(moby + 0x78);
    char *p;
    int i;
    p = D_L14_001B0F30[*(int *)(data + 0xD0)];
    for (i = 0; i < *(int *)p - 1; i++) {
        *(float *)(p + 0x1C + i * 0x10) = FastVecDist(p + 0x10 + i * 0x10, p + 0x20 + i * 0x10);
    }
    p = D_L14_001B0F30[*(int *)(data + 0x150)];
    for (i = 0; i < *(int *)p - 1; i++) {
        *(float *)(p + 0x1C + i * 0x10) = FastVecDist(p + 0x10 + i * 0x10, p + 0x20 + i * 0x10);
    }
    p = D_L14_001B0F30[*(int *)(data + 0xDC)];
    for (i = 0; i < *(int *)p - 1; i++) {
        *(float *)(p + 0x1C + i * 0x10) = FastVecDist(p + 0x10 + i * 0x10, p + 0x20 + i * 0x10);
    }
    *(int *)(data + 0x10C) = 0;
}
extern float func_L00_001FF860(float, float);
extern void func_L00_002592B0(char *moby, float *vel, float target, float k, float d, float max);

/* steer a moby's position toward a target and update its velocity */
int func_L14_002B6980(char *moby, char *a1, int a2, int a3, float *v, float *vel,
                      float f12, float f13, float f14, float f15, float f16, float f17, float f18) {
    float tmp[3];
    int r = func_L00_0025E860(a1, tmp, a2, a3, 0);
    func_L00_0025C918((float *)(moby + 0x10), v, tmp[0], f13, f14, f15);
    func_L00_0025C918((float *)(moby + 0x14), v + 1, tmp[1], f13, f14, f15);
    func_L00_0025C918((float *)(moby + 0x18), v + 2, tmp[2], f13, f14, f15);
    func_L00_002592B0(moby, vel, func_L00_001FF860(v[0], v[1]), f16, f17, f18);
    return r != 0;
}
extern void func_L00_002592B0_2B6AA0(char *moby, float target, float *vel, float k, float d, float max) __asm__("func_L00_002592B0");

/* eases a moby's position and heading toward targets while in states 4-6 or 8 */
void func_L14_002B6AA0(char *moby, float *target, float a, float b, float c, float d, float e, float f, float g) {
    int data;
    int s = moby[0x20] & 0xFF;
    if ((s >= 4 && s <= 6) || s == 8) {
        data = *(int *)(moby + 0x78);
        func_L00_0025C918((float *)(moby + 0x10), (float *)(data + 0xF0), target[0], b, c, d);
        func_L00_0025C918((float *)(moby + 0x14), (float *)(data + 0xF4), target[1], b, c, d);
        func_L00_0025C918((float *)(moby + 0x18), (float *)(data + 0xF8), target[2], b, c, d);
        func_L00_002592B0_2B6AA0(moby, a, (float *)(data + 0xE4), e, f, g);
    }
}
INCLUDE_ASM("asm/overlays", func_L14_002B6BB8);
INCLUDE_ASM("asm/overlays", func_L14_002B6E80);
extern char D_0013E633[];
extern void func_L00_0028EBF0(int);

// Clears a moby's link to its slot entry, releasing the slot if it still points back here.
void func_L14_002B6EE8(char *moby)
{
    char *data = *(char **)(moby + 0x78);
    int idx;
    *(unsigned short *)(moby + 0x34) |= 0x41;
    *(int *)(moby + 0x94) = 0;
    idx = *(int *)(data + 0x108);
    if (idx != -1) {
        char *e = D_0013E633 + 0x1D + idx * 0x70;
        if (*(char **)(e + 0x88) == moby && *(unsigned char *)(e + 0x74) != 0) {
            func_L00_0028EBF0(idx);
        }
    }
    *(int *)(data + 0x108) = -1;
}
INCLUDE_ASM("asm/overlays", func_L14_002B6F68);
INCLUDE_ASM("asm/overlays", func_L14_002B7028);
INCLUDE_ASM("asm/overlays", func_L14_002BBEC8);
typedef int u128_2BC560 __attribute__((mode(TI)));
extern float D_0015EE60 MACRO_ADDR;
extern struct Moby *func_0020D348_m(int) __asm__("func_0020D348");
extern float func_002140F8(float, float);
extern void func_001F9CA0(void *, void *, void *);
extern float func_L00_00258C80(float lo, float hi);
extern void func_002156E0(void *dst, void *vec, void *axis, float angle);
extern void func_L00_00251E30(void *);

// Spawns moby 0x51 at a position facing away from an owner, with random drift and spin parameters.
unsigned char *func_L14_002BC560(char *owner, float angle, char *posp) {
    float vec[12];
    unsigned char *m;
    char *d;
    char *g;
    float *v0 = vec;
    float *v1;
    *(u128_2BC560 *)v0 = *(u128_2BC560 *)posp;
    m = (unsigned char *)func_0020D348_m(0x51);
    if (m != 0) {
        d = *(char **)(m + 0x78);
        qcopy(m + 0x10, v0);
        v1 = vec + 4;
        *(float *)(m + 0x48) = angle;
        m[0x20] = 0;
        m[0x30] = 0xFF;
        *(short *)(m + 0x32) = 0xFF;
        m[0x31] = 1;
        func_001F9BF0(v1, v0, owner + 0x10);
        vec[6] = 0.0f;
        func_L00_001FF4B0(v1, v1, func_002140F8(D_0015EE60 * 0.075f, D_0015EE60 * 0.2f));
        g = D_0013E633 + 0x10AD;
        func_001F9CA0(vec + 8, g, v1);
        func_002156E0(d, v1, g, func_L00_00258C80(0.0f, 0.7853982f));
        *(float *)(d + 8) = func_002140F8(D_0015EE60 * 0.05f, D_0015EE60 * 0.32f);
        *(float *)(d + 0x14) = func_L00_00258C80(0.0f, 0.034906585f);
        *(float *)(d + 0x18) = func_L00_00258C80(0.0f, 0.034906585f);
        *(float *)(d + 0x1C) = func_L00_00258C80(0.0f, 0.034906585f);
        *(short *)(d + 0x10) = func_001F9850(200);
        *(char **)(d + 0x20) = owner;
        *(short *)(d + 0x12) = -1;
        func_L00_00251E30(m);
    }
    return m;
}
extern void func_L00_0023F1D0(int);
extern void func_0020D678(void *);

void func_L14_002BC728(char *moby)
{
    char *data = *(char **)(moby + 0x78);
    int index = *(short *)(data + 0x12);
    if (index != -1) {
        func_L00_0023F1D0(index);
        *(short *)(data + 0x12) = -1;
    }
    DeleteMoby(moby);
}
INCLUDE_ASM("asm/overlays", func_L14_002D7250);
extern char *D_L14_0015F7EC_p __asm__("D_L14_0015F7EC") MACRO_ADDR;
extern short D_L14_00161B08;
extern int func_L00_0025EFC0(void *, void *, float *, int *, float *, int, float, float, float);

typedef struct {
    float v[4];
    int i;
    float t;
} PathPos_2D7668;

/* Finds the path segments nearest to the two target points and sums the segment lengths between them. */
void func_L14_002D7668(char *m) {
    char *d = *(char **)(m + 0x78);
    char *path = *(char **)(D_L14_0015F7EC_p + *(int *)(d + 0x60) * 32 + 0x10);
    char *tg;
    PathPos_2D7668 s;
    int k;
    float z;
    unsigned short n;
    *(float *)(d + 0x74) = *(float *)&D_L14_00161B08;
    *(int *)(d + 0x68) = 0;
    *(int *)(d + 0x64) = 0;
    z = *(float *)(d + 0x68);
    tg = (char *)D_L14_001B0F30[*(int *)(d + 0x88)] + 0x30;
    s.t = z;
    s.i = 0;
    func_L00_0025EFC0(path, tg, s.v, &s.i, &s.t, 0, 20.0f, 5.0f, z);
    *(short *)(d + 0x8C) = s.i;
    s.t = z;
    s.i = 0;
    func_L00_0025EFC0(path, (char *)D_L14_001B0F30[*(int *)(d + 0x88)] + 0x20, s.v, &s.i, &s.t, 0, 20.0f, 5.0f, z);
    n = s.i;
    *(short *)(d + 0x8E) = n;
    *(float *)(d + 0x78) = z;
    for (k = (short)n; k < *(short *)(d + 0x8C); k++) {
        *(float *)(d + 0x78) += *(float *)(path + k * 16 + 0x1C);
    }
}
/* Moves toward the table entry: looks up entry d[0x60] (32-byte records, pointer at +0x10), runs
 * func_001F9908 on the data block's +0x6C and returns whether that was non-zero; then calls
 * func_001F9C08 with the moby position, the entry, the D_L14_001B0F30 target and
 * func_001FA888(+0x6C) * +0x70 as the factor. The index-first sum keeps retail's addu order. */
extern char *D_L14_0015F7EC_p __asm__("D_L14_0015F7EC") MACRO_ADDR;
extern char *D_L14_001B0F30_a[] __asm__("D_L14_001B0F30");
extern int func_001F9908(void *);
extern void func_001F9C08(void *, void *, void *, float);

int func_L14_002D77E0(char *m) {
    char *d = *(char **)(m + 0x78);
    char *ent = *(char **)((char *)((*(int *)(d + 0x60) << 5) + (int)D_L14_0015F7EC_p) + 0x10);
    int ok;
    float t;
    ok = func_001F9908(d + 0x6C) != 0;
    t = func_001FA888(*(int *)(d + 0x6C));
    func_001F9C08(m + 0x10, ent + 0x10, D_L14_001B0F30_a[*(int *)(d + 0x84)] + 0x10, t * *(float *)(d + 0x70));
    return ok;
}
INCLUDE_ASM("asm/overlays", func_L14_002D7880);
INCLUDE_ASM("asm/overlays", func_L14_002D7AF8);
extern int D_L14_0015F7EC MACRO_ADDR;
extern short D_L14_00161B00;
extern float D_0015EE6C MACRO_ADDR;
extern void func_L00_0025E860(int a, char *pos, char *b, char *c, int d, float f);

// Calls func_L00_0025E860 with a table entry, the moby position and two data fields, scaled.
void func_L14_002D84A8(char *moby)
{
    char *data = *(char **)(moby + 0x78);
    int idx = *(int *)(data + 0x60);
    func_L00_0025E860(*(int *)((idx << 5) + D_L14_0015F7EC + 0x10), moby + 0x10, data + 0x64, data + 0x68, 0, *(float *)&D_L14_00161B00 * D_0015EE6C);
}
INCLUDE_ASM("asm/overlays", func_L14_002D8500);
extern char D_L14_00180AC0[];
extern short D_L14_00161B30;
extern float D_L14_0015F660[] MACRO_ADDR;
extern void func_L00_00250800(void *, int, void *);
extern int func_L00_0023F0D0(float *, float, float, float, float, float);
extern void func_002141A8(void *, float, float);
extern char *func_L00_002757E8(void *, void *, int, void *);
extern void func_L14_002D8500(void);

/* Puffs smoke from the moby's exhaust joint: keeps its light in place while active, then spawns four puffs. */
void func_L14_002D87A0(char *m) {
    char *d = *(char **)(m + 0x78);
    float p[4];
    float v[4];
    float w[4];
    char *q;
    int i;
    func_L00_00250800(m, 1, p);
    func_001F9BF0(v, p, D_L14_001675C0);
    func_L00_001FF4B0(v, v, -0.5f);
    func_001F9BD8(d + 0xE0, p, v);
    if ((unsigned int)(((unsigned char *)m)[0x20] - 3) < 3) {
        p[2] += 1.0f;
        if (*(int *)(d + 0xF0) == -1) {
            *(int *)(d + 0xF0) = func_L00_0023F0D0(p, *(float *)&D_L14_00161B30, 0.0f, 0.5f, 0.5f, 1.0f);
        }
        if (*(int *)(d + 0xF0) >= 0) {
            char *e = D_L14_00180AC0 + *(int *)(d + 0xF0) * 32;
            qcopy(e + 0x10, p);
            *(float *)(e + 0x1C) = *(float *)&D_L14_00161B30;
        }
        p[2] -= 1.0f;
    }
    func_002141A8(w, 0.005f, 0.03f);
    q = func_L00_002757E8(p, w, 0x7F, m);
    if (q != 0) {
        *(float *)(q + 0xC) = func_002140F8(6000.0f, 32000.0f);
    }
    for (i = 0; i < 3; i++) {
        char *e;
        int t;
        q = func_L00_002757E8(p, D_L14_0015F660, 0x7F, m);
        if (q == 0) continue;
        e = q + 0x20;
        if (i == 2 && func_002140B0(8) == 0) {
            *(float *)(q + 0xC) = 180000.0f;
        } else {
            *(float *)(q + 0xC) = func_002140F8(80000.0f, 120000.0f);
        }
        t = func_001F9850(2);
        *(short *)(q + 0xA) = t;
        *(float *)(e + 0x10) = 1.0f / func_001FA888((short)t);
        *(int *)(e + 0x18) = 0x7F7F7F;
        *(short *)(e + 0x16) = 3;
    }
    func_L00_00250800(m, 6, d + 0x200);
    func_001F49B0(func_L14_002D8500, m);
}
INCLUDE_ASM("asm/overlays", func_L14_002DF5F8);
INCLUDE_ASM("asm/overlays", func_L14_002DF6B8);
typedef int u128 __attribute__((mode(TI)));
extern void func_L14_002E0480(char *);
extern float func_001F9B88(float);
extern int func_L00_0028EB98(void *, int);
extern int func_L00_0028EF68(int i, int a1, int v, int k);
extern void func_L14_002E1058(char *);
extern float func_001F9F90(float);
extern float func_001F9FA8(float);
extern void func_L14_002E0538(char *);

/* Updates a gem-lock sentry: picks up a sound slot and fires when the player is near. */
void func_L14_002E0228(char *moby) {
    char *data = *(char **)(moby + 0x78);
    char *x;
    float v[4];
    float w[4];
    int idx;
    switch (((unsigned char *)moby)[0x20]) {
    case 0:
        if (*(int *)(data + 0x1F4) == -1 || *(int *)(data + 0x1F8) == -1 || *(int *)(data + 0x1FC) == -1 || *(int *)(data + 0x200) < 0) {
            func_0020D678(moby);
            return;
        }
        func_L14_002E0480(moby);
        moby[0x20] = 1;
        *(int *)(data + 0x204) = -1;
        break;
    case 1:
        x = D_0013E633 + 0xE1D;
        if (*(int *)(x + 0x208C) != 0xF
            || (*(int *)(x + 0x560) != *(int *)((*(int *)(data + 0x1F4) << 5) + D_L14_0015F7EC + 0x10)
                && *(int *)(x + 0x560) != *(int *)((*(int *)(data + 0x1F8) << 5) + D_L14_0015F7EC + 0x10)
                && *(int *)(x + 0x560) != *(int *)((*(int *)(data + 0x1FC) << 5) + D_L14_0015F7EC + 0x10))) {
            if (16.0f < func_001F9B88(*(float *)(x + 0x80) - *(float *)(moby + 0x10))) goto end;
            if (16.0f < func_001F9B88(*(float *)(x + 0x84) - *(float *)(moby + 0x14))) goto end;
        }
        if (func_L00_0028EB98(moby, *(int *)(data + 0x204)) == 0) {
            *(int *)(data + 0x204) = func_L00_0028EF68(6, 4, (int)moby, 0xD3);
        }
        func_L14_002E1058(moby);
        v[0] = func_001F9F90(*(float *)(moby + 0x48)) * 3.125f;
        v[1] = func_001F9FA8(*(float *)(moby + 0x48)) * 3.125f;
        v[2] = 0.0f;
        func_001F9BD8(v, moby + 0x10, v);
        qcopy(w, v);
        w[3] = 4.5f;
        if (func_L00_00200290((char *)w, 64.0f) >= 0) {
            func_L14_002E0538(moby);
        }
        return;
    }
end:
    idx = *(int *)(data + 0x204);
    if (idx >= 0) {
        if (idx != -1) {
            char *e = D_0013E633 + 0x1D + idx * 0x70;
            if (*(char **)(e + 0x88) == moby && *(unsigned char *)(e + 0x74) != 0) {
                func_L00_0028EBF0(idx);
            }
        }
        *(int *)(data + 0x204) = -1;
    }
}
/* Initialises two tables of spaced vectors in the moby's data block and clears four fields. */
void func_L14_002E0480(char *moby) {
    float *d = *(float **)(moby + 0x78);
    float *p = d;
    int i;
    for (i = 0; i < 10; i++) {
        p[0] = d[0x1F0 / 4] * (float)i;
        p[1] = p[2] = 0.0f;
        p[3] = 1.0f;
        p += 4;
    }
    i = 0;
    p = d;
    for (; i < 20; i++) {
        p[0xA0 / 4] = (float)i * 0.39f;
        p[0xA4 / 4] = p[0xA8 / 4] = 0.0f;
        p[0xAC / 4] = 1.0f;
        p += 4;
    }
    d[0x1E0 / 4] = 0.0f;
    d[0x1E4 / 4] = 0.0f;
    d[0x1E8 / 4] = 0.0f;
    d[0x1EC / 4] = 0.0f;
}
