#!/usr/bin/env python3
"""
splat/spimdisasm name every un-analyzed data symbol D_<VRAM_HEX> and every
function func_<VRAM_HEX> -- the hex suffix IS the address. Anything in a
bss region (declared as reserved space in the linker script, not an
object with real symbols) shows up as "undefined reference" at link time
even though we know exactly what address it must be. Rather than writing
a real symbol declaration for every one of those (hundreds, and growing
as more get named for real), generate .equ definitions straight from the
link error output; run this against build-sn/undefined_syms.txt after any
link attempt.

Only touches 8-hex-digit D_/func_ names (real addresses); anything else
(stray small-constant "symbols" spimdisasm sometimes emits, e.g. D_1000,
or local jump-table labels) is left for manual investigation -- printed
separately so they don't get silently equated to garbage.
"""
import re
import sys
from pathlib import Path

ADDR_RE = re.compile(r"^(D|func)_([0-9A-Fa-f]{1,8})$")


def main() -> None:
    undefined_path = Path(sys.argv[1] if len(sys.argv) > 1 else "build-sn/undefined_syms.txt")
    out_path = Path(sys.argv[2] if len(sys.argv) > 2 else "build-sn/bss_equs.s")

    names = [n.strip() for n in undefined_path.read_text().splitlines() if n.strip()]
    equs = []
    unresolved = []
    for name in names:
        m = ADDR_RE.match(name)
        if m:
            equs.append((name, int(m.group(2), 16)))
        else:
            unresolved.append(name)

    with out_path.open("w") as f:
        f.write("# Generated by tools/gen_bss_equs.py -- do not hand-edit.\n")
        for name, addr in equs:
            # .equ alone defaults to local binding -- .global is required
            # for this symbol to satisfy an undefined reference in a
            # *different* object at link time.
            f.write(f".global {name}\n.equ {name}, 0x{addr:08X}\n")

    print(f"Wrote {len(equs)} .equ definitions to {out_path}")
    if unresolved:
        print(f"{len(unresolved)} unresolved (not 8-hex-digit D_/func_) -- needs manual look:")
        for name in unresolved:
            print(f"  {name}")


if __name__ == "__main__":
    main()
