#!/usr/bin/env python3
"""
Pair the functions of a Sony library archive (libc.a, libm.a, ...) with retail
functions, by code with relocatable fields masked, and write
config/<name>.tsv: member, symbol, address, size.

The archive is only a reference for naming and address mapping (the library
symbol names are public); matching still requires compiling real source.
Usage: venv/bin/python tools/map_archive.py ARCHIVE.a NAME
"""
import os
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import retail as mp  # noqa: E402
from elftools.elf.elffile import ELFFile  # noqa: E402

ROOT = mp.ROOT


def main() -> int:
    archive, name = sys.argv[1], sys.argv[2]
    funcs = []
    for l in (ROOT / "config" / "functions.tsv").read_text().splitlines()[1:]:
        n, a, s, seg = l.split("\t")
        funcs.append((int(a, 16), int(s, 16), n))
    with open(ROOT / "baserom" / "SCUS_974.65.elf", "rb") as f:
        secs = mp.sections(ELFFile(f))
    by_size = {}
    for a, s, n in funcs:
        by_size.setdefault(s, []).append((a, n, mp.normalise(mp.read(secs, a, s))))
    rows, taken = [], set()
    with tempfile.TemporaryDirectory() as d:
        subprocess.run(["ar", "x", os.path.abspath(archive)], cwd=d, check=True)
        for obj in sorted(os.listdir(d)):
            try:
                elf = ELFFile(open(os.path.join(d, obj), "rb"))
                text = elf.get_section_by_name(".text")
                if text is None:
                    continue
                data = text.data()
                syms = [s for s in elf.get_section_by_name(".symtab").iter_symbols()
                        if s["st_info"]["type"] == "STT_FUNC" and s["st_size"]]
            except Exception:  # noqa: BLE001
                continue
            for s in syms:
                code = data[s["st_value"]: s["st_value"] + s["st_size"]]
                cn = mp.normalise(code)
                for size in (s["st_size"], (s["st_size"] + 7) & ~7):
                    hit = [(a, n) for a, n, c in by_size.get(size, []) if n not in taken and c[:len(cn)] == cn]
                    if hit:
                        a, n = hit[0]
                        taken.add(n)
                        rows.append((obj, s.name, a, size))
                        break
    rows.sort(key=lambda r: r[2])
    with open(ROOT / "config" / (name + ".tsv"), "w") as f:
        f.write("# member\tsymbol\taddress\tsize  (generated by tools/map_archive.py from %s)\n" % Path(archive).name)
        for o, sym, a, sz in rows:
            f.write("%s\t%s\t0x%08X\t0x%X\n" % (o, sym, a, sz))
    print("%s: %d functions mapped, %d bytes" % (name, len(rows), sum(r[3] for r in rows)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
