/* Level 10 (Orxon) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

extern int func_001E9730();
extern void func_0020D678(void *);
extern float func_001F9878(float);
extern int func_001F9908(int *);
extern int func_0022ED80(int, int, int);
extern int func_001F9850(int);
typedef int u128 __attribute__((mode(TI)));
extern char D_L10_001DC810[];
// Update for class 1033: oscillates its height between two limits with timed pauses.
void func_L10_00296BD8(char *m) {
    char *d = *(char **)(m + 0x78);
    if (d == 0) {
        func_001E9730(D_L10_001DC810, *(short *)(m + 0xA6), *(short *)(m + 0xB2));
        func_0020D678(m);
        return;
    }
    switch (*(unsigned char *)(m + 0x20)) {
    case 0:
        d[0x28] = 4;
        *(short *)(d + 0x3E) = 5;
        *(int *)(d + 0x20) = 0;
        *(short *)(d + 0x24) = 0;
        *(u128 *)(d + 0xA0) = *(u128 *)(m + 0x10);
        m[0x20] = 1;
        break;
    case 1: {
        float lim;
        *(float *)(m + 0x18) = *(float *)(m + 0x18) + 1.5f / func_001F9878(45.0f);
        lim = *(float *)(d + 0xA8) + 1.5f;
        if (lim <= *(float *)(m + 0x18)) {
            *(float *)(m + 0x18) = lim;
            m[0x20] = 2;
            *(int *)(d + 0xB0) = func_001F9850(0x78);
        }
        break;
    }
    case 2:
        if (func_001F9908((int *)(d + 0xB0))) {
            func_0022ED80(0, 0, (int)m);
            m[0x20] = 3;
        }
        break;
    case 3: {
        float lim;
        *(float *)(m + 0x18) = *(float *)(m + 0x18) - 1.5f / func_001F9878(45.0f);
        lim = *(float *)(d + 0xA8);
        if (*(float *)(m + 0x18) <= lim) {
            *(float *)(m + 0x18) = lim;
            m[0x20] = 4;
            *(int *)(d + 0xB0) = func_001F9850(0x78);
        }
        break;
    }
    case 4:
        if (func_001F9908((int *)(d + 0xB0))) {
            func_0022ED80(0, 0, (int)m);
            m[0x20] = 1;
        }
        break;
    }
}
typedef int Q_296dc0 __attribute__((mode(TI)));
extern float D_0015EE6C_x __asm__("D_0015EE6C") MACRO_ADDR;
extern float D_0015EE70 MACRO_ADDR;
extern int func_L01_00278FA8(void *);
extern float func_00214158(void);
extern float func_L00_00258C80(float lo, float hi);
extern void func_L00_00263B78(float, float, char *, float *, float *);
extern void func_L00_00263BF8(void *, char *, char *, float, float, float);
extern int func_L00_00258BC8(int, int);
extern void func_001F9BF0(void *, void *, void *);
extern void func_L00_002617B0(char *, void *, void *, void *);

/* Bobbing float: drifts with a gentle wobble; when stood on it sinks, then rises back to its rest height. */
void func_L10_00296DC0(char *m) {
    char *d = *(char **)(m + 0x78);
    float prev[4];
    float v[4];
    *(Q_296dc0 *)prev = *(Q_296dc0 *)(m + 0x10);
    if (func_L01_00278FA8(m)) m[0x20] = 2;
    func_001F9908((int *)(d + 0xBC));
    switch (((unsigned char *)m)[0x20]) {
    case 0:
        d[0x28] = 4;
        *(short *)(d + 0x3E) = 5;
        *(int *)(d + 0x20) = 0;
        *(short *)(d + 0x24) = 0;
        *(float *)(d + 0xA0) = *(float *)(m + 0x18);
        *(float *)(d + 0xA8) = func_00214158();
        *(float *)(d + 0xB4) = func_00214158();
        {
            float r = func_00214158();
            float e = D_0015EE6C_x * 0.13962634f;
            *(float *)(d + 0xB8) = r;
            *(float *)(d + 0xB0) = D_0015EE6C_x * 1.5707964f + func_L00_00258C80(0.0f, e);
        }
        m[0x20] = 1;
    case 1:
        *(int *)(d + 0xA4) = 0;
        func_L00_00263B78(0.1f, *(float *)(d + 0xB0), m, (float *)(d + 0xA8), (float *)(d + 0xAC));
        func_L00_00263BF8(m, d + 0xB4, d + 0xB8, 0.047123890f, D_0015EE6C_x * 0.34906584f, D_0015EE6C_x * 0.5235988f);
        break;
    case 2: {
        float a = *(float *)(d + 0xA4) - (D_0015EE70 + D_0015EE70);
        float lim = -(D_0015EE6C_x + D_0015EE6C_x);
        *(float *)(d + 0xA4) = a;
        if (a < lim) *(float *)(d + 0xA4) = lim;
        *(float *)(m + 0x18) += *(float *)(d + 0xA4);
        if (func_L01_00278FA8(m) == 0) m[0x20] = 3;
        if (*(int *)(d + 0xBC) <= 0) {
            func_0022ED80(0, 0, (int)m);
            *(int *)(d + 0xBC) = func_L00_00258BC8(0x28, 0x3C);
        }
        break;
    }
    case 3: {
        float vz = *(float *)(d + 0xA4);
        float g = D_0015EE70;
        float dist, sq, t;
        if (vz < 0.0f || (t = g + g, dist = *(float *)(d + 0xA0) - *(float *)(m + 0x18), sq = vz * vz,
                          sq / (t + t) < dist)) {
            float a = vz + g;
            float mx = D_0015EE6C_x + D_0015EE6C_x;
            *(float *)(d + 0xA4) = a;
            if (mx < a) *(float *)(d + 0xA4) = mx;
        } else if (0.0f < dist) {
            float a = vz - sq / (dist + dist);
            *(float *)(d + 0xA4) = a;
            if (a < 0.0f) *(float *)(d + 0xA4) = 0.0f;
        }
        *(float *)(m + 0x18) += *(float *)(d + 0xA4);
        if (*(float *)(d + 0xA0) <= *(float *)(m + 0x18)) {
            *(float *)(m + 0x18) = *(float *)(d + 0xA0);
            m[0x20] = 1;
        }
        break;
    }
    }
    func_001F9BF0(v, m + 0x10, prev);
    func_L00_002617B0(d + 0x60, v, m + 0x40, m + 0x40);
}
INCLUDE_ASM("asm/overlays", func_L10_00299818);
INCLUDE_ASM("asm/overlays", func_L10_00299D18);
INCLUDE_ASM("asm/overlays", func_L10_002BFBB8);
INCLUDE_ASM("asm/overlays", func_L10_002C0378);
INCLUDE_ASM("asm/overlays", func_L10_002C0388);
INCLUDE_ASM("asm/overlays", func_L10_002C03EC);
INCLUDE_ASM("asm/overlays", func_L10_002C04C4);
extern char D_0013E633[];
extern int func_001F9908(int *arg0);
extern void func_001FA218(float *, float *);
extern void func_001F9BC0(float *);
extern void func_001F9EE8(void *, void *, void *);
extern void func_001F9C30(void *, void *, float);
extern void *func_L00_00270BC8(char *a, char *b, unsigned char c, int d);
extern void func_001F9BD8(void *, void *, void *);
extern int func_L00_0028EB98(void *, int);
extern int func_L00_0028EF68(int i, int a1, int v, int k);
extern void func_L00_0028EBF0(int);
extern float D_0015EE6C MACRO_ADDR;

// Update for a swirling effect moby: spawns particles along an axis and manages a sound slot.
void func_L10_002C8DE0(unsigned char *moby) {
    char *data = *(char **)(moby + 0x78);
    float d[16];
    float v[4];
    float r[4];
    float s[4];
    switch (moby[0x20]) {
    case 0:
        *(int *)(data + 0x10) = -1;
        if (func_001F9908((int *)(data + 0xC))) {
            *(int *)(data + 0xC) = *(int *)(data + 4);
            moby[0x20] = 1;
        }
        break;
    case 1:
        qcopy(v, moby + 0x10);
        func_001FA218(d, (float *)(moby + 0x40));
        func_001F9BC0(r);
        r[2] = *(float *)data * 3.0f * D_0015EE6C;
        func_001F9EE8(r, r, d);
        func_001F9C30(s, r, 0.33f);
        func_L00_00270BC8((char *)v, (char *)r, 0x40, (int)moby);
        func_001F9BD8(v, v, s);
        func_L00_00270BC8((char *)v, (char *)r, 0x40, (int)moby);
        func_001F9BD8(v, v, s);
        func_L00_00270BC8((char *)v, (char *)r, 0x40, (int)moby);
        if (func_L00_0028EB98(moby, *(int *)(data + 0x10)) == 0) {
            *(int *)(data + 0x10) = func_L00_0028EF68(0, 4, (int)moby, 0x519);
        }
        if (func_001F9908((int *)(data + 0xC))) {
            int k;
            *(int *)(data + 0xC) = *(int *)(data + 8);
            moby[0x20] = 0;
            k = *(int *)(data + 0x10);
            if (k != -1) {
                unsigned char *e = (unsigned char *)D_0013E633 + 0x1D + k * 0x70;
                if (*(unsigned char **)(e + 0x88) == moby && e[0x74] != 0) {
                    func_L00_0028EBF0(k);
                }
            }
            *(int *)(data + 0x10) = -1;
        }
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L10_002CAD18);
INCLUDE_ASM("asm/overlays", func_L10_002CB030);
LINKER_REMNANT("asm/overlays", func_L10_002CF310);
INCLUDE_ASM("asm/overlays", func_L10_002D8ED8);
INCLUDE_ASM("asm/overlays", func_L10_002D8F08);
// stores a float into field 0x18
void func_L10_002D8F34(char *a, float f) {
    *(float *)(a + 0x18) = f;
}
INCLUDE_ASM("asm/overlays", func_L10_002D8F40);
extern char *func_0020D348(int);
extern float func_002140F8(float, float);
extern int func_001F9850(int);
extern void func_L00_00251E30(void *);
extern float D_0015EE6C MACRO_ADDR;
extern short D_L10_00161C6C;

struct Swirl { char pad[0x18]; float a; float b; };

// Spawns a moby with a swirl/particle data block.
char *func_L10_002D9418(int owner, char *pos, char *vec) {
    char *moby = CreateMoby(0x3AA);
    if (moby != 0) {
        char *data = *(char **)(moby + 0x78);
        ((unsigned char *)moby)[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0x7F;
        moby[0x31] = 1;
        moby[0x20] = 0;
        *(int *)(data + 0x10) = owner;
        *(short *)(data + 0x16) = 0;
        qcopy(moby + 0x10, pos);
        *(float *)(moby + 0x18) = *(float *)(moby + 0x18) + *(float *)&D_L10_00161C6C;
        qcopy(data, vec);
        ((struct Swirl *)data)->a = random_float_between(D_0015EE6C * 1.0471976f, D_0015EE6C * 3.1415927f);
        ((struct Swirl *)data)->b = random_float_between(D_0015EE6C * 1.0471976f, D_0015EE6C * 3.1415927f);
        *(short *)(data + 0x14) = scale_ticks(0x3C);
        func_L00_00251E30(moby);
    }
    return moby;
}
INCLUDE_ASM("asm/overlays", func_L10_002D9530);
INCLUDE_ASM("asm/overlays", func_L10_002D9988);
extern int func_L00_00258BC8(int, int);
extern int func_001F9908(int *arg0);
extern float func_001FA748(float, float);
extern void func_00215C00(void *, float, float, float);
extern void func_001F9BD8(void *, void *, void *);
extern int func_0022ED80(int, int, int);
extern short D_L10_00161C70;
extern short D_L10_00161C74;
extern short D_L10_00161C78;
extern short D_L10_00161C7C;
extern short D_L10_00161C80;
extern short D_L10_00161C84;
extern short D_L10_00161C88;

/* update: on a timer, fire a projectile from the moby's angle, then rearm the timer */
void func_L10_002D9FC0(char *moby) {
    char *data = *(char **)(moby + 0x78);
    float a[4];
    float b[4];
    if (((unsigned char *)moby)[0x20] == 0) {
        *(int *)data = scale_ticks(rand_range(*(int *)&D_L10_00161C70, *(int *)&D_L10_00161C74));
        moby[0x20] = 1;
    }
    if (func_001F9908((int *)data)) {
        float x = *(float *)&D_L10_00161C78;
        float p = random_float_between(-x, x) * 0.017453292f;
        float q = FastAddRots(*(float *)(moby + 0x48), p);
        float r = random_float_between(*(float *)&D_L10_00161C7C, *(float *)&D_L10_00161C80) * 0.017453292f;
        func_00215C00(a, random_float_between(*(float *)&D_L10_00161C84, *(float *)&D_L10_00161C88) * D_0015EE6C, q, r);
        FastVecAdd(b, moby + 0x10, a);
        func_L10_002D9418(moby, b, a);
        func_0022ED80(0, 0, (int)moby);
        *(int *)data = scale_ticks(rand_range(*(int *)&D_L10_00161C70, *(int *)&D_L10_00161C74));
    }
}
typedef int Q_2da0f0 __attribute__((mode(TI)));
extern int *D_L10_001B0C30[];
extern char D_L10_001DD420[];
extern char D_L10_001807C0[];
extern int D_L10_0015F6B0 MACRO_ADDR;
extern int func_001E9730_2da0f0(void *, int) __asm__("func_001E9730");
extern void func_L00_0023F1D0(int);
extern int func_001F9908_v(void *) __asm__("func_001F9908");
extern float func_001F9D10(void *, void *);
extern void func_L00_002633D8_f(float, float, void *, int *, float *, void *) __asm__("func_L00_002633D8");
extern int func_L00_0023F0D0(float *, float, float, float, float, float);
extern int func_002140B0(int);
extern void func_L10_002DE630(char *, float *, int *, float, float, float);
extern int func_L00_0028EF68_v(int, int, void *, int) __asm__("func_L00_0028EF68");

/* Electric spark: runs along its wire path with a light and a buzzing sound, then rests for a random time. */
void func_L10_002DA0F0(char *m) {
    char *d = *(char **)(m + 0x78);
    int *path;
    float pos[4];
    int seg;
    float frac;
    float len;
    if (*(int *)d == -1) {
        func_001E9730_2da0f0(D_L10_001DD420, *(short *)(m + 0xB2));
        func_0020D678(m);
        return;
    }
    path = D_L10_001B0C30[*(int *)d];
    ((unsigned char *)m)[0x30] = 0xFF;
    switch (((unsigned char *)m)[0x20]) {
    case 0:
        if (*(int *)(d + 0xC) != -1) {
            func_L00_0023F1D0(*(int *)(d + 0xC));
            *(int *)(d + 0xC) = -1;
        }
        if (*(int *)(d + 0x10) != -1) {
            char *e = D_0013E633 + 0x1D + *(int *)(d + 0x10) * 0x70;
            if (*(char **)(e + 0x88) == m && ((unsigned char *)e)[0x74] != 0) {
                func_L00_0028EBF0(*(int *)(d + 0x10));
            }
        }
        *(int *)(d + 0x10) = -1;
        if (func_001F9908_v(d + 8) != 0) {
            m[0x20] = 1;
            *(int *)(d + 4) = 0;
        }
        break;
    case 1:
        len = func_001F9D10((char *)path + 0x10, (char *)path + 0x20);
        *(float *)(d + 4) += D_0015EE6C * 5.0f;
        func_L00_002633D8_f(*(float *)(d + 4), len, path, &seg, &frac, pos);
        if (*(int *)(d + 0xC) == -1) {
            *(int *)(d + 0xC) = func_L00_0023F0D0(pos, 3.0f, 0.0f, 1.0f, 1.0f, 0.5f);
        } else {
            char *l = D_L10_001807C0 + *(int *)(d + 0xC) * 32;
            qcopy(l + 0x10, pos);
            *(float *)(l + 0) = 1.0f;
            *(float *)(l + 0x1C) = 3.0f;
            *(float *)(l + 4) = 1.0f;
            *(float *)(l + 8) = 0.5f;
            *(int *)(l + 0xC) = 0;
        }
        if (func_002140B0(2) != 0) return;
        if (D_L10_0015F6B0 & 1) {
            func_L10_002DE630(m, pos, path, *(float *)(d + 4), D_0015EE6C * 5.0f, len);
        }
        if (func_L00_0028EB98(m, *(int *)(d + 0x10)) == 0) {
            int r = func_L00_0028EF68_v(0, 0xC, m, 0x442);
            *(int *)(d + 0x10) = r;
            if (r != -1) {
                *(Q_2da0f0 *)(D_0013E633 + 0xAD + r * 0x70) = *(Q_2da0f0 *)pos;
            }
        } else {
            *(Q_2da0f0 *)(D_0013E633 + 0xAD + *(int *)(d + 0x10) * 0x70) = *(Q_2da0f0 *)pos;
        }
        if (seg == *path - 1) {
            m[0x20] = 0;
            *(int *)(d + 8) = func_001F9850(0x78);
        }
        break;
    }
}
typedef int u128_2DA3C0 __attribute__((mode(TI)));
extern void func_001FA4A0(void *, void *);
extern void func_001F9BF0(void *, void *, void *);
extern float func_001F9B88(float);
extern short D_L10_00161C90;
extern short D_L10_00161C8C;

/* Test whether a point lies within a box around a moby, in the moby's local frame. */
int func_L10_002DA3C0(char *m, float *p) {
    float a[4] __attribute__((aligned(16)));
    float t10[16] __attribute__((aligned(16)));
    float t50[4] __attribute__((aligned(16)));
    float t60[4] __attribute__((aligned(16)));
    *(u128_2DA3C0 *)a = *(u128_2DA3C0 *)p;
    func_001FA4A0(t10, m + 0xC0);
    func_001F9BF0(t60, a, m + 0x10);
    *(u128_2DA3C0 *)t50 = *(u128_2DA3C0 *)t60;
    func_001F9EE8(t50, t50, t10);
    if (func_001F9B88(t50[0]) < *(float *)&D_L10_00161C90) {
        return func_001F9B88(t50[1]) < *(float *)&D_L10_00161C8C;
    }
    return 0;
}
extern char D_L10_001DD460[];
extern u128 D_L10_001672C0;
extern u128 D_0013F4D0;
extern char D_0013D490[];
extern int func_L00_0025A208(int *, int, int, int);
extern int func_L00_0025A2F0(int *, int, int, int);

/* update for a moby that glides between two heights and sets a flag */
void func_L10_002DA468(unsigned char *m) {
    int *d = *(int **)(m + 0x78);
    u128 v[2];
    int it;
    int flag;
    int hit;
    if (d == 0) {
        func_001E9730(D_L10_001DD460, *(short *)(m + 0xA6), *(short *)(m + 0xB2));
        func_0020D678(m);
        return;
    }
    switch (m[0x20]) {
    case 0:
        *(u128 *)d = *(u128 *)(m + 0x10);
        m[0x20] = 2;
        break;
    case 1:
        flag = 0;
        {
            float f = *(float *)(m + 0x18) - 4.0f / func_001F9878(20.0f);
            *(float *)(m + 0x18) = f;
            if (f <= *(float *)(d + 2)) {
                *(float *)(m + 0x18) = *(float *)(d + 2);
                m[0x20] = 2;
            }
        }
        if (d[4] != -1) {
            if (func_L00_0025A208(&it, d[4], 0, 0)) {
                do {
                    v[0] = *(u128 *)(it + 0x10);
                    if (func_L10_002DA3C0(m, &v[0])) {
                        flag = 1;
                        break;
                    }
                } while (func_L00_0025A2F0(&it, it, 0, 0));
            }
        }
        hit = 0;
        if (flag == 0) {
            v[0] = D_L10_001672C0;
            if (func_L10_002DA3C0(m, &v[0]) == 0) {
                v[1] = D_0013F4D0;
                if (func_L10_002DA3C0(m, &v[1]) == 0) goto done;
            }
        }
        hit = 1;
    done:
        if (hit) m[0x20] = 3;
        break;
    case 2:
        break;
    case 3: {
        float f = 4.0f / func_001F9878(20.0f);
        float g = *(float *)(m + 0x18) + f;
        float h;
        *(float *)(m + 0x18) = g;
        h = *(float *)(d + 2) + 4.0f;
        if (h <= g) {
            *(float *)(m + 0x18) = h;
            m[0x20] = 4;
            if (d[5] != -1) D_0013D490[d[5] + 0x4C] = 1;
        }
        break;
    }
    case 4:
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L10_002DA678);
INCLUDE_ASM("asm/overlays", func_L10_002DB278);
INCLUDE_ASM("asm/overlays", func_L10_002DB688);
INCLUDE_ASM("asm/overlays", func_L10_002DBA50);
INCLUDE_ASM("asm/overlays", func_L10_002DE018);
INCLUDE_ASM("asm/overlays", func_L10_002DE630);
typedef int Effect128 __attribute__((mode(TI)));
extern void func_L00_002633D8(int,float *,float *,void *,float,float);
extern s32 func_001FA898(f32);
extern f32 func_001FA888(s32);
extern int func_L00_001F2BE8(float,void *,int,void *,void *);
extern void func_L00_0025BA50(void *,void *,void *,int,int,int,int,int,float,float,float);
extern float D_0015EE60 MACRO_ADDR;
extern char D_L10_00178400[];
typedef struct { int owner; float phase,speed,size; int source,timer; float growth; } EffectData;
/* Advances an effect, scales its size over its lifetime and emits hits. */
void func_L10_002DE798(char *m) {
 float old[4],pos[4],a,b;
 char *d=*(char **)(m+0x78);
 *(Effect128 *)old=*(Effect128 *)(m+0x10);
 ((EffectData *)d)->phase+=((EffectData *)d)->speed;
 ((EffectData *)d)->speed*=(((EffectData *)d)->growth-1.0f)*D_0015EE60+1.0f;
 func_L00_002633D8(((EffectData *)d)->owner,&a,&b,m+0x10,((EffectData *)d)->phase,((EffectData *)d)->size);
 *(float *)(m+0x40)=func_00214158();
 *(float *)(m+0x44)=func_00214158();
 *(float *)(m+0x48)=func_00214158();
 if(func_001F9908((int *)(d+0x14))) {func_0020D678(m);return;}
 if(*(int *)(d+0x14)<func_001FA898(10.0f/(D_0015EE6C*5.0f))/2) {
  float numerator=func_001FA888(*(int *)(d+0x14));
  *(float *)(m+0x2C)=*(float *)(*(char **)(m+0x24)+0x24)*numerator/func_001FA888(func_001FA898(10.0f/(D_0015EE6C*5.0f))/2)*0.5f;
 } else if((func_001FA898(10.0f/(D_0015EE6C*5.0f))/4)*3<*(int *)(d+0x14)) {
  float numerator=func_001FA888(func_001FA898(10.0f/(D_0015EE6C*5.0f))-*(int *)(d+0x14));
  *(float *)(m+0x2C)=*(float *)(*(char **)(m+0x24)+0x24)*numerator/func_001FA888(func_001FA898(10.0f/(D_0015EE6C*5.0f))/4)*0.5f;
 }
 if(*(float *)(*(char **)(m+0x24)+0x24)*0.25f<*(float *)(m+0x2C)) {
  int count=func_L00_001F2BE8(0.15f,m+0x10,16,*(void **)(d+0x10),0);
  *(Effect128 *)pos=*(Effect128 *)(m+0x10);
  func_L00_0025BA50(*(void **)(d+0x10),pos,D_L10_00178400,count,0,0x810001,2,1,2.0f,1.0f,1.0f);
 }
}
extern void func_001F9BF0(void *dst, void *a, void *b);
extern unsigned char D_0014171B[] NOT_SDA;
extern int D_0015EE84_m __asm__("D_0015EE84") MACRO_ADDR;
typedef struct { char pad0[0x454]; unsigned char collected[1]; } L10State;
extern L10State D_L10_001BB9C0;
extern int D_L10_001BAC60[];
extern char D_L10_00178600[];

/* Collectible trigger: deletes itself once taken, else watches for its toucher. */
void func_L10_002DEA10(char *m) {
    int i;
    char *e;
    float w[16];
    float v[4];
    unsigned short id = *(unsigned short *)(m + 0xB2);
    if (D_L10_001BB9C0.collected[(short)id] != 0
        || (*(int *)(D_0014171B + 0xAB75 + (((short)id >> 5) * 4 + (D_0015EE84_m << 8))) >> (id & 0x1F)) & 1) {
        func_0020D678(m);
        return;
    }
    *(short *)(m + 0x32) = 0x80;
    e = D_L10_00178600;
    for (i = 0; i < 0x40; i++, e += 0x40) {
        if (*(char **)(e + 0x34) == m) {
            if (*(int *)(e + 0x24) & 0x20000) {
                char *o = *(char **)(e + 0x20);
                if (*(short *)(o + 0xA6) == 0xAC || *(short *)(o + 0xA6) == 0x99) {
                    func_001F9BF0(v, m + 0x10, o + 0x10);
                    func_001FA4A0(w, m + 0xC0);
                    func_001F9EE8(v, v, w);
                    if (v[0] > 0.25f) {
                        *(int *)(D_0014171B + 0xAB75 + (((short)*(unsigned short *)(m + 0xB2) >> 5) * 4 + (D_0015EE84_m << 8))) |= 1 << (*(unsigned short *)(m + 0xB2) & 0x1F);
                        D_L10_001BAC60[(short)*(unsigned short *)(m + 0xB2) >> 5] |= 1 << (*(unsigned short *)(m + 0xB2) & 0x1F);
                        func_0020D678(m);
                        return;
                    }
                    *(int *)(e + 0x34) = 0;
                } else {
                    *(int *)(e + 0x34) = 0;
                }
            }
        }
    }
}
extern char *func_0020D348(int);
extern void func_L00_00251E30(void *);

char *func_L10_002DEC08(char *owner) {
    char *moby = CreateMoby(0x462);
    if (moby != 0) {
        ((unsigned char *)moby)[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        moby[0x31] = 1;
        *(int *)(moby + 0x40) = 0;
        *(int *)(moby + 0x44) = 0;
        *(float *)(moby + 0x48) = *(float *)(owner + 0x48);
        *(long *)(moby + 0x38) = *(long *)(owner + 0x38);
        qcopy(moby + 0x10, owner + 0x10);
        *(float *)(moby + 0x18) = 59.0f;
        func_L00_00251E30(moby);
    }
    return moby;
}
INCLUDE_ASM("asm/overlays", func_L10_002E0630);
INCLUDE_ASM("asm/overlays", func_L10_002E0FF8);
extern short *D_L10_001ABFC0[];
typedef struct { char p0[0x10]; float x; float y; char p1[8]; unsigned char state; char p2[0xDF]; } Ent;
extern Ent *D_L10_00160058 MACRO_ADDR;

/* Sets every listed entity in state 1 to state 2. */
void func_L10_002E14F8(unsigned char *m) {
    short *p;
    if (m[0x21] != 0xFF) {
        p = D_L10_001ABFC0[m[0x21]];
        if (p != 0) {
            do {
                Ent *base = D_L10_00160058;
                Ent *e = (Ent *)((*(unsigned short *)p & 0x7FFF) * 256 + (int)base);
                if (e->state == 1) e->state = 2;
            } while (*p++ >= 0);
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L10_002E1568);
INCLUDE_ASM("asm/overlays", func_L10_002E2B80);
typedef struct { char p0[0x10]; float x; float y; char p1[8]; unsigned char state; char p2[0xDF]; } Ent_2E3070;
extern Ent_2E3070 *D_L10_00160058_2E3070 __asm__("D_L10_00160058") MACRO_ADDR;
extern short D_L10_00161E80;

/* Stores a value into each table entry listed for this moby's index. */
void func_L10_002E3070(unsigned char *moby) {
    short *p;
    if (moby[0x21] != 0xFF) {
        p = D_L10_001ABFC0[moby[0x21]];
        if (p != 0) {
            do {
                int idx = *(unsigned short *)p & 0x7FFF;
                ((char *)D_L10_00160058_2E3070)[(idx << 8) + 0xBC] = func_001F9850(*(int *)&D_L10_00161E80);
            } while (*p++ >= 0);
        }
    }
}
