/* Level 08 (Batalia) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"
#include "moby.h"

extern float func_002140F8(float, float);
extern void func_L00_0025E210(void *);
extern int func_L08_0027ACC8(char *);
extern short D_L08_001614F8;
extern short D_L08_001614FC;

// Initialize the moby's rotation and data block, then fetch its handle.
void func_L08_002B9438(char *moby) {
    float a = *(float *)&D_L08_001614F8;
    float b = *(float *)&D_L08_001614FC;
    char *d;
    *(float *)(moby + 0x40) = 0.0f;
    *(float *)(moby + 0x44) = 0.5235988f;
    *(float *)(moby + 0x48) = 0.0f;
    d = *(char **)(moby + 0x78);
    *(float *)(d + 0xC) = random_float_between(a, b);
    *(int *)(d + 0x28) = 0;
    *(float *)(d + 8) = *(float *)(moby + 0x18);
    func_L00_0025E210(moby);
    *(int *)(d + 0x24) = func_L08_0027ACC8(moby);
}
typedef struct Target_2B94B0 {
    char pad0[0xA];
    short fA;
} Target_2B94B0;

typedef struct MobyData_2B94B0 {
    char pad0[8];
    float f8;
    float fC;
    float vel[4];
    int f20;
    Target_2B94B0 *target;
    int ticks;
    int f2C;
} MobyData_2B94B0;

typedef struct Moby_2B94B0 {
    char pad0[0x10];
    float pos[4];
    unsigned char state;
    char pad21[0x27];
    float f48;
    char pad4C[0x2C];
    MobyData_2B94B0 *data;
} Moby_2B94B0;

typedef struct Hero_2B94B0 {
    char pad0[0x80];
    float pos[4];
    char pad90[0x480];
    float v510[4];
    float v520[4];
    float v530[4];
    char pad540[0x1B4C];
    int f208C;
    char pad2090[0x1F8];
    float f2288;
    float f228C;
} Hero_2B94B0;

typedef struct Goal_2B94B0 {
    int active;
    int pad4;
    float pos[4];
} Goal_2B94B0;

extern float func_001F9CB8_2B94B0(void *a) __asm__("func_001F9CB8");
extern void func_L00_001FF4B0_2B94B0(void *, void *, float) __asm__("func_L00_001FF4B0");
extern void func_001F9BD8_2B94B0(void *, void *, void *) __asm__("func_001F9BD8");
extern void func_001F9BF0_2B94B0(void *, void *, void *) __asm__("func_001F9BF0");
extern int func_L00_001F39B0_2B94B0(void *, void *, int, int, int) __asm__("func_L00_001F39B0");
extern void func_L00_001FF610_2B94B0(void *, void *, void *) __asm__("func_L00_001FF610");
extern void func_001F9BC0_2B94B0(void *) __asm__("func_001F9BC0");
extern float func_001FA748_2B94B0(float, float) __asm__("func_001FA748");
extern float func_001F9D48_2B94B0(void *, void *) __asm__("func_001F9D48");
extern float func_001F9B88_2B94B0(float) __asm__("func_001F9B88");
extern int func_001FFB38_2B94B0(int, int, void *, void *, void *, void *, int) __asm__("func_001FFB38");
extern void func_0020D678_2B94B0(void *) __asm__("func_0020D678");
extern float func_001F9FA8_2B94B0(float) __asm__("func_001F9FA8");
extern void func_L08_002B9438_2B94B0(void *moby) __asm__("func_L08_002B9438");
extern int func_0022ED80_2B94B0(int, int, void *) __asm__("func_0022ED80");
extern void func_L00_0023A658_2B94B0(void) __asm__("func_L00_0023A658");
extern void func_L00_0023A690_2B94B0(void) __asm__("func_L00_0023A690");
extern void func_L00_0023A788_2B94B0(void) __asm__("func_L00_0023A788");
extern char *D_L08_00160058_2B94B0 __asm__("D_L08_00160058") MACRO_ADDR;
extern int D_L08_0015F6B0_2B94B0 __asm__("D_L08_0015F6B0") MACRO_ADDR;
extern int D_0015EE84_2B94B0 __asm__("D_0015EE84") MACRO_ADDR;
extern float D_0015EE70_2B94B0 __asm__("D_0015EE70") MACRO_ADDR;
extern float D_0015EE60_2B94B0 __asm__("D_0015EE60") MACRO_ADDR;
extern int D_0015EE98_2B94B0 __asm__("D_0015EE98") MACRO_ADDR;
extern char D_L08_001746D8_2B94B0[] __asm__("D_L08_001746D8");
extern int D_L08_001746D8_2B94B0i __asm__("D_L08_001746D8");
extern char D_L08_00174700_2B94B0[] __asm__("D_L08_00174700");
extern float D_L08_001614DC_2B94B0 SDATA(D_L08_001614DC);
extern float D_L08_001614E8_2B94B0 SDATA(D_L08_001614E8);
extern float D_L08_001614EC_2B94B0 SDATA(D_L08_001614EC);
extern int D_L08_001614F0_2B94B0 SDATA(D_L08_001614F0);
extern float D_L08_001614F4_2B94B0 SDATA(D_L08_001614F4);
extern char D_0013F450_2B94B0[] __asm__("D_0013F450");
extern char D_0013DE6E_2B94B0[] __asm__("D_0013DE6E");

/* Level 8 moby update (class 152): state machine that steers the moby toward the hero and fires its event. */
void func_L08_002B94B0(Moby_2B94B0 *m)
{
    MobyData_2B94B0 *d = m->data;
    float A[4], F[4], B[4], C[4], P[4], E[4];
    float f20, t, f;
    int hit, ok, n;

    d->ticks++;
    if (m->state != 0) m->pos[2] = d->f8;
    switch (m->state) {
    case 0:
        func_L08_002B9438_2B94B0(m);
        if (d->f2C != 0) m->state = 1;
        else m->state = 2;
        break;
    case 1:
        qcopy(P, m->pos);
        d->vel[2] = d->vel[2] - D_0015EE70_2B94B0 * 9.8f;
        f20 = func_001F9CB8_2B94B0(d->vel);
        if (D_L08_001614DC_2B94B0 * 1.8f * D_0015EE60_2B94B0 < f20) {
            func_L00_001FF4B0_2B94B0(d->vel, d->vel, D_L08_001614DC_2B94B0 * 1.8f * D_0015EE60_2B94B0);
            f20 = D_L08_001614DC_2B94B0 * 1.8f * D_0015EE60_2B94B0;
        }
        func_001F9BD8_2B94B0(A, P, d->vel);
        func_L00_001FF4B0_2B94B0(B, d->vel, D_L08_001614DC_2B94B0);
        func_001F9BF0_2B94B0(B, P, B);
        func_L00_001FF4B0_2B94B0(C, d->vel, f20 + D_L08_001614DC_2B94B0);
        func_001F9BD8_2B94B0(C, C, P);
        if (D_L08_0015F6B0_2B94B0 % 2 == (((char *)m - D_L08_00160058_2B94B0) >> 8) % 2
            && func_L00_001F39B0_2B94B0(B, C, 2, 0, 0) != 0) {
            ok = 1;
            if (D_L08_001746D8_2B94B0i == 0 || d->ticks >= 10) {
                if (f20 < D_L08_001614E8_2B94B0) {
                    ok = 0;
                } else {
                    func_001F9BF0_2B94B0(E, P, (D_L08_001746D8_2B94B0 + 8));
                    func_L00_001FF4B0_2B94B0(E, E, D_L08_001614DC_2B94B0);
                    func_001F9BD8_2B94B0(P, (D_L08_001746D8_2B94B0 + 8), E);
                }
                if (ok != 0) {
                    func_L00_001FF610_2B94B0(F, d->vel, D_L08_00174700_2B94B0);
                    f = func_001F9CB8_2B94B0(F) - D_L08_001614EC_2B94B0;
                    func_L00_001FF4B0_2B94B0(d->vel, F, f < 0.0f ? 0.0f : f);
                } else {
                    func_001F9BC0_2B94B0(d->vel);
                    qcopy(P, (D_L08_001746D8_2B94B0 + 8));
                    P[2] = P[2] + D_L08_001614DC_2B94B0;
                    if (*(int *)D_L08_001746D8_2B94B0 == 0) {
                        func_001F9BC0_2B94B0(d->vel);
                        m->state = 2;
                    }
                }
            } else {
                qcopy(P, A);
            }
        } else {
            qcopy(P, A);
        }
        qcopy(m->pos, P);
    case 2:
        hit = 0;
        m->f48 = func_001FA748_2B94B0(m->f48, d->fC);
        if (((Hero_2B94B0 *)D_0013F450_2B94B0)->f208C == 15) {
            if (func_001F9D48_2B94B0(((Hero_2B94B0 *)D_0013F450_2B94B0)->v510, m->pos) < 0.5f) hit = 1;
            if (func_001F9D48_2B94B0(((Hero_2B94B0 *)D_0013F450_2B94B0)->v520, m->pos) < 0.5f) hit = 1;
            if (func_001F9D48_2B94B0(((Hero_2B94B0 *)D_0013F450_2B94B0)->v530, m->pos) < 0.5f) hit = 1;
        } else if (func_001F9D48_2B94B0(m->pos, ((Hero_2B94B0 *)D_0013F450_2B94B0)->pos) < ((Hero_2B94B0 *)D_0013F450_2B94B0)->f2288) {
            if (func_001F9B88_2B94B0(m->pos[2] - ((Hero_2B94B0 *)D_0013F450_2B94B0)->pos[2]) < ((Hero_2B94B0 *)D_0013F450_2B94B0)->f228C) hit = 1;
        }
        if (hit == 0) break;
        if (d->target != 0) d->target->fA = 0;
        D_0015EE98_2B94B0 = D_0015EE98_2B94B0 + d->f20;
        ((int *)(D_0013DE6E_2B94B0 + 0x1D2))[D_0015EE84_2B94B0] = ((int *)(D_0013DE6E_2B94B0 + 0x1D2))[D_0015EE84_2B94B0] + d->f20;
        func_0022ED80_2B94B0(0, 0, m);
        func_001FFB38_2B94B0(2, 0x754E, func_L00_0023A658_2B94B0, func_L00_0023A690_2B94B0,
                             func_L00_0023A788_2B94B0, &D_0015EE98_2B94B0, 0x98967F);
        func_0020D678_2B94B0(m);
        return;
    case 3:
        break;
    case 4:
        if (d->target != 0) d->target->fA = 0;
        func_0020D678_2B94B0(m);
        return;
    }
    n = D_L08_001614F0_2B94B0;
    t = (float)(d->ticks % n) / (float)(n - 1) * 6.2831855f - 3.1415927f;
    f = func_001F9FA8_2B94B0(t);
    d->f8 = m->pos[2];
    m->pos[2] = m->pos[2] + D_L08_001614F4_2B94B0 * f;
}
extern char *func_0020D348(int);
extern int func_001F9850(int);
extern float func_002140F8(float, float);
extern float func_L00_001FF860(float, float);
extern void func_L00_00251E30(void *);
/* Spawns a moby of class 0xF8 at a position and facing derived from a vector. */
char *func_L08_002D35E8(int arg, char *pos, char *vec) {
    char *m = CreateMoby(0xF8);
    if (m != 0) {
        char *d = *(char **)(m + 0x78);
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0xFF;
        m[0x31] = 1;
        m[0x20] = 1;
        *(int *)(d + 0x30) = arg;
        *(int *)(d + 0x20) = scale_ticks(300);
        *(float *)(d + 0x2C) = 1.0f;
        *(int *)(d + 0x24) = 0;
        qcopy(m + 0x10, pos);
        qcopy(d + 0x10, vec);
        *(float *)(m + 0x40) = random_float_between(-180.0f, 180.0f) * 0.017453292f;
        *(float *)(m + 0x48) = func_L00_001FF860(*(float *)vec, *(float *)(vec + 4)) + 1.5707964f;
        func_L00_00251E30(m);
    }
    return m;
}
INCLUDE_ASM("asm/overlays", func_L08_002D36F8);
INCLUDE_ASM("asm/overlays", func_L08_002D55E0);
typedef struct Moby_2D5FA8 Moby_2D5FA8;
typedef struct {
    char pad0[0x20];
    float health;
    char pad24[2];
    short timer;
    char pad28[0x16];
    unsigned short flags;
    float f40[4];
    char pad50[0x50];
    short anim0;
    short anim2;
    char padA4[3];
    unsigned char tint;
    char padA8[8];
    float target[4];
    char padC0[0x30];
    int fF0;
    int mode;
    char padF8[0x18];
    float f110[4];
    float f120[4];
    char pad130[0x24];
    int path;
    char pad158[8];
    Moby_2D5FA8 *partA;
    Moby_2D5FA8 *partB;
    char pad168[8];
    float yaw;
    float yaw_speed;
    float pitch;
    float pitch_speed;
    char pad180[4];
    int part_id;
} Data_2D5FA8;
struct Moby_2D5FA8 {
    char pad0[0x10];
    float pos[4];
    unsigned char state;
    char pad21[0x1F];
    float rot[4];
    char pad50[3];
    unsigned char f53;
    char pad54[0x24];
    Data_2D5FA8 *data;
    char pad7C[0x28];
    unsigned char alpha;
    char padA5[1];
    short oclass;
};
typedef struct { char pad0[0x20]; Moby_2D5FA8 *moby; } Hit_2D5FA8;
typedef struct { int count; char pad4[0xC]; char list[1]; } Path_2D5FA8;

extern int D_0015EE84_2D5FA8 __asm__("D_0015EE84") MACRO_ADDR;
extern float D_0015EE70_2D5FA8 __asm__("D_0015EE70") MACRO_ADDR;
extern float D_0015EE6C_2D5FA8 __asm__("D_0015EE6C") MACRO_ADDR;
extern int D_L08_0015F694_2D5FA8 __asm__("D_L08_0015F694") MACRO_ADDR;
extern int D_L08_0015F698_2D5FA8 __asm__("D_L08_0015F698") MACRO_ADDR;
extern int D_L08_0015F69C_2D5FA8 __asm__("D_L08_0015F69C") MACRO_ADDR;
extern int D_L08_0015F6A0_2D5FA8 __asm__("D_L08_0015F6A0") MACRO_ADDR;
extern float D_L08_0015F660_2D5FA8[] __asm__("D_L08_0015F660") MACRO_ADDR;
extern Path_2D5FA8 *D_L08_001B0FB0_2D5FA8[] __asm__("D_L08_001B0FB0");
extern char D_0013E633_2D5FA8[] __asm__("D_0013E633") NOT_SDA;
extern unsigned char D_0013D50F_2D5FA8[] __asm__("D_0013D50F") NOT_SDA;
extern Hit_2D5FA8 *find_2D5FA8(Moby_2D5FA8 *, int, int) __asm__("func_L00_0025B478");
extern Hit_2D5FA8 *pick_2D5FA8(Hit_2D5FA8 *, Hit_2D5FA8 *, Hit_2D5FA8 *, int) __asm__("func_L05_0028AA68");
extern int damage_2D5FA8(Moby_2D5FA8 *, Hit_2D5FA8 *, float *, int, int *, float *, int, int) __asm__("func_L00_0025B4D0");
extern int ticks_2D5FA8(int) __asm__("func_001F9850");
extern void animate_2D5FA8(Moby_2D5FA8 *, int, int, int) __asm__("func_00213DE0");
extern void zero_2D5FA8(void *) __asm__("func_001F9BC0");
extern void burst_2D5FA8(Moby_2D5FA8 *, float *, float *, float, float, int, int, int, float, float, float, float, int, float, int, int, int, int) __asm__("func_L00_0025F4A8");
extern void *spawn_2D5FA8(Moby_2D5FA8 *, int, float *, float *, int, int, float, float *, float *, float *) __asm__("func_L00_00265050");
extern int sound_2D5FA8(int, int, int) __asm__("func_0022EE28");
extern void voice_2D5FA8(int, int) __asm__("func_L00_00264DB8");
extern void explode_2D5FA8(Moby_2D5FA8 *, int, int) __asm__("func_L00_002584A8");
extern void delete_2D5FA8(Moby_2D5FA8 *) __asm__("func_0020D678");
extern int event_2D5FA8(int, int, Moby_2D5FA8 *) __asm__("func_0022ED80");
extern void effects_start_2D5FA8(Moby_2D5FA8 *, short *) __asm__("func_L00_0025E4B0");
extern int follow_2D5FA8(float, Moby_2D5FA8 *, float *, int, int, char *, int) __asm__("func_L00_00260FB0");
extern void subtract_2D5FA8(float *, float *, float *) __asm__("func_001F9BF0");
extern float angle_2D5FA8(float, float) __asm__("func_L00_001FF860");
extern float length_2D5FA8(float *) __asm__("func_001F9CE8");
extern float angle_delta_2D5FA8(float, float) __asm__("func_001FA790");
extern float approach_2D5FA8(float *, float, float *, float, float, float) __asm__("func_L00_0025CE58");
extern void rotation_2D5FA8(float *, int, float) __asm__("func_L00_001FFED8");
extern void matmul_2D5FA8(float *, float *, float *) __asm__("func_001FA588");
extern void effects_update_2D5FA8(Moby_2D5FA8 *, short *) __asm__("func_L00_0025E590");

/* Per-frame update of a batalia turret moby: damage, its death state and its two helper parts. */
void func_L08_002D5FA8(Moby_2D5FA8 *m) {
    Data_2D5FA8 *d = m->data;
    Hit_2D5FA8 *t;
    Hit_2D5FA8 *u;
    Hit_2D5FA8 *c;
    float vec[4];
    int hit;
    float damage = 0.0f;
    int one;

    t = find_2D5FA8(m, 0x330000, 0);
    if (d->partA != 0) {
        u = find_2D5FA8(d->partA, 0x210000, 0);
    } else {
        u = 0;
    }
    if (d->partB != 0) {
        c = find_2D5FA8(d->partB, 0x210000, 0);
    } else {
        c = 0;
    }
    t = pick_2D5FA8(t, u, c, 0);
    if (t != 0 && t->moby != 0) {
        short h = t->moby->oclass;
        if (h == 0x1A9 || h == 0x47) t = 0;
    }
    damage_2D5FA8(m, t, &d->health, 0, &hit, &damage, 0, 4);
    one = 1;
    if (hit != one && m->state != 0) {
        d->health -= damage;
        if (damage != 0.0f) event_2D5FA8(4, 0, m);
        if (d->health > 0.0f) {
            if (damage < 4.0f) {
                d->tint = 0x78;
                if ((unsigned short)(t->moby->oclass - 0xB0) < 2) {
                    d->timer = ticks_2D5FA8(0x3C);
                } else {
                    d->timer = ticks_2D5FA8(0x1E);
                }
            } else if (damage < 6.0f) {
                d->tint = 0xC8;
                d->timer = ticks_2D5FA8(0x1E);
            } else {
                d->tint = 0xE6;
                d->timer = ticks_2D5FA8(0x1E);
            }
            if (m->state == 0xC && m->f53 != 1) {
                animate_2D5FA8(m, 1, 0, 0);
            }
        } else {
            int dead = 0x63;
            if (m->state != dead) {
                qcopy(vec, m->pos);
                vec[2] += 3.0f;
                d->tint = 0xFA;
                zero_2D5FA8(d->f120);
                burst_2D5FA8(m, d->f40, vec, 0.0f, 0.0f, 20, 8, 20, 4.0f, 2.0f, 9.0f, 1.0f, -1, 15.0f, 1, one, -1, 0);
                spawn_2D5FA8(m, 0x6C0, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                spawn_2D5FA8(m, 0x6C1, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                spawn_2D5FA8(m, 0x6C2, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                spawn_2D5FA8(m, 0x6C3, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                spawn_2D5FA8(m, 0x6C4, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                if (m->f53 != one) animate_2D5FA8(m, 1, 0, 3);
                m->state = dead;
                d->health = 6.0f;
                d->flags &= 0xFFFD;
            } else {
                if (D_0015EE84_2D5FA8 == 8) {
                    int k = d->part_id;
                    if (k != 0 && t != 0 && t->moby != 0 && t->moby->oclass == 0x661) {
                        if (k == one) D_L08_0015F694_2D5FA8 = one;
                        if (k == 2) D_L08_0015F698_2D5FA8 = one;
                        if (k == 3) D_L08_0015F69C_2D5FA8 = one;
                        if (k == 4) D_L08_0015F6A0_2D5FA8 = one;
                        if (D_L08_0015F694_2D5FA8 != 0 && D_L08_0015F698_2D5FA8 != 0) {
                            unsigned char *flags = D_0013D50F_2D5FA8 + 1;
                            if (flags[0xD] == 0) {
                                flags[0xD] = one;
                                sound_2D5FA8(1, 0, 0);
                                voice_2D5FA8(0x53DB, -1);
                            }
                        }
                    }
                }
                qcopy(vec, m->pos);
                vec[2] += 1.0f;
                explode_2D5FA8(m, 0, -1);
                event_2D5FA8(2, 0, m);
                burst_2D5FA8(m, d->f40, vec, 0.0f, 0.0f, 20, 8, 20, 4.0f, 2.0f, 9.0f, 1.0f, -1, 15.0f, 1, 1, -1, 0);
                spawn_2D5FA8(m, 0x6FE, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                spawn_2D5FA8(m, 0x6FE, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                spawn_2D5FA8(m, 0x6FF, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                spawn_2D5FA8(m, 0x6FF, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                spawn_2D5FA8(m, 0x6FF, m->pos, m->rot, 0, 0, 0.0f, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8, D_L08_0015F660_2D5FA8);
                if (d->partA != 0) delete_2D5FA8(d->partA);
                if (d->partB != 0) delete_2D5FA8(d->partB);
                delete_2D5FA8(m);
                return;
            }
        }
        effects_start_2D5FA8(m, &d->anim0);
    }

    m->alpha = 0xFF;
    if (d->partA != 0) d->partA->alpha = 0xFF;
    if (d->partB != 0) d->partB->alpha = 0xFF;

    follow_2D5FA8(100.0f, m, d->target, 0, 0, D_L08_001B0FB0_2D5FA8[d->path]->list, D_L08_001B0FB0_2D5FA8[d->path]->count);
    if (d->fF0 == 0) d->fF0 = *(int *)(D_0013E633_2D5FA8 + 0x2E9D);
    if (d->mode != 2) {
        float yaw, len, pitch;
        subtract_2D5FA8(vec, d->target, m->pos);
        vec[2] -= 3.0f;
        yaw = angle_2D5FA8(vec[0], vec[1]);
        len = length_2D5FA8(vec);
        pitch = -angle_2D5FA8(len, vec[2]);
        if (0.34906585f < pitch) {
            pitch = 0.34906585f;
        } else if (pitch < -0.7853982f) {
            pitch = -0.7853982f;
        }
        yaw = angle_delta_2D5FA8(yaw, m->rot[2]);
        approach_2D5FA8(&d->yaw, yaw, &d->yaw_speed, D_0015EE70_2D5FA8 * 12.566371f, D_0015EE70_2D5FA8 * 12.566371f, D_0015EE6C_2D5FA8 * 9.424778f);
        approach_2D5FA8(&d->pitch, pitch, &d->pitch_speed, D_0015EE70_2D5FA8 * 12.566371f, D_0015EE70_2D5FA8 * 12.566371f, D_0015EE6C_2D5FA8 * 9.424778f);
    } else {
        approach_2D5FA8(&d->yaw, 0.0f, &d->yaw_speed, D_0015EE70_2D5FA8 * 12.566371f, D_0015EE70_2D5FA8 * 12.566371f, D_0015EE6C_2D5FA8 * 9.424778f);
        approach_2D5FA8(&d->pitch, 0.0f, &d->pitch_speed, D_0015EE70_2D5FA8 * 12.566371f, D_0015EE70_2D5FA8 * 12.566371f, D_0015EE6C_2D5FA8 * 9.424778f);
    }
    rotation_2D5FA8(vec, 1, d->pitch);
    rotation_2D5FA8(d->f110, 2, d->yaw);
    matmul_2D5FA8(d->f110, vec, d->f110);
    {
        short a0 = d->anim0;
        short a2 = d->anim2;
        effects_update_2D5FA8(m, &d->anim0);
        if (d->partA != 0) {
            d->anim0 = a0;
            d->anim2 = a2;
            effects_update_2D5FA8(d->partA, &d->anim0);
        }
        if (d->partB != 0) {
            d->anim0 = a0;
            d->anim2 = a2;
            effects_update_2D5FA8(d->partB, &d->anim0);
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L08_002D68D0);
extern void func_L00_00250800_2D6C58(void *, int, void *) __asm__("func_L00_00250800");
extern void func_0020DAF8_2D6C58(char *, int, char *) __asm__("func_0020DAF8");
extern float func_00214158_2D6C58(void) __asm__("func_00214158");
extern float func_002140F8_2D6C58(float, float) __asm__("func_002140F8");
extern void func_L00_001FF4B0_2D6C58(void *, void *, float) __asm__("func_L00_001FF4B0");
extern void func_001F9BD8_2D6C58(void *, void *, void *) __asm__("func_001F9BD8");
extern void func_001F9C30_2D6C58(void *, void *, float) __asm__("func_001F9C30");
extern float func_001F9F90_2D6C58(float) __asm__("func_001F9F90");
extern float func_001F9FA8_2D6C58(float) __asm__("func_001F9FA8");
extern float func_001F9878_2D6C58(float) __asm__("func_001F9878");
extern int func_001FA898_2D6C58(float) __asm__("func_001FA898");
extern char *func_00219780_2D6C58(void *, void *, void *, int, int, int, int, int, int) __asm__("func_00219780");
extern float D_0015EE6C_2D6C58 __asm__("D_0015EE6C") MACRO_ADDR;
extern int D_L08_00161964_2D6C58 SDATA(D_L08_00161964);
extern int D_L08_00161968_2D6C58 SDATA(D_L08_00161968);
extern float D_L08_0016196C_2D6C58 SDATA(D_L08_0016196C);
extern float D_L08_00161970_2D6C58 SDATA(D_L08_00161970);
extern float D_L08_00161978_2D6C58 SDATA(D_L08_00161978);
extern int D_L08_0016197C_2D6C58 SDATA(D_L08_0016197C);
extern int D_L08_00161980_2D6C58 SDATA(D_L08_00161980);
extern int D_L08_00161984_2D6C58 SDATA(D_L08_00161984);
extern float D_L08_00161988_2D6C58 SDATA(D_L08_00161988);
extern float D_L08_0016198C_2D6C58 SDATA(D_L08_0016198C);

// Jitters the moby's vector, then spawns the effect groups for each of the count steps.
void func_L08_002D6C58(char *moby, int a1, int count) {
    char *d = *(char **)(moby + 0x78);
    char t10[32];
    float t30[8];
    float t50[4];
    float t60[4];
    float t70[4];
    float t80[4];
    float v90[4];
    int i;
    int x1, x2, x3;
    float s, t;

    func_L00_00250800_2D6C58(moby, a1, t50);
    func_0020DAF8_2D6C58(moby, a1, t10);
    for (i = 0; i < count; i++) {
        float *vp = v90;

        s = func_00214158_2D6C58();
        qcopy(vp, t50);
        v90[0] += func_002140F8_2D6C58(-0.05f, 0.05f);
        v90[1] += func_002140F8_2D6C58(-0.05f, 0.05f);
        v90[2] += func_002140F8_2D6C58(-0.05f, 0.05f);
        qcopy(t60, d + 0x40);
        qcopy(t70, d + 0x40);
        if (count / 3 < i) {
            func_L00_001FF4B0_2D6C58(t80, t30, func_002140F8_2D6C58(D_L08_0016196C_2D6C58, D_L08_0016196C_2D6C58 * 1.2f) * D_0015EE6C_2D6C58);
            func_001F9BD8_2D6C58(t60, t60, t80);
            func_001F9C30_2D6C58(t70, t70, 0.5f);
            t = func_001F9F90_2D6C58(s);
            t = t * (func_002140F8_2D6C58(0.0f, D_L08_00161978_2D6C58) * D_0015EE6C_2D6C58);
            t70[0] = t70[0] + t;
            t = func_001F9FA8_2D6C58(s);
            t = t * (func_002140F8_2D6C58(0.0f, D_L08_00161978_2D6C58) * D_0015EE6C_2D6C58);
            t70[1] = t70[1] + t;
            t70[2] = D_L08_00161970_2D6C58 * D_0015EE6C_2D6C58;
        } else {
            func_L00_001FF4B0_2D6C58(t80, t30, func_002140F8_2D6C58(0.0f, D_L08_0016196C_2D6C58) * D_0015EE6C_2D6C58);
            func_001F9BD8_2D6C58(t60, t60, t80);
            func_001F9C30_2D6C58(t70, t70, 0.5f);
            t = func_001F9F90_2D6C58(s);
            t = t * (func_002140F8_2D6C58(0.0f, D_L08_00161978_2D6C58 * 0.25f) * D_0015EE6C_2D6C58);
            t70[0] = t70[0] + t;
            t = func_001F9FA8_2D6C58(s);
            t = t * (func_002140F8_2D6C58(0.0f, D_L08_00161978_2D6C58 * 0.25f) * D_0015EE6C_2D6C58);
            t70[1] = t70[1] + t;
            t70[2] = D_L08_00161970_2D6C58 * D_0015EE6C_2D6C58;
        }
        t60[3] = D_L08_00161988_2D6C58;
        t70[3] = D_L08_0016198C_2D6C58;
        x1 = func_001FA898_2D6C58(func_001F9878_2D6C58(func_002140F8_2D6C58((float)D_L08_0016197C_2D6C58, (float)D_L08_0016197C_2D6C58 * 1.2f)));
        x2 = func_001FA898_2D6C58(func_001F9878_2D6C58(func_002140F8_2D6C58((float)D_L08_00161980_2D6C58, (float)D_L08_00161980_2D6C58 * 1.2f)));
        x3 = func_001FA898_2D6C58(func_001F9878_2D6C58(func_002140F8_2D6C58((float)D_L08_00161984_2D6C58, (float)D_L08_00161984_2D6C58 * 1.5f)));
        func_00219780_2D6C58(t50, t60, t70, D_L08_00161964_2D6C58, D_L08_00161968_2D6C58, x1, x2, x3, -1);
    }
}
INCLUDE_ASM("asm/overlays", func_L08_002D7010);
INCLUDE_ASM("asm/overlays", func_L08_002D7758);
INCLUDE_ASM("asm/overlays", func_L08_002DB438);
typedef u32 u128_DB468 __attribute__((mode(TI), aligned(16)));
typedef union {
    u128_DB468 q;
    f32 f[4];
    s32 i[4];
} Vec4_DB468;
struct MobyTrail_DB468 {
    Vec4_DB468 pos[8]; /* 0x00: ring of source positions */
    Vec4_DB468 rot[8]; /* 0x80: ring of source rotations */
    s32 copy_fade[4]; /* 0x100: start of copy moby byte 0x23; all 0 ends the trail */
    s32 delay[4]; /* 0x110: frames each copy lags behind */
    struct Moby *copies[4]; /* 0x120 */
    s16 head; /* 0x130: next ring slot */
    s16 count; /* 0x132: ring entries filled (max 8) */
    struct Moby *source; /* 0x134 */
    s32 copy_count; /* 0x138: copies in use (max 4) */
    s32 active; /* 0x13C */
};
struct HeroItemSlot_DB468 {
    struct Moby *moby; /* 0x00: item moby */
    struct Moby *moby2; /* 0x04: second item moby */
    u8 pad_08[0x8];
    s32 button_mask; /* 0x10: pad buttons that hold the gadget states */
    s32 unk14; /* 0x14: set on release */
    s16 timer; /* 0x18: counts down; a slot change waits for 0 */
    u8 unk1A; /* 0x1A: cleared on a slot change */
    u8 pad_1B[0x1];
    u8 unk1C; /* 0x1C: 2 blocks a slot change, 1 reloads timer */
    u8 timer_reload; /* 0x1D: timer reload value */
    u8 pad_1E[0x2];
    s32 unk20; /* 0x20 */
    s32 state; /* 0x24: 0 empty, 2 ready, 3 released */
    s32 item_id; /* 0x28: item in the slot */
    u8 pad_2C[0x24];
};
struct HeroMotion_DB468 {
    Vec4_DB468 pos; /* 0x80: world position */
    Vec4_DB468 rot; /* 0x90: rotation; z is the yaw */
    Vec4_DB468 unkA0; /* 0xA0 */
    Vec4_DB468 unkB0; /* 0xB0 */
    Vec4_DB468 unkC0; /* 0xC0 */
    Vec4_DB468 unkD0; /* 0xD0 */
    Vec4_DB468 velocity; /* 0xE0: per-frame velocity */
    Vec4_DB468 unkF0; /* 0xF0 */
    Vec4_DB468 unk100; /* 0x100 */
    Vec4_DB468 unk110; /* 0x110 */
    Vec4_DB468 unk120; /* 0x120 */
    Vec4_DB468 unk130; /* 0x130 */
    Vec4_DB468 unk140; /* 0x140 */
    Vec4_DB468 unk150; /* 0x150: copied from unk110/unk100 on hero_set_state */
    f32 unk160; /* 0x160 */
    f32 unk164; /* 0x164 */
    f32 unk168; /* 0x168 */
    f32 unk16C; /* 0x16C */
    Vec4_DB468 unk170; /* 0x170 */
    f32 unk180; /* 0x180: angle, compared with rot.z */
    f32 unk184; /* 0x184 */
    f32 unk188; /* 0x188 */
    u8 pad_18C[0x4];
};
struct HeroRandTimer_DB468 {
    s32 fired; /* 0xFF0: 1 once the deadline passed */
    s32 deadline; /* 0xFF4: frame count to wait for */
    s32 range; /* 0xFF8: random span; 0 holds the timer off */
};
struct HeroState_DB468 {
    s32 current; /* 0x2084: state id; hero_set_state sets it */
    s32 step; /* 0x2088: sub-step, 0 on state change */
    s32 control_mode; /* 0x208C */
    s32 prev; /* 0x2090: state before the last change */
    s32 prev_control_mode; /* 0x2094: control_mode before the last change */
    s32 prev_timer; /* 0x2098: state_timer before the last change */
    s32 prev2; /* 0x209C: state before prev */
    s32 prev2_control_mode; /* 0x20A0: control mode before prev_control_mode */
};
struct HeroHealth_DB468 {
    s32 hp; /* 0x22A8: hit points; 0 = dead */
    s32 unk22AC; /* 0x22AC: swapped with health.hp */
    s16 unk22B0; /* 0x22B0: s16 copy of health.hp */
    s16 unk22B2; /* 0x22B2 */
};
struct Hero_DB468 {
    u8 pad_0[0x40];
    f32 unk40[16]; /* 0x40 */
    struct HeroMotion_DB468 motion; /* 0x80 */
    f32 unk190; /* 0x190 */
    f32 unk194; /* 0x194 */
    s32 state_timer; /* 0x198: frames in the current state */
    s32 unk19C; /* 0x19C */
    s32 unk1A0; /* 0x1A0 */
    s32 unk1A4; /* 0x1A4 */
    s32 unk1A8; /* 0x1A8 */
    s32 unk1AC; /* 0x1AC */
    s16 unk1B0; /* 0x1B0 */
    s16 unk1B2; /* 0x1B2 */
    s32 unk1B4; /* 0x1B4 */
    s32 unk1B8; /* 0x1B8 */
    s32 unk1BC; /* 0x1BC */
    s32 unk1C0; /* 0x1C0 */
    s32 unk1C4; /* 0x1C4 */
    s16 unk1C8; /* 0x1C8 */
    s16 unk1CA; /* 0x1CA */
    s32 unk1CC; /* 0x1CC */
    s32 unk1D0; /* 0x1D0 */
    s32 unk1D4; /* 0x1D4 */
    s16 unk1D8; /* 0x1D8 */
    s16 unk1DA; /* 0x1DA */
    s16 unk1DC; /* 0x1DC */
    s16 unk1DE; /* 0x1DE */
    s16 unk1E0; /* 0x1E0 */
    s16 unk1E2; /* 0x1E2 */
    s16 unk1E4; /* 0x1E4 */
    s16 unk1E6; /* 0x1E6 */
    s16 unk1E8; /* 0x1E8 */
    s16 unk1EA; /* 0x1EA */
    s16 unk1EC; /* 0x1EC */
    s16 unk1EE; /* 0x1EE */
    s16 unk1F0; /* 0x1F0 */
    s16 unk1F2; /* 0x1F2 */
    s16 unk1F4; /* 0x1F4 */
    s16 unk1F6; /* 0x1F6 */
    s16 unk1F8; /* 0x1F8 */
    u8 pad_1FA[0x6];
    Vec4_DB468 unk200; /* 0x200 */
    Vec4_DB468 unk210; /* 0x210 */
    f32 unk220; /* 0x220 */
    f32 unk224; /* 0x224 */
    f32 unk228; /* 0x228 */
    f32 unk22C; /* 0x22C */
    f32 unk230; /* 0x230 */
    f32 unk234; /* 0x234 */
    u8 pad_238[0x4];
    u8 *coll_hit_moby; /* 0x23C: moby of the last push-out collision hit */
    s32 unk240; /* 0x240 */
    u8 pad_244[0x4];
    f32 unk248; /* 0x248 */
    u8 pad_24C[0xB];
    u8 unk257; /* 0x257 */
    u8 pad_258[0x18];
    Vec4_DB468 unk270; /* 0x270 */
    Vec4_DB468 unk280; /* 0x280 */
    Vec4_DB468 unk290; /* 0x290 */
    Vec4_DB468 unk2A0; /* 0x2A0 */
    Vec4_DB468 unk2B0; /* 0x2B0 */
    union { f32 f[2]; s32 i[2]; } unk2C0; /* 0x2C0: written as floats and zeroed as ints */
    union { f32 f[2]; s32 i[2]; } unk2C8; /* 0x2C8: written as floats and zeroed as ints */
    union { f32 f[2]; s32 i[2]; } unk2D0; /* 0x2D0: written as floats and zeroed as ints */
    union { f32 f; s32 i; } unk2D8; /* 0x2D8: written as a float and zeroed as an int */
    f32 unk2DC; /* 0x2DC */
    union { f32 f; s32 i; } unk2E0; /* 0x2E0: written as a float and zeroed as an int */
    union { f32 f; s32 i; } unk2E4; /* 0x2E4: written as a float and zeroed as an int */
    union { f32 f; s32 i; } unk2E8; /* 0x2E8: written as a float and zeroed as an int */
    f32 unk2EC; /* 0x2EC */
    f32 height_threshold; /* 0x2F0 */
    f32 unk2F4; /* 0x2F4 */
    s32 unk2F8; /* 0x2F8 */
    struct Moby *unk2FC; /* 0x2FC */
    s32 unk300; /* 0x300 */
    f32 unk304; /* 0x304 */
    s16 unk308; /* 0x308 */
    s16 unk30A; /* 0x30A */
    union { s16 s; u16 u; } unk30C; /* 0x30C: read signed, incremented unsigned */
    union { s16 s; u16 u; } unk30E; /* 0x30E: read signed, incremented unsigned */
    u8 pad_310[0xA0];
    f32 unk3B0; /* 0x3B0 */
    s32 unk3B4; /* 0x3B4 */
    s16 unk3B8; /* 0x3B8 */
    u8 pad_3BA[0x2];
    s16 unk3BC; /* 0x3BC */
    s16 unk3BE; /* 0x3BE */
    u8 pad_3C0[0x10];
    s32 unk3D0; /* 0x3D0 */
    s32 unk3D4; /* 0x3D4 */
    f32 unk3D8; /* 0x3D8 */
    f32 unk3DC; /* 0x3DC */
    s32 unk3E0; /* 0x3E0 */
    u8 *unk3E4; /* 0x3E4 */
    s32 unk3E8; /* 0x3E8 */
    u8 pad_3EC[0x8];
    f32 unk3F4; /* 0x3F4 */
    f32 unk3F8; /* 0x3F8 */
    u8 pad_3FC[0x4];
    Vec4_DB468 unk400; /* 0x400 */
    f32 unk410; /* 0x410 */
    f32 unk414; /* 0x414 */
    s32 unk418; /* 0x418: set when velocity.z clamps to unk500.z, counts up */
    s16 unk41C; /* 0x41C */
    s16 unk41E; /* 0x41E: set to 1 when FUN_L00_00233a78(velocity) < 0.001 */
    s32 unk420; /* 0x420: per-state scale_game_frames(N), compared with state_timer */
    f32 unk424; /* 0x424 */
    f32 unk428; /* 0x428 */
    f32 unk42C; /* 0x42C */
    f32 unk430; /* 0x430 */
    f32 unk434; /* 0x434 */
    f32 unk438; /* 0x438 */
    f32 unk43C; /* 0x43C */
    f32 unk440; /* 0x440 */
    f32 unk444; /* 0x444 */
    f32 unk448; /* 0x448 */
    s32 unk44C; /* 0x44C */
    s32 unk450; /* 0x450 */
    f32 unk454; /* 0x454 */
    f32 unk458; /* 0x458 */
    f32 unk45C; /* 0x45C */
    Vec4_DB468 unk460; /* 0x460 */
    Vec4_DB468 unk470; /* 0x470 */
    f32 unk480; /* 0x480 */
    f32 unk484; /* 0x484 */
    f32 unk488; /* 0x488 */
    f32 unk48C; /* 0x48C */
    f32 unk490; /* 0x490 */
    f32 unk494; /* 0x494 */
    s16 unk498; /* 0x498 */
    s16 unk49A; /* 0x49A */
    s16 unk49C; /* 0x49C */
    s16 unk49E; /* 0x49E */
    f32 unk4A0; /* 0x4A0 */
    s16 unk4A4; /* 0x4A4 */
    s16 unk4A6; /* 0x4A6 */
    s16 unk4A8; /* 0x4A8 */
    s16 unk4AA; /* 0x4AA */
    s16 unk4AC; /* 0x4AC */
    u8 unk4AE; /* 0x4AE */
    u8 unk4AF; /* 0x4AF */
    f32 unk4B0; /* 0x4B0 */
    u8 pad_4B4[0x4];
    f32 unk4B8; /* 0x4B8 */
    s32 unk4BC; /* 0x4BC */
    f32 unk4C0; /* 0x4C0 */
    s32 unk4C4; /* 0x4C4 */
    u8 pad_4C8[0x8];
    Vec4_DB468 unk4D0; /* 0x4D0 */
    u8 pad_4E0[0x4];
    f32 unk4E4; /* 0x4E4 */
    s32 unk4E8; /* 0x4E8 */
    f32 unk4EC; /* 0x4EC */
    f32 unk4F0; /* 0x4F0 */
    u8 pad_4F4[0x4];
    s32 unk4F8; /* 0x4F8: first argument of FUN_L00_00233f80 (FUN_L01_00233de0) */
    u8 pad_4FC[0x4];
    Vec4_DB468 unk500; /* 0x500 */
    Vec4_DB468 unk510; /* 0x510 */
    Vec4_DB468 unk520; /* 0x520 */
    Vec4_DB468 unk530; /* 0x530 */
    Vec4_DB468 unk540; /* 0x540 */
    Vec4_DB468 unk550; /* 0x550 */
    s32 unk560; /* 0x560 */
    s32 unk564; /* 0x564 */
    f32 unk568; /* 0x568 */
    s32 unk56C; /* 0x56C */
    s32 unk570; /* 0x570 */
    f32 unk574; /* 0x574 */
    s32 unk578; /* 0x578 */
    f32 unk57C; /* 0x57C */
    f32 unk580; /* 0x580 */
    s32 unk584; /* 0x584 */
    f32 unk588; /* 0x588 */
    s32 unk58C; /* 0x58C */
    s32 unk590; /* 0x590 */
    s32 unk594; /* 0x594 */
    s32 unk598; /* 0x598 */
    f32 unk59C; /* 0x59C */
    s32 unk5A0; /* 0x5A0 */
    s32 unk5A4; /* 0x5A4 */
    s32 unk5A8; /* 0x5A8 */
    union { f32 f; s32 i; } unk5AC; /* 0x5AC: float approached toward a speed, zeroed as an int */
    f32 unk5B0; /* 0x5B0 */
    s32 unk5B4; /* 0x5B4 */
    s32 unk5B8; /* 0x5B8 */
    s16 unk5BC; /* 0x5BC */
    s16 unk5BE; /* 0x5BE */
    s32 unk5C0; /* 0x5C0 */
    s32 unk5C4; /* 0x5C4 */
    f32 unk5C8; /* 0x5C8 */
    f32 unk5CC; /* 0x5CC */
    f32 unk5D0; /* 0x5D0 */
    f32 unk5D4; /* 0x5D4 */
    struct Moby *unk5D8; /* 0x5D8 */
    f32 unk5DC; /* 0x5DC */
    Vec4_DB468 unk5E0; /* 0x5E0 */
    s32 *unk5F0; /* 0x5F0 */
    s32 unk5F4; /* 0x5F4 */
    f32 unk5F8; /* 0x5F8 */
    s32 unk5FC; /* 0x5FC */
    s32 unk600; /* 0x600 */
    f32 unk604; /* 0x604 */
    u8 pad_608[0x4];
    s32 unk60C; /* 0x60C */
    f32 unk610; /* 0x610 */
    f32 unk614; /* 0x614 */
    union { f32 f; s32 i; } unk618; /* 0x618: float distance clamp, zeroed as an int */
    u8 pad_61C[0x54];
    f32 unk670; /* 0x670 */
    f32 unk674; /* 0x674 */
    u8 pad_678[0x10];
    f32 unk688; /* 0x688 */
    u8 pad_68C[0x4];
    f32 unk690; /* 0x690 */
    f32 unk694; /* 0x694 */
    s32 unk698; /* 0x698 */
    f32 unk69C; /* 0x69C */
    s32 unk6A0; /* 0x6A0 */
    struct Moby *unk6A4; /* 0x6A4 */
    u8 pad_6A8[0x18];
    Vec4_DB468 unk6C0; /* 0x6C0: 0x60 bytes cleared by FillTransferWords */
    f32 unk6D0; /* 0x6D0 */
    f32 unk6D4; /* 0x6D4 */
    u8 pad_6D8[0x48];
    Vec4_DB468 unk720; /* 0x720 */
    u8 pad_730[0x10];
    Vec4_DB468 unk740; /* 0x740 */
    Vec4_DB468 unk750; /* 0x750 */
    Vec4_DB468 unk760; /* 0x760 */
    Vec4_DB468 unk770; /* 0x770 */
    Vec4_DB468 unk780; /* 0x780 */
    Vec4_DB468 unk790; /* 0x790 */
    u8 pad_7A0[0x30];
    f32 unk7D0[0x20]; /* 0x7D0 */
    u8 pad_850[0x4];
    f32 unk854; /* 0x854 */
    f32 unk858; /* 0x858 */
    f32 unk85C; /* 0x85C */
    f32 unk860; /* 0x860 */
    s32 unk864; /* 0x864 */
    f32 unk868; /* 0x868 */
    u8 *unk86C; /* 0x86C */
    s32 unk870; /* 0x870 */
    f32 unk874; /* 0x874 */
    f32 unk878; /* 0x878 */
    f32 unk87C; /* 0x87C */
    u8 pad_880[0x4];
    s16 unk884; /* 0x884 */
    s16 unk886; /* 0x886 */
    s16 unk888; /* 0x888 */
    s16 unk88A; /* 0x88A */
    u8 unk88C; /* 0x88C */
    u8 unk88D; /* 0x88D */
    u8 unk88E; /* 0x88E */
    u8 unk88F; /* 0x88F */
    u8 pad_890[0x4];
    s32 unk894; /* 0x894: frame counter shown as m:ss.hh on the HUD (FUN_L05_00266710) */
    s16 unk898; /* 0x898 */
    s16 unk89A; /* 0x89A: shown + 1 (capped at 3) on the HUD (FUN_L05_00266320) */
    s16 unk89C; /* 0x89C */
    s16 unk89E; /* 0x89E */
    f32 unk8A0; /* 0x8A0 */
    f32 unk8A4; /* 0x8A4 */
    s32 unk8A8; /* 0x8A8: count shown on the HUD (FUN_L05_00266710) */
    s16 unk8AC; /* 0x8AC */
    u8 pad_8AE[0x1];
    u8 unk8AF; /* 0x8AF */
    s16 unk8B0; /* 0x8B0 */
    s16 unk8B2; /* 0x8B2 */
    void *unk8B4; /* 0x8B4 */
    union { f32 f; s32 i; } unk8B8; /* 0x8B8: read as a float, zeroed as an int */
    s16 unk8BC; /* 0x8BC */
    s16 unk8BE; /* 0x8BE */
    s32 unk8C0; /* 0x8C0: 1..3 picks the HUD rank string (FUN_L05_00266320) */
    s32 unk8C4; /* 0x8C4 */
    u8 pad_8C8[0x4];
    s16 unk8CC; /* 0x8CC */
    u8 unk8CE; /* 0x8CE */
    u8 pad_8CF[0x1];
    Vec4_DB468 unk8D0; /* 0x8D0 */
    s32 unk8E0; /* 0x8E0 */
    f32 unk8E4; /* 0x8E4 */
    f32 unk8E8; /* 0x8E8 */
    f32 unk8EC; /* 0x8EC */
    s32 unk8F0; /* 0x8F0 */
    s32 unk8F4; /* 0x8F4 */
    s16 unk8F8; /* 0x8F8 */
    u8 pad_8FA[0x2];
    f32 unk8FC; /* 0x8FC */
    s16 unk900; /* 0x900 */
    s16 unk902; /* 0x902 */
    u8 pad_904[0x6];
    s16 unk90A; /* 0x90A */
    s16 unk90C; /* 0x90C */
    s16 unk90E; /* 0x90E */
    s32 unk910; /* 0x910 */
    s32 unk914; /* 0x914 */
    u8 pad_918[0x8];
    Vec4_DB468 unk920; /* 0x920 */
    f32 unk930; /* 0x930 */
    u8 pad_934[0xC];
    f32 unk940; /* 0x940 */
    f32 unk944; /* 0x944 */
    f32 unk948; /* 0x948 */
    f32 unk94C; /* 0x94C */
    f32 unk950; /* 0x950 */
    f32 unk954; /* 0x954 */
    u8 pad_958[0x8];
    f32 unk960; /* 0x960 */
    struct Moby *unk964; /* 0x964 */
    s32 unk968; /* 0x968 */
    f32 unk96C; /* 0x96C */
    f32 unk970; /* 0x970 */
    s32 unk974; /* 0x974 */
    u8 pad_978[0x4];
    f32 unk97C; /* 0x97C */
    f32 unk980; /* 0x980 */
    f32 unk984; /* 0x984 */
    s32 unk988; /* 0x988 */
    u8 pad_98C[0x4];
    struct Moby *unk990; /* 0x990 */
    struct Moby *unk994; /* 0x994 */
    f32 unk998; /* 0x998 */
    s16 unk99C; /* 0x99C */
    s16 unk99E; /* 0x99E */
    f32 unk9A0; /* 0x9A0 */
    f32 unk9A4; /* 0x9A4 */
    f32 unk9A8; /* 0x9A8 */
    f32 unk9AC; /* 0x9AC */
    f32 unk9B0; /* 0x9B0 */
    f32 unk9B4; /* 0x9B4 */
    f32 unk9B8; /* 0x9B8 */
    s16 unk9BC; /* 0x9BC */
    s16 unk9BE; /* 0x9BE */
    u8 pad_9C0[0x4];
    f32 unk9C4; /* 0x9C4 */
    f32 unk9C8; /* 0x9C8 */
    f32 unk9CC; /* 0x9CC */
    f32 unk9D0; /* 0x9D0: rail yaw (FUN_L01_002f6328) */
    f32 unk9D4; /* 0x9D4 */
    u8 pad_9D8[0x4];
    f32 unk9DC; /* 0x9DC: rail speed, eased toward the rail's speed */
    f32 unk9E0; /* 0x9E0: pull toward the rail, capped at the distance */
    f32 unk9E4; /* 0x9E4 */
    f32 unk9E8; /* 0x9E8 */
    u8 pad_9EC[0x64];
    u8 *unkA50; /* 0xA50 */
    struct Moby *unkA54; /* 0xA54 */
    s32 unkA58; /* 0xA58 */
    f32 unkA5C; /* 0xA5C */
    s32 unkA60; /* 0xA60 */
    s32 unkA64; /* 0xA64 */
    f32 unkA68; /* 0xA68 */
    f32 unkA6C; /* 0xA6C */
    f32 unkA70; /* 0xA70 */
    u8 pad_A74[0x8];
    s32 unkA7C; /* 0xA7C */
    s32 unkA80; /* 0xA80 */
    u8 *unkA84; /* 0xA84 */
    u8 *unkA88; /* 0xA88 */
    void *unkA8C; /* 0xA8C */
    f32 unkA90; /* 0xA90 */
    f32 unkA94; /* 0xA94 */
    s32 unkA98; /* 0xA98 */
    s32 unkA9C; /* 0xA9C */
    s32 unkAA0; /* 0xAA0 */
    s32 unkAA4; /* 0xAA4 */
    f32 unkAA8; /* 0xAA8 */
    u8 pad_AAC[0x8];
    s32 unkAB4; /* 0xAB4 */
    u8 pad_AB8[0x248];
    u8*unkD00; /* 0xD00 */
    u8*unkD04; /* 0xD04 */
    u8 *unkD08[2]; /* 0xD08: per item slot 0/1: moby from FUN_L00_0024f028 */
    u8 *unkD10; /* 0xD10 */
    s32 unkD14; /* 0xD14 */
    u8 pad_D18[0x2D8];
    struct HeroRandTimer_DB468 rand_timer;/* 0xFF0 */
    u8 pad_FFC[0x14];
    s32 unk1010; /* 0x1010 */
    u8 pad_1014[0x7C];
    struct HeroItemSlot_DB468 items[4]; /* 0x1090: item slots; slot 0 is the equipped gadget */
    u8 pad_11D0[0x110];
    s16 unk12E0; /* 0x12E0 */
    u8 unk12E2; /* 0x12E2 */
    u8 unk12E3; /* 0x12E3 */
    u8 base_condition; /* 0x12E4 */
    u8 selector_1; /* 0x12E5 */
    u8 selector_3; /* 0x12E6 */
    u8 unk12E7; /* 0x12E7 */
    u8 unk12E8; /* 0x12E8 */
    u8 unk12E9; /* 0x12E9 */
    u8 unk12EA; /* 0x12EA */
    u8 selector_11; /* 0x12EB */
    u8 selector_13; /* 0x12EC */
    u8 unk12ED; /* 0x12ED */
    u8 unk12EE; /* 0x12EE */
    u8 pad_12EF[0x301];
    struct Moby *ship_moby; /* 0x15F0: the ship the hero is flying (l17 FUN_L17_002ed018) */
    s16 ship_oclass; /* 0x15F4: its oclass, -1 when none */
    u8 ship_ammo; /* 0x15F6: shots left in the space levels; firing needs one and takes it (FUN_L11_003126f8) */
    u8 ship_ammo_max; /* 0x15F7: ammo pips the ship HUD draws, lit while below ship_ammo */
    u8 unk15F8; /* 0x15F8 */
    u8 unk15F9; /* 0x15F9 */
    u8 unk15FA; /* 0x15FA */
    u8 unk15FB; /* 0x15FB */
    f32 ship_hp; /* 0x15FC: ship health; l17 subtracts collision damage and explodes the ship below 0 */
    f32 ship_hp_max; /* 0x1600: full ship_hp; the HUD bar shows ship_hp over it */
    f32 unk1604; /* 0x1604 */
    s32 ship_hp_percent; /* 0x1608: ship_hp as a percentage for the HUD */
    s16 unk160C; /* 0x160C */
    u8 unk160E; /* 0x160E */
    u8 ship_flags; /* 0x160F: 2 = being steered back from the edge or height limit of the space arena (FUN_L11_00313f60) */
    u8 pad_1610[0x4];
    s32 unk1614; /* 0x1614 */
    u8 pad_1618[0x8];
    void *unk1620; /* 0x1620 */
    void *unk1624; /* 0x1624 */
    u8 pad_1628[0x8];
    s32 unk1630; /* 0x1630 */
    s16 unk1634; /* 0x1634 */
    s16 unk1636; /* 0x1636 */
    u8 pad_1638[0x8];
    Vec4_DB468 unk1640; /* 0x1640 */
    s32 unk1650; /* 0x1650 */
    u8 pad_1654[0xC];
    s32 unk1660; /* 0x1660 */
    u8 pad_1664[0xC];
    struct MobyTrail_DB468 trail; /* 0x1670: trail of moby copies following hero.moby */
    u8 pad_17B0[0x350];
    Vec4_DB468 unk1B00[32]; /* 0x1B00: ring of 32 quads indexed by unk21B0 */
    u8 pad_1D00[0x20];
    f32 unk1D20; /* 0x1D20 */
    f32 unk1D24; /* 0x1D24 */
    u8 pad_1D28[0x238];
    u8 unk1F60[0x40]; /* 0x1F60: 0x40-byte buffer cleared by FUN_L00_002b58d8 */
    u8 unk1FA0[0x40]; /* 0x1FA0: 0x40-byte buffer cleared by FUN_L00_002b58d8 */
    u8 *unk1FE0; /* 0x1FE0: moby set by FUN_L00_002b58d8 */
    u8 pad_1FE4[0x11];
    u8 unk1FF5; /* 0x1FF5 */
    u8 ammo_used; /* 0x1FF6 */
    u8 ammo_capacity; /* 0x1FF7 */
    u8 pad_1FF8[0x48];
    struct Moby *unk2040; /* 0x2040: nearest oclass 0x25D moby (FUN_L00_002d2ee8) */
    f32 unk2044; /* 0x2044: distance to unk2040; 100000 when none */
    s32 unk2048; /* 0x2048 */
    u8 pad_204C[0x34];
    struct Moby *moby; /* 0x2080: the hero's moby */
    struct HeroState_DB468 state; /* 0x2084 */
    u8 unk20A4; /* 0x20A4 */
    u8 unk20A5; /* 0x20A5 */
    u8 unk20A6; /* 0x20A6: forces slot 0 to item 8 */
    u8 unk20A7; /* 0x20A7 */
    u8 unk20A8; /* 0x20A8 */
    u8 unk20A9; /* 0x20A9 */
    u8 unk20AA; /* 0x20AA */
    u8 unk20AB; /* 0x20AB */
    u8 unk20AC; /* 0x20AC */
    u8 unk20AD; /* 0x20AD */
    u8 unk20AE; /* 0x20AE */
    u8 unk20AF; /* 0x20AF */
    u8 pad_20B0[0x1];
    u8 unk20B1; /* 0x20B1 */
    u8 unk20B2; /* 0x20B2 */
    u8 unk20B3; /* 0x20B3 */
    u8 unk20B4; /* 0x20B4 */
    u8 pad_20B5[0x3];
    s32 pending_item[7]; /* 0x20B8: per slot: item to switch to */
    s32 selected_item[7]; /* 0x20D4: per slot: item after a switch */
    s32 saved_item[7]; /* 0x20F0: per slot: item kept while another is forced in */
    s32 restore_item[7]; /* 0x210C: per slot: 1 puts saved_item back */
    u8 pad_2128[0x88];
    s32 unk21B0; /* 0x21B0: unk1B00 ring index */
    s32 unk21B4; /* 0x21B4: unk1B00 ring count */
    u8 pad_21B8[0x60];
    s32 unk2218; /* 0x2218 */
    u8 pad_221C[0x4];
    s32 unk2220; /* 0x2220 */
    s32 unk2224; /* 0x2224 */
    s32 unk2228; /* 0x2228 */
    s32 unk222C; /* 0x222C */
    s32 unk2230; /* 0x2230 */
    s32 unk2234; /* 0x2234 */
    u8 pad_2238[0x38];
    s32 unk2270; /* 0x2270 */
    s32 unk2274; /* 0x2274 */
    u8 pad_2278[0x8];
    struct Moby *unk2280; /* 0x2280 */
    s32 unk2284; /* 0x2284 */
    f32 unk2288; /* 0x2288 */
    f32 unk228C; /* 0x228C */
    f32 unk2290; /* 0x2290 */
    s32 unk2294; /* 0x2294 */
    s32 unk2298; /* 0x2298 */
    f32 unk229C; /* 0x229C */
    s32 unk22A0; /* 0x22A0 */
    f32 unk22A4; /* 0x22A4 */
    struct HeroHealth_DB468 health; /* 0x22A8 */
    s32 unk22B4; /* 0x22B4 */
    f32 unk22B8; /* 0x22B8: distance to the nearest carrying path this frame (FUN_L01_002f3120 keeps the minimum) */
    u8 pad_22BC[0x8];
    s32 unk22C4; /* 0x22C4 */
    s16 unk22C8; /* 0x22C8 */
    u8 unk22CA; /* 0x22CA */
    u8 unk22CB; /* 0x22CB */
    s16 unk22CC; /* 0x22CC */
    s16 unk22CE; /* 0x22CE */
    u8 pad_22D0[0x2];
    s16 unk22D2; /* 0x22D2 */
    s16 unk22D4; /* 0x22D4: countdown set on pad bit 0x10 press */
    s16 unk22D6; /* 0x22D6: countdown; nonzero with unk22D4 switches pending_item[0] */
    s16 unk22D8; /* 0x22D8 */
    s16 unk22DA; /* 0x22DA */
    s16 unk22DC; /* 0x22DC */
    s16 unk22DE; /* 0x22DE */
    s16 unk22E0; /* 0x22E0 */
    u8 pad_22E2[0x12];
    s32 unk22F4; /* 0x22F4 */
    s32 unk22F8; /* 0x22F8 */
    s16 unk22FC; /* 0x22FC */
};
extern struct Hero_DB468 D_0013F450_DB468 __asm__("D_0013F450");
extern short D_L08_00161A00_DB468 SDATA(D_L08_00161A00);
extern float D_L08_001D7320_DB468[4] __asm__("D_L08_001D7320");
extern char D_L08_0015F660_DB468[] __asm__("D_L08_0015F660") MACRO_ADDR;
extern int D_0015EE84_DB468 __asm__("D_0015EE84") MACRO_ADDR;
extern float D_0015EE6C_DB468 __asm__("D_0015EE6C") MACRO_ADDR;
extern void func_L02_002A52B0_DB468(void *, float) __asm__("func_L02_002A52B0");
extern void func_001F49B0_DB468(void *, void *) __asm__("func_001F49B0");
extern void func_00216270_DB468(void *) __asm__("func_00216270");
extern int func_L00_0028EB98_DB468(struct Moby *, int) __asm__("func_L00_0028EB98");
extern void func_L00_0028EBF0_DB468(int) __asm__("func_L00_0028EBF0");
extern char *func_L00_002D9340_DB468(void *, float) __asm__("func_L00_002D9340");
extern float func_00214158_DB468(void) __asm__("func_00214158");
extern float func_002140F8_DB468(float, float) __asm__("func_002140F8");
extern float func_001F9F90_DB468(float) __asm__("func_001F9F90");
extern float func_001F9FA8_DB468(float) __asm__("func_001F9FA8");
extern int func_L00_00258BC8_DB468(int, int) __asm__("func_L00_00258BC8");
extern int func_002140B0_DB468(int) __asm__("func_002140B0");
extern void func_L00_002703E8_DB468(void *, void *, int, int) __asm__("func_L00_002703E8");
extern void func_L00_00258DB0_DB468(float *, float, float) __asm__("func_L00_00258DB0");
extern void func_001F9BD8_DB468(void *, void *, void *) __asm__("func_001F9BD8");
extern unsigned char *func_L00_00272770_DB468(void *, void *, void *, float, float) __asm__("func_L00_00272770");
extern float func_001F9878_DB468(float) __asm__("func_001F9878");
extern s32 func_001FA898_DB468(f32) __asm__("func_001FA898");

/* Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/l08/gameplay/entities/002b8228.c, FUN_L08_002da0f0. */
void func_L08_002DB468(struct Moby *moby) {
    Vec4_DB468 pos;
    Vec4_DB468 v;
    char *r;
    int i;
    int n;
    float sc, sp;

    if ((*(int *)&D_L08_00161A00_DB468) == 0) {
        (*(int *)&D_L08_00161A00_DB468) = 1;
        func_L02_002A52B0_DB468(D_L08_001D7320_DB468, 0.6666667f);
    }
    func_001F49B0_DB468(func_00216270_DB468, moby);
    if (D_0015EE84_DB468 != 8)
        return;
    if (!(D_0013F450_DB468.motion.pos.f[2] < D_L08_001D7320_DB468[2]))
        return;
    if (!(D_L08_001D7320_DB468[2] <= D_0013F450_DB468.motion.pos.f[2] - D_0013F450_DB468.motion.unk100.f[2]))
        return;
    if (func_L00_0028EB98_DB468(D_0013F450_DB468.moby, D_0013F450_DB468.health.unk22B2)) {
        func_L00_0028EBF0_DB468(D_0013F450_DB468.health.unk22B2);
        D_0013F450_DB468.health.unk22B2 = -1;
    }
    qcopy(&pos, &D_0013F450_DB468.motion.pos);
    pos.f[2] = D_L08_001D7320_DB468[2];
    r = func_L00_002D9340_DB468(&pos, 3.0f);
    if (r)
        r[0x23] = 0x70;
    for (i = 0; i < 16; i++) {
        float ang = func_00214158_DB468();
        float k = func_002140F8_DB468(D_0015EE6C_DB468 * 0.0f, D_0015EE6C_DB468 * 3.0f);
        v.f[0] = func_001F9F90_DB468(ang) * k;
        v.f[1] = func_001F9FA8_DB468(ang) * k;
        v.f[2] = func_002140F8_DB468(D_0015EE6C_DB468 * 3.0f, D_0015EE6C_DB468 * 6.5f);
        n = func_L00_00258BC8_DB468(0x5A, 0x78);
        func_L00_002703E8_DB468(&pos, &v, func_002140B0_DB468(2), n);
    }
    for (i = 0; i < 16; i++) {
        unsigned char *q;
        func_L00_00258DB0_DB468(v.f, 1.0f, 1.0f);
        func_001F9BD8_DB468(&v, &v, &pos);
        v.f[2] = D_L08_001D7320_DB468[2] + 0.05f;
        sc = func_002140F8_DB468(0.7f, 1.0f);
        sp = i == 0 ? 2.0f : -2.0f;
        q = func_L00_00272770_DB468(&v, D_L08_0015F660_DB468, &D_L08_001D7320_DB468[2], sc, sp);
        if (q)
            *(short *)(q + 0xA) = func_001FA898_DB468(func_001F9878_DB468(func_002140F8_DB468(30.0f, 60.0f)));
    }
}
typedef u32 u128_DB768 __attribute__((mode(TI), aligned(16)));
typedef union {
    u128_DB768 q;
    f32 f[4];
    s32 i[4];
} Vec4;
struct Manip;
struct GifEntry;
struct AnimSeq;
extern float func_00214158(void);
extern float func_001F9F90(float);
extern float func_001F9FA8(float);
extern int func_L00_00258BC8(int, int);
extern int func_002140B0(int);
extern void func_001F9BD8(void *, void *, void *);
extern short D_L08_00161A28;
extern short D_L08_00161A30;
extern u16 D_L08_00161A38;
extern void func_001F9BF0(void *, void *, void *);
extern void func_001F9C30(void *, void *, f32);
extern f32 func_001FA888(s32);
extern float func_L00_00258C80(float, float);
extern unsigned char *func_L00_0026DEA0(void *, float, float, float, int, void *, float, int);
extern char *func_L00_0026DA50(void *, void *, int, int, int, int, float);

/* Strings count glowing puffs from one point to another, growing from size0 to size1, then bursts a spark shower at each end.
   Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/l08/gameplay/entities/002b8228.c, FUN_L08_002da3f0. */
void func_L08_002DB768(struct Moby *moby, void *from, void *to, int count, f32 size0, f32 size1) {
    Vec4 step;
    Vec4 pos;
    Vec4 vel;
    f32 grow;
    f32 size;
    unsigned char *puff;
    unsigned char *tail;
    int alpha, grey;
    int i;

    FastVecSub(&step, to, from);
    FastVecScale(&step, &step, 1.0f / (f32)count);
    grow = (size1 - size0) / (f32)count;
    vel.q = 0;
    vel.f[3] = 1.0f;
    vel.f[2] = 0.01f;
    for (i = 0; i < count; i++) {
        FastVecScale(&pos, &step, func_001FA888(i));
        FastVecAdd(&pos, from, &pos);
        vel.f[0] = randf_sym(0.0f, 0.005f);
        vel.f[1] = randf_sym(0.0f, 0.005f);
        vel.f[2] = random_float_between((*(float *)&D_L08_00161A28) * 0.1f, (*(float *)&D_L08_00161A28));
        alpha = rand_range(0x30, 0x70);
        grey = rand_range(0x30, 0x7F);
        grey |= (grey << 16) | (grey << 8);
        size = random_float_between(1.0f, 1.02f);
        puff = func_L00_0026DEA0(&pos, (*(float *)&D_L08_00161A30), 1.0f, size, rand_range(-2, 2), &vel,
                                grow + size0 * 210000.0f, (alpha << 24) | grey);
        if (puff) {
            tail = puff + 0x20;
            if (random_integer_below(2)) {
                puff[3] = 0x44;
                grey = rand_range(0x60, 0xE0);
                grey |= (grey << 16) | (grey << 8);
                *(u32 *)(puff + 4) = (alpha << 24) | grey;
            }
            *(u16 *)(puff + 0xA) = D_L08_00161A38;
            *(s32 *)(tail + 4) = 2;
            tail[0xA] = alpha;
            tail[0xB] = D_L08_00161A38;
        }
    }
    vel.f[0] = FastCos(random_angle_radians()) * 0.05f;
    vel.f[1] = FastSin(random_angle_radians()) * 0.05f;
    vel.f[2] = 0.0f;
    vel.f[2] = random_float_between(0.01f, 0.03f);
    func_L00_0026DA50(from, &vel, 0x4F007FFF, 0x1FFFFFFF,
                     rand_range(scale_ticks(10), scale_ticks(20)), 1, 10000.0f);
    vel.f[0] = FastCos(random_angle_radians()) * 0.05f;
    vel.f[1] = FastSin(random_angle_radians()) * 0.05f;
    vel.f[2] = 0.0f;
    vel.f[2] = random_float_between(0.01f, 0.03f);
    func_L00_0026DA50(to, &vel, 0x4F007FFF, 0x1FFFFFFF,
                     rand_range(scale_ticks(10), scale_ticks(20)), 1, 20000.0f);
}
extern float func_001FA850(float, float);
extern float func_001F9D10(void *, void *);
extern short *D_L08_001AC340[];
extern char *D_L08_00160058 MACRO_ADDR;
extern char D_0013E633[] NOT_SDA;

/* Picks the best candidate moby from the moby's list by heading and distance.
 * Exact since tools/ps2eeas_nops.py puts the hazard nop after the shared bc1fl's label. */
char *func_L08_002DBD88(char *moby) {
    short *t = D_L08_001AC340[(unsigned char)moby[0x21]];
    char *best;
    char *p;
    float bestD, bestA;
    int idx;
    char *base;
    if (t == 0) return 0;
    best = 0;
    idx = *(unsigned short *)t & 0x7FFF;
    p = D_L08_00160058 + (idx << 8);
    bestA = 0.0f;
    bestD = bestA;
    for (;;) {
        if (*(short *)(p + 0xA6) != 0x14D && *(unsigned char *)(p + 0xBC) == 0) {
            float ang, d, a;
            a = func_L00_001FF860(*(float *)(p + 0x10) - *(float *)(moby + 0x10),
                                  *(float *)(p + 0x14) - *(float *)(moby + 0x14));
            base = D_0013E633 + 0xE1D;
            ang = FastDiffRots(a, func_L00_001FF860(*(float *)(base + 0x80) - *(float *)(moby + 0x10),
                                                     *(float *)(base + 0x84) - *(float *)(moby + 0x14)));
            d = FastVecDist(moby + 0x10, p + 0x10);
            if (ang < 1.5707964f) {
                if (bestA < ang) {
                    best = p;
                    bestD = d;
                    bestA = ang;
                }
            } else if ((d >= 16.0f && (d < bestD || bestD < 16.0f)) || (d < 16.0f && bestD < d)) {
                best = p;
                bestD = d;
                bestA = ang;
            }
        }
        if (*t < -1) return best;
        t++;
        idx = *(unsigned short *)t & 0x7FFF;
        p = D_L08_00160058 + (idx << 8);
    }
}
INCLUDE_ASM("asm/overlays", func_L08_002DBF68);
typedef int Q_2dd128 __attribute__((mode(TI)));
extern int D_L08_0015F6A8 MACRO_ADDR;
extern int D_L08_00179C90[];
extern int D_L08_0015F674 MACRO_ADDR;
extern int D_0013A5E0_d[] __asm__("D_0013A5E0") NOT_SDA;
extern float D_0015EE6C_d __asm__("D_0015EE6C") MACRO_ADDR;
extern void func_0020D960(void *, int, void *);
extern float func_001FA748(float, float);
extern void func_L00_0025AFA8(void *, void *);
extern void func_001F9BC0(void *);
extern void func_L00_00262DF0_i(int, void *, float, void *) __asm__("func_L00_00262DF0");
extern void func_001F9BF0(void *, void *, void *);
extern void func_L00_002617B0(void *, void *, void *, void *);
extern void func_L08_002DD4F8(char *);
extern void func_L08_002DDB68(char *moby);
extern int func_L08_002DD9C0(char *m);
extern void func_L08_002DD818(char *moby);
extern void func_L08_002DD440(char *moby);

/* Platform moby update: toggles visibility, spins, records its start pose, then rides its path while the
 * player stands on it; at the end of the path it can hand over to the cutscene state. */
void func_L08_002DD128(char *m) {
    char *d = *(char **)(m + 0x78);
    float pos[4];
    float rot[4];
    float vec[4];
    float tgt[4];
    float *rp;
    qcopy(pos, m + 0x10);
    qcopy(rot, m + 0x40);
    if (D_L08_0015F6A8 != 2 && *(int *)(d + 0x124) != 0) {
        m[0x31] = 1;
        *(unsigned short *)(m + 0x34) &= 0xFFFE;
    } else {
        m[0x31] = 0;
        *(unsigned short *)(m + 0x34) |= 1;
    }
    rp = rot;
    if (((unsigned char *)d)[0xA1] == 0) {
        AttachManipulator(m, 0, d + 0xA0);
    }
    *(float *)(d + 0x110) = FastAddRots(*(float *)(d + 0x110), D_0015EE6C_d * 1.5707964f);
    func_L00_0025AFA8(d + 0xB0, d + 0x110);
    switch (((unsigned char *)m)[0x20]) {
    case 0:
        clear_u64_value(d + 0x110);
        if (*(int *)(d + 0x80) == -1) {
            qcopy(d + 0x60, m + 0x10);
            qcopy(d + 0x70, m + 0x40);
            m[0x20] = 4;
            *(int *)(d + 0x124) = 1;
        } else {
            *(int *)(d + 0x100) = -1;
            *(short *)(d + 0xE0) = -1;
            func_L08_002DD4F8(m);
            m[0x20] = 2;
            ((unsigned char *)m)[0x30] = 0xFF;
        }
        break;
    case 2: {
        char *q = D_0013E633 + 0xE1D;
        if (*(char **)(q + 0x2FC) == m) {
            if (D_L08_00179C90[0] == 0 && D_L08_00179C90[9] == -1) {
                qcopy(tgt, q + 0x80);
                func_L00_00262DF0_i(*(int *)(d + 0x8C), tgt, 0.5f, tgt);
                if (FastVecDist(q + 0x80, tgt) < 0.001f) {
                    func_L08_002DDB68(m);
                    if ((D_0013A5E0_d[0x2604 / 4] & 0x10) && *(short *)(q + 0x30E) == 0 && D_L08_0015F674 == 10) {
                        m[0x20] = 3;
                    }
                }
            }
        } else {
            func_L08_002DD4F8(m);
        }
        break;
    }
    case 3: {
        char *q = D_0013E633 + 0xE1D;
        *(short *)(q + 0x1F2) = 5;
        *(short *)(q + 0x1F4) = 5;
        *(short *)(q + 0x22DA) = *(unsigned short *)(d + 0x8C);
        if (func_L08_002DD9C0(m)) {
            func_L08_002DD4F8(m);
            m[0x20] = 2;
        }
        break;
    }
    }
    func_L08_002DD818(m);
    if (*(int *)(d + 0x8C) != -1) {
        func_L08_002DD440(m);
    }
    FastVecSub(vec, m + 0x10, pos);
    func_L00_002617B0(d + 0x20, vec, rp, m + 0x40);
}
extern int D_L08_001B0FB0[];
extern char D_L08_001DB540[];
extern void func_001F9EC0(void *, void *, void *);
extern void func_001F9BD8(void *, void *, void *);

// Transforms eight vectors of the current table entry by the moby's matrix.
void func_L08_002DD440(char *moby) {
    char *data = *(char **)(moby + 0x78);
    int *t = (int *)D_L08_001B0FB0[*(int *)(data + 0x8C)];
    if (*t == 8) {
        char *q = D_L08_001DB540;
        char *mat = moby + 0xC0;
        char *pos = moby + 0x10;
        char *p = (char *)t + 0x10;
        int i;
        for (i = 7; i >= 0; i--) {
            func_001F9EC0(p, q, mat);
            q += 0x10;
            FastVecAdd(p, p, pos);
            p += 0x10;
        }
    }
}
typedef struct {
    int count;
    int pad[3];
    float e[1][4];
} Route_2dd4f8;
extern Route_2dd4f8 *D_L08_001B0FB0_r[] __asm__("D_L08_001B0FB0");
extern char D_0014171B_r[] __asm__("D_0014171B") NOT_SDA;
extern int D_0015EE84_r __asm__("D_0015EE84") MACRO_ADDR;
extern int D_L08_0015F6B0_r __asm__("D_L08_0015F6B0") MACRO_ADDR;
extern float func_001F9D48(void *, void *);

/* Platform route choice: picks whichever of its three routes is nearest the player (end of route a, or
 * the start of b or c), and on a change starts along it; on route a it skips to b/c when the current
 * frame's route flags say so, and hides when far from the player. */
void func_L08_002DD4F8(char *m) {
    char *d = *(char **)(m + 0x78);
    char *pl = D_0013E633 + 0xE9D;
    Route_2dd4f8 *a = D_L08_001B0FB0_r[*(int *)(d + 0x88)];
    Route_2dd4f8 *b = D_L08_001B0FB0_r[*(int *)(d + 0x80)];
    Route_2dd4f8 *c = D_L08_001B0FB0_r[*(int *)(d + 0x84)];
    float d0 = FastVecDist(pl, (char *)a + (a->count << 4));
    float d1 = FastVecDist(pl, b->e[0]);
    float d2 = FastVecDist(pl, c->e[0]);
    int sel = 0;
    float y;
    if (d1 < d0) {
        d0 = d1;
        sel = 1;
    }
    if (d2 < d0) sel = 3;
    if (*(int *)(d + 0x100) == sel) return;
    *(int *)(d + 0x100) = sel;
    *(int *)(d + 0xE4) = 0;
    *(float *)(d + 0x104) = 1.0f;
    m[0x31] = 1;
    *(unsigned short *)(m + 0x34) &= 0xFFFE;
    *(int *)(d + 0x124) = 1;
    *(int *)(m + 0x94) = *(int *)(*(char **)(m + 0x24) + 0x10);
    switch (sel) {
    case 0: {
        int n = a->count;
        unsigned char *t;
        int f94, f98;
        int fr;
        qcopy(d + 0x60, (char *)((n << 4) + (int)a));
        y = func_L00_001FF860(*(float *)((char *)a + ((n - 2) << 4) + 0x10) - *(float *)(d + 0x60),
                              *(float *)((char *)a + ((n - 2) << 4) + 0x14) - *(float *)(d + 0x64));
        fr = D_0015EE84_r << 4;
        t = (unsigned char *)(D_0014171B_r + 0xAA35);
        *(float *)(d + 0x78) = y;
        *(float *)(d + 0xE4) = 1.0f;
        *(int *)(d + 0x104) = 0;
        f94 = t[*(int *)(d + 0x94) + fr] == 0xFF;
        f98 = t[*(int *)(d + 0x98) + fr] == 0xFF;
        if (f98) {
            *(Route_2dd4f8 **)(d + 0x120) = c;
        } else if (f94) {
            *(Route_2dd4f8 **)(d + 0x120) = b;
        } else if (32.0f < func_001F9D48(m + 0x10, pl) || D_L08_0015F6B0_r < 5) {
            m[0x31] = 0;
            *(unsigned short *)(m + 0x34) |= 1;
            *(int *)(d + 0x124) = 0;
            *(int *)(m + 0x94) = 0;
        }
        return;
    }
    case 1:
        qcopy(d + 0x60, b->e[0]);
        y = func_L00_001FF860(b->e[1][0] - *(float *)(d + 0x60), b->e[1][1] - *(float *)(d + 0x64));
        *(Route_2dd4f8 **)(d + 0x120) = b;
        break;
    case 2:
        qcopy(d + 0x60, a->e[0]);
        y = func_L00_001FF860(a->e[1][0] - *(float *)(d + 0x60), a->e[1][1] - *(float *)(d + 0x64));
        *(Route_2dd4f8 **)(d + 0x120) = a;
        break;
    case 3:
        qcopy(d + 0x60, c->e[0]);
        y = func_L00_001FF860(c->e[1][0] - *(float *)(d + 0x60), c->e[1][1] - *(float *)(d + 0x64));
        *(Route_2dd4f8 **)(d + 0x120) = c;
        break;
    default:
        return;
    }
    *(float *)(d + 0x78) = y;
}
extern float func_001FA748(float, float);
extern float D_0015EE6C MACRO_ADDR;
extern float func_001F9FA8(float);
void func_L08_002DD818(char *moby) {
    char *d = *(char **)(moby + 0x78);
    float s, t, w;
    qcopy(moby + 0x10, d + 0x60);
    qcopy(moby + 0x40, d + 0x70);
    s = FastAddRots(*(float *)(d + 0xEC), D_0015EE6C * 2.0943951f);
    *(float *)(d + 0xEC) = s;
    t = FastSin(s);
    w = D_0015EE6C * 1.6929693f;
    *(float *)(moby + 0x18) += t * 0.25f;
    s = FastAddRots(*(float *)(d + 0xF0), w);
    *(float *)(d + 0xF0) = s;
    t = FastAddRots(*(float *)(moby + 0x44), FastSin(s) * 0.08726646f);
    w = D_0015EE6C * 0.9250245f;
    *(float *)(moby + 0x44) = t;
    s = FastAddRots(*(float *)(d + 0xF4), w);
    *(float *)(d + 0xF4) = s;
    *(float *)(moby + 0x40) = FastAddRots(*(float *)(moby + 0x40), FastSin(s) * 0.08726646f);
    if (*(float *)(moby + 0x40) > 0.17453292f) *(float *)(moby + 0x40) = 0.17453292f;
    else if (*(float *)(moby + 0x40) < -0.17453292f) *(float *)(moby + 0x40) = -0.17453292f;
    if (*(float *)(moby + 0x44) > 0.17453292f) *(float *)(moby + 0x44) = 0.17453292f;
    else if (*(float *)(moby + 0x44) < -0.17453292f) *(float *)(moby + 0x44) = -0.17453292f;
}
extern float func_00214D88(float *, float *, float, float, float, float);
extern void func_00215CA8(int *, int, void *, float *, int, float);
extern float func_001F9B88(float);
extern float D_0015EE70 MACRO_ADDR;

/* Per-frame update: ease the angle and position fields toward their targets. */
int func_L08_002DD9C0(char *m) {
    char *d = *(char **)(m + 0x78);
    int *path;
    float a = D_0015EE70 * 0.1f;
    float b = D_0015EE6C * 0.08f;
    path = *(int **)(d + 0x120);
    func_00214D88((float *)(d + 0xE4), (float *)(d + 0xE8), *(float *)(d + 0x104), a, a, b);
    *(float *)(d + 0x110) = FastAddRots(*(float *)(d + 0x110), *(float *)(d + 0xE8) * 50.0f);
    func_00215CA8(path, 0, d + 0x60, (float *)(d + 0x70), 0, *(float *)(d + 0xE4) * (float)(*path - 1));
    *(int *)(d + 0x74) = 0;
    if (FastAbsF(*(float *)(d + 0xE4) - *(float *)(d + 0x104)) < 0.2f) {
        func_00214D88((float *)(d + 0x108), (float *)(d + 0x10C), 3.14159f, D_0015EE70 * 2.0943952f, D_0015EE70 * 2.0943952f, D_0015EE6C * 6.2831855f);
    } else {
        *(int *)(d + 0x108) = 0;
    }
    if (*(float *)(d + 0x104) == 0.0f) {
        *(float *)(d + 0x78) = FastAddRots(*(float *)(d + 0x78), 3.14159f);
    }
    *(float *)(d + 0x78) = FastAddRots(*(float *)(d + 0x78), *(float *)(d + 0x108));
    return *(float *)(d + 0xE4) == *(float *)(d + 0x104);
}
extern void func_00215F80(int, int);
extern int D_L08_001B0FB0[];

void func_L08_002DDB68(char *moby) {
    char *data = *(char **)(moby + 0x78);
    if (*(float *)(data + 0x104) > 0.9f) {
        try_set_help_message(0xA, 0x1F4D);
    } else if (*(int *)(data + 0x120) == D_L08_001B0FB0[*(int *)(data + 0x80)]) {
        try_set_help_message(0xA, 0x1F50);
    } else if (*(int *)(data + 0x120) == D_L08_001B0FB0[*(int *)(data + 0x88)]) {
        try_set_help_message(0xA, 0x1F4F);
    } else {
        try_set_help_message(0xA, 0x1F4E);
    }
}
extern char *func_0020D348(int);
extern int func_001F9850(int);
extern float func_002140F8(float, float);
extern float func_L00_001FF860(float, float);
extern void func_L00_00251E30(void *);
/* Spawns a moby of class 0x1A9 at a position, with a random spin and a heading from a vector. */
char *func_L08_002DDC18(char *src, char *pos, char *vec) {
    char *moby = CreateMoby(0x1A9);
    char *data;
    if (moby) {
        data = *(char **)(moby + 0x78);
        *(unsigned char *)(moby + 0x30) = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        moby[0x31] = 1;
        moby[0x20] = 1;
        *(char **)(data + 0x20) = src;
        *(int *)(data + 0x10) = scale_ticks(0x12C);
        *(float *)(data + 0x1C) = 1.0f;
        *(int *)(data + 0x14) = 0;
        qcopy(moby + 0x10, pos);
        qcopy(data, vec);
        *(float *)(moby + 0x40) = random_float_between(-180.0f, 180.0f) * 0.017453293f;
        *(float *)(moby + 0x48) = func_L00_001FF860(*(float *)vec, *(float *)(vec + 4)) + 1.5707964f;
        func_L00_00251E30(moby);
    }
    return moby;
}
INCLUDE_ASM("asm/overlays", func_L08_002DDD20);
typedef unsigned int Q46 __attribute__((mode(TI)));
typedef float V46[4] __attribute__((aligned(16)));
typedef struct M46 M46;
typedef struct D46 D46;
typedef struct { char pad0[0x10]; int animation; char pad14[0x10]; float scale; } Model46;
struct M46 {
    char pad0[0xC]; float distance; V46 position;
    unsigned char state,group,pad22[2]; Model46 *model;
    float pad28,scale; unsigned char pad30[2]; unsigned short flags;
    char pad34[0xC]; V46 rotation; char pad50[0x28]; D46 *data;
    char pad7C[0x18]; int animation; char pad98[0xE]; unsigned short class_id;
    char padA8[0x18]; V46 matrix[4];
};
struct D46 {
    char pad0[0x20]; V46 velocity; char pad30[0x10];
    float pitch,yaw,roll; M46 *target;
    int waypoint; signed char direction; char pad55[3]; int health; int pad5C;
    Route_2dd4f8 *path; int path_index; char pad68[0x18];
    float yaw_velocity; int pad84,effect_path; float activation_range;
    int persistent,timer; float speed;
};
typedef struct { int waypoint; signed char direction; char pad5[0xB]; Route_2dd4f8 *path; } RouteState46;
typedef struct { char pad0[0x2C]; unsigned char active; } Persistent46;
extern char D_0013D355[] NOT_SDA;
typedef struct { char pad0[0x140]; float x,y,z,w; } Camera46;
extern Camera46 D_L08_00167500;
extern unsigned int D_L08_0016005C MACRO_ADDR;
extern float D_L08_00161A90 SDATA(D_L08_00161A90);
extern float D_L08_00161A94 SDATA(D_L08_00161A94);
extern float D_L08_00161A98 SDATA(D_L08_00161A98);
extern float D_L08_00161A9C SDATA(D_L08_00161A9C);
extern float D_L08_00161AA4 SDATA(D_L08_00161AA4);
extern int D_L08_00161AB0 SDATA(D_L08_00161AB0);
extern float D_L08_00161AB4 SDATA(D_L08_00161AB4);
extern float D_L08_00161AB8 SDATA(D_L08_00161AB8);
extern int D_L08_00161ABC SDATA(D_L08_00161ABC);
extern int D_L08_00161AC0 SDATA(D_L08_00161AC0);
extern void *func_L00_0025B478(void*,int,int);
extern void func_0020D678(void*);
extern float func_001F9CE8(void*);
extern int func_001FA898_r(float) __asm__("func_001FA898");
extern void func_L00_0025F4A8(void *,void *,void *,float,float,int,int,int,float,float,float,float,int,float,int,int,int,int);
extern int func_0022ED80(int,int,void*);
extern void func_L00_00260108(void*,void*,int,float,float);
extern void func_L00_00263D68(void*,void*,float,float,float);
extern void func_L00_002607A8(void*,float);
extern float func_00214158(void),func_001F9F90(float);
extern void func_L00_001FF4B0(void*,void*,float);
extern float func_00214D28(float*,float,float);
extern void func_L00_0026A7F8(void*,void*,int,int,int,int,int,int);
extern int timer46(int*) __asm__("func_001F9908");
extern void func_L00_002592B0(void*,void*,float,float,float,float);
extern int func_L00_00258BC8(int,int);
extern void func_L05_00319B58(void*,int,void*,void*,int);
extern void func_L08_002DF8A0(void*,int,int,int);
extern float func_L00_0025CC58(float*,int,float,float);
extern void func_00215C00(void*,float,float,float);
extern int func_L00_001F39B0(void*,int,int,void*,int);

/* Rocket guidance, route traversal, launch effects, and destruction. */
void func_L08_002DE738(M46 *m) {
    V46 target,delta,accel,effect,aux;
    D46 *d=m->data;
    if (func_L00_0025B478(m,0x210000,0) && m->state!=4) {
        func_0022ED80(0,0,m);
        func_L00_00260108(m,m->position,-1,0.5f,13.0f);
        DeleteMoby(m);
        return;
    }
    switch(m->state) {
    case 0: {
        char *persistence_base=D_0013D355+0x13B;
        Persistent46 *state=(Persistent46*)(persistence_base+d->persistent);
        if (state->active) {
            short *p=D_L08_001AC340[m->group];
            do { DeleteMoby(D_L08_00160058+((*(unsigned short*)p&0x7FFF)<<8)); } while (*p++>=-1);
            return;
        }
        if (!d->persistent) d->timer=scale_ticks(10);
        d->path=D_L08_001B0FB0_r[d->path_index];
        qcopy(m->position,d->path->e[0]);
        d->waypoint=1; m->state=3; m->animation=0; m->flags=0;
        return;
    }
    case 1: {
        D46 *t=d->target->data;
        int life,size0,size1;
        float yaw,pitch,radius,angle;
        m->rotation[0]=FastAddRots(m->rotation[0],D_0015EE6C*6.2831855f);
        qcopy(target,d->target->position); target[2]+=5.0f;
        yaw=func_L00_001FF860(m->position[0]-target[0],m->position[1]-target[1]);
        pitch=func_L00_001FF860(func_001F9D48(target,m->position),m->position[2]-target[2]);
        func_L00_00263D68(target,target,d->roll,d->yaw,d->pitch);
        FastVecSub(delta,target,m->position);
        func_L00_002607A8(delta,t->speed*D_0015EE6C);
        FastVecSub(accel,delta,d->velocity);
        func_L00_002607A8(accel,D_L08_00161A94*D_0015EE70);
        FastVecAdd(d->velocity,d->velocity,accel);
        FastVecAdd(m->position,m->position,d->velocity);
        m->rotation[1]=-func_L00_001FF860(func_001F9CE8(d->velocity),d->velocity[2]);
        m->rotation[2]=func_L00_001FF860(d->velocity[0],d->velocity[1]);
        if (FastDiffRots(yaw,d->yaw)<0.08726646f && FastDiffRots(pitch,d->pitch)<0.08726646f) m->state=2;
        radius=random_float_between(0.0f,D_L08_00161AA4)*D_0015EE6C;
        angle=random_angle_radians();
        func_L00_001FF4B0(effect,m->matrix[2],radius*FastCos(angle));
        func_L00_001FF4B0(aux,m->matrix[1],radius*FastSin(angle));
        FastVecAdd(effect,effect,aux); qcopy(aux,aux);
        effect[3]=D_L08_00161AB4; aux[3]=D_L08_00161AB8;
        life=scale_ticks(D_L08_00161AB0);
        size0=func_001FA898_r(D_L08_00161AB4); size1=func_001FA898_r(D_L08_00161AB8);
        func_L00_0026A7F8(m->position,effect,D_L08_00161ABC,D_L08_00161AC0,life,size0,size1,1);
        return;
    }
    case 2: {
        D46 *t=d->target->data;
        int life,size0,size1;
        float scale,radius,angle;
        m->rotation[0]=FastAddRots(m->rotation[0],D_0015EE6C*6.2831855f);
        scale=m->model->scale*3.0f;
        func_00214D28(&m->scale,scale,m->model->scale/(float)scale_ticks(180));
        qcopy(target,d->target->position); target[2]+=5.0f;
        FastVecSub(delta,target,m->position);
        func_L00_002607A8(delta,t->speed*D_0015EE6C);
        FastVecSub(accel,delta,d->velocity);
        func_L00_002607A8(accel,D_L08_00161A94*4.0f*D_0015EE70);
        FastVecAdd(d->velocity,d->velocity,accel);
        FastVecAdd(m->position,m->position,d->velocity);
        m->rotation[1]=-func_L00_001FF860(func_001F9CE8(d->velocity),d->velocity[2]);
        m->rotation[2]=func_L00_001FF860(d->velocity[0],d->velocity[1]);
        if (FastVecDist(m->position,d->target->position)<D_L08_00161A9C) {
            t->health-=60; clear_u64_value(d->velocity); func_0022ED80(0,0,m); m->state=6;
        }
        radius=random_float_between(0.0f,D_L08_00161AA4)*D_0015EE6C;
        angle=random_angle_radians();
        func_L00_001FF4B0(effect,m->matrix[2],radius*FastCos(angle));
        func_L00_001FF4B0(aux,m->matrix[1],radius*FastSin(angle));
        FastVecAdd(effect,effect,aux); qcopy(aux,aux);
        effect[3]=D_L08_00161AB4; aux[3]=D_L08_00161AB8;
        life=scale_ticks(D_L08_00161AB0);
        size0=func_001FA898_r(D_L08_00161AB4); size1=func_001FA898_r(D_L08_00161AB8);
        func_L00_0026A7F8(m->position,effect,D_L08_00161ABC,D_L08_00161AC0,life,size0,size1,1);
        return;
    }
    case 3:
        if (D_L08_0015F6A8) return;
        if (FastVecDist(D_0013E633+0xE9D,(char*)d->path+(d->path->count<<4))<d->activation_range && timer46(&d->timer)) {
            m->flags=0x40; m->state=4; m->animation=m->model->animation;
            m->rotation[2]=func_L00_001FF860(d->path->e[1][0]-m->position[0],d->path->e[1][1]-m->position[1]);
            func_0022ED80(1,0,m);
        }
        return;
    case 4: {
        RouteState46 *route;
        int next;
        float yaw;
        if (D_L08_0015F6A8) return;
        route=(RouteState46*)&d->waypoint;
        next=(route->waypoint+route->path->count+route->direction)%route->path->count;
        yaw=func_L00_001FF860(*(float*)((char*)route->path+(next<<4)+0x10)-m->position[0],*(float*)((char*)route->path+(next<<4)+0x14)-m->position[1]);
        func_L00_002592B0(m,&d->yaw_velocity,yaw,0.1f,1.3f,1.0f);
        m->rotation[1]=func_L00_001FF860(func_001F9D48(route->path->e[next],m->position),m->position[2]-route->path->e[next][2]);
        qcopy_nc(target,route->path->e[next]);
        if (route->waypoint!=route->path->count-1) {
            int life0,life1,size1;
            FastVecSub(delta,target,m->position);
            func_L00_001FF4B0(delta,delta,D_L08_00161A98*D_0015EE6C);
            FastVecAdd(m->position,m->position,delta);
            if (FastVecDist(m->position,target)<0.5f) route->waypoint=next;
            *(Q46*)effect=(Q46)0;
            effect[0]=random_float_between(-1.0f,1.0f); effect[1]=random_float_between(-1.0f,1.0f); effect[2]=random_float_between(-1.0f,1.0f);
            *(Q46*)accel=*(Q46*)effect; func_L00_002607A8(accel,D_0015EE6C+D_0015EE6C);
            life0=scale_ticks(rand_range(30,45));
            size1=rand_range(40,70);
            func_L00_0026A7F8(m->position,accel,0x6F00AFFF,0xFF,life0,40,size1,1);
            *(Q46*)aux=(Q46)0;
            aux[0]=random_float_between(-1.0f,1.0f); aux[1]=random_float_between(-1.0f,1.0f); aux[2]=random_float_between(-1.0f,1.0f);
            *(Q46*)effect=*(Q46*)aux; func_L00_002607A8(effect,D_0015EE6C+D_0015EE6C);
            life1=scale_ticks(rand_range(60,120));
            size1=rand_range(100,150);
            func_L00_0026A7F8(m->position,effect,0x1FFFFFFF,0x4F4F4F,life1,40,size1,0);
            return;
        } else {
            short *p=D_L08_001AC340[m->group];
            long special=0;
            int index;
            M46 *other;
            if (!p) return;
            index=*(unsigned short*)p&0x7FFF;
            other=(M46*)(D_L08_00160058+(index<<8));
            ((Persistent46*)(D_0013D355+d->persistent+0x13B))->active=1;
            linked_object:
                if (other->state<0x7F && other!=m) {
                    unsigned short cls=other->class_id;
                    if ((unsigned int)(cls-0x223)<6) {
                        clear_u64_value(accel);
                        switch ((short)(other->class_id-0x223)) {
                        case 0: *(Q46*)aux=(Q46)0; aux[0]=-3.331f; aux[1]=3.331f; aux[2]=0.275f; qcopy(effect,aux); break;
                        case 1: *(Q46*)aux=(Q46)0; aux[0]=-6.0f; aux[1]=6.0f; aux[2]=-1.772f; qcopy(effect,aux); break;
                        case 2: *(Q46*)aux=(Q46)0; aux[0]=-2.0f; aux[1]=-1.152f; aux[2]=-1.772f; qcopy(effect,aux); break;
                        case 3: *(Q46*)aux=(Q46)0; aux[2]=0.975f; qcopy(effect,aux); break;
                        case 4: *(Q46*)aux=(Q46)0; aux[1]=-1.665f; aux[2]=0.642f; qcopy(effect,aux); break;
                        case 5: *(Q46*)aux=(Q46)0; qcopy(effect,aux); break;
                        }
                        if (other->distance>1500.0f) DeleteMoby(other);
                        else {
                            float a,b,lo,hi,angle_delta;
                            float *launch_offset;
                            FastVecSub(accel,other->position,m->position); accel[2]=0.0f;
                            func_L00_001FF4B0(accel,accel,D_0015EE6C*12.0f);
                            accel[2]=random_float_between(D_0015EE6C*8.0f,D_0015EE6C*12.0f);
                            other->animation=0;
                            a=func_L00_001FF860(accel[0],accel[1]);
                            b=func_L00_001FF860(D_L08_00167500.x-m->position[0],D_L08_00167500.y-m->position[1]);
                            angle_delta=FastDiffRots(a,b);
                            launch_offset=effect;
                            if (angle_delta<0.7853982f) { lo=10.0f; hi=20.0f; }
                            else { lo=60.0f; hi=90.0f; }
                            func_L05_00319B58(other,(int)m,accel,launch_offset,func_001FA898_r(random_float_between(lo,hi)));
                        }
                    } else if ((short)cls==0x1A8) {
                        special=1; clear_u64_value(accel);
                        func_L00_0025F4A8(other,accel,other->position,0.0f,0.0f,50,60,60,12.0f,8.0f,9.0f,1.0f,-1,15.0f,1,1,-1,0);
                        DeleteMoby(other);
                    }
                }
                if (*p++>=-1) {
                    index=*(unsigned short*)p&0x7FFF;
                    other=(M46*)(D_L08_00160058+(index<<8));
                    goto linked_object;
                }
            if (special) func_L08_002DF8A0(m,d->effect_path,30,1);
            else func_L08_002DF8A0(m,d->effect_path,30,0);
            func_0022ED80(2,0,m); m->state=6;
        }
        return;
    }
    case 5:
        func_L00_0025CC58(&m->rotation[2],0,d->yaw,D_0015EE6C*0.5235988f);
        func_L00_0025CC58(&m->rotation[1],0,-d->pitch,D_0015EE6C*0.5235988f);
        m->rotation[0]=FastAddRots(m->rotation[0],D_0015EE6C*6.2831855f);
        func_00215C00(d->velocity,(D_L08_00161A90+D_L08_00161A90)*D_0015EE6C,m->rotation[2],-m->rotation[1]);
        FastVecAdd(m->position,m->position,d->velocity);
        if (func_L00_001F39B0(m->position,0x400,2,m,0) || m->position[0]<5.0f || m->position[0]>500.0f || m->position[1]<5.0f || m->position[1]>500.0f || m->position[2]<5.0f || m->position[2]>500.0f || FastVecDist(D_0013E633+0xE9D,m->position)<16.0f) m->state=6;
        return;
    case 6:
        if (D_L08_0016005C<(unsigned int)m) func_L00_0025F4A8(m,d->velocity,m->position,0.0f,0.0f,15,10,10,3.0f,2.0f,9.0f,1.0f,-1,15.0f,1,1,-1,0);
        DeleteMoby(m);
        break;
    default: break;
    }
}
LINKER_REMNANT("asm/overlays", func_L08_002DF750);
INCLUDE_ASM("asm/overlays", func_L08_002DF758);
INCLUDE_ASM("asm/overlays", func_L08_002DF8A0);
extern float func_L00_00258C80(float lo, float hi);
extern float func_001F9CE8(void *);
extern int func_L00_001F10E0(float, void *, int, void *);
extern void func_L00_0025F4A8(void *, void *, void *, float, float, int, int, int, float, float, float, float, int, float, int, int, int, int);
extern void func_0020D678(void *);
extern void *func_L00_0025B478(void *, int, int);
extern int func_0022EE28(int, int, int);
extern void func_L00_00264DB8(int, int);
extern void func_L08_002E0008(char *m, char *pos);
extern short D_L08_00161AD4;
extern int D_001414D4;
extern unsigned char D_0013D510[];

/* Update function: switch on the state byte at +0x20. State 0 reads the table D_L08_001B0FB0[*data] (deleting
 * the moby if the index is -1), 1 steps along it, 2 falls under gravity and deletes the moby below z = 10.0
 * or on a hit. */
void func_L08_002DFBC0(char *m) {
    float a[4];
    float b[4];
    char *d = *(char **)(m + 0x78);
    char *pos = m + 0x10;
    int *t;
    qcopy(a, pos);
    t = (int *)D_L08_001B0FB0[*(int *)d];
    switch (*(unsigned char *)(m + 0x20)) {
    case 0:
        if (*(int *)d == -1) {
            DeleteMoby(m);
            return;
        }
        {
            float l0 = FastVecDist((char *)t + 0x10, (char *)t + 0x20);
            FastVecDist((char *)t + 0x10, (char *)t + (*t << 4));
            *(float *)(d + 8) = *(float *)&D_L08_00161AD4 * D_0015EE6C / l0;
            *(float *)(d + 4) = *(float *)(d + 4) * (float)*t;
            *(float *)(d + 0xC) = randf_sym(0.0f, 5.0f);
        }
        m[0x20] = 1;
        *(unsigned char *)(m + 0x30) = 0xFF;
    case 1: {
        float f;
        func_00215CA8(t, 1, m + 0x10, (float *)(m + 0x40), 0, *(float *)(d + 4));
        *(float *)(m + 0x44) = *(float *)(m + 0x44) * 0.5f;
        *(float *)(m + 0x18) = *(float *)(m + 0x18) + *(float *)(d + 0xC);
        *(float *)(d + 4) = *(float *)(d + 4) + *(float *)(d + 8);
        f = (float)*t;
        if (f < *(float *)(d + 4)) {
            *(float *)(d + 4) = *(float *)(d + 4) - f;
        }
        break;
    }
    case 2: {
        float c15 = 15.0f;
        float c10 = 10.0f;
        float dd;
        float g;
        char *v = d + 0x10;
        g = D_0015EE6C * 7.3303828f;
        *(float *)(d + 0x18) = *(float *)(d + 0x18) - D_0015EE70 * c15;
        dd = FastAddRots(*(float *)(m + 0x40), g);
        *(float *)(m + 0x40) = *(float *)(m + 0x40) + dd;
        *(float *)(m + 0x44) = -func_L00_001FF860(func_001F9CE8(v), *(float *)(d + 0x18));
        FastVecAdd(pos, pos, v);
        if (*(float *)(m + 0x18) < c10) {
            DeleteMoby(m);
            return;
        }
        if (coll_sphere(1.25f, pos, 0, m)) {
            func_L00_0025F4A8(m, v, pos, 0.0f, 0.0f, 0x14, 0x28, 0x10, c10, 5.0f, 9.0f, 1.0f, -1, c15, 1, 1, -1, 0);
            DeleteMoby(m);
            return;
        }
        break;
    }
    default:
        break;
    }
    if (*(float *)(m + 0x10) < 4.0f || *(float *)(m + 0x14) < 4.0f || *(float *)(m + 0x18) < 4.0f) {
        *(int *)(m + 0x94) = 0;
    } else {
        *(int *)(m + 0x94) = *(int *)(*(char **)(m + 0x24) + 0x10);
    }
    if (func_L00_0025B478(m, 0x10000, 0) != 0 && *(unsigned char *)(m + 0x20) != 2) {
        if (D_001414D4 == 0x32 && gSkillPoints[0xC] == 0) {
            gSkillPoints[0xC] = 1;
            func_0022EE28(1, 0, 0);
            ShowBanner(0x53DB, -1);
        }
        FastVecSub(b, m + 0x10, a);
        qcopy(d + 0x10, b);
        *(float *)(d + 0x18) = *(float *)(d + 0x18) + (D_0015EE6C + D_0015EE6C);
        func_L00_0025F4A8(m, b, m + 0x10, 0.0f, 0.0f, 0x14, 0x28, 0x10, 10.0f, 5.0f, 9.0f, 1.0f, -1, 15.0f, 1, 1, -1, 0);
        m[0x20] = 2;
    }
    *(unsigned char *)(m + 0xA4) = 0xFF;
    if (*(unsigned char *)(m + 0x31) != 0) {
        func_L08_002E0008(m, (char *)a);
    }
}
typedef int u128 __attribute__((mode(TI)));
extern void func_001F9BF0(void *dst, void *a, void *b);
extern void func_001F9C30(void *, void *, float);
extern void func_L00_00258DB0(float *, float, float);
extern int func_001FA8A8(int, int, float);
extern float func_001F9878(float);
extern int func_001FA898_r(float) __asm__("func_001FA898");
extern char *func_00219780(void *, void *, void *, int, int, int, int, int, int);
extern short D_L08_00161AD8;
extern short D_L08_00161ADC;
extern short D_L08_00161AE0;
extern short D_L08_00161AE4;
extern short D_L08_00161AE8;
extern short D_L08_00161AEC;
extern short D_L08_00161AF0;
extern short D_L08_00161AF4;
extern short D_L08_00161AF8;
extern short D_L08_00161AFC;
extern short D_L08_00161B00;
extern short D_L08_00161B04;
extern short D_L08_00161B08;
extern short D_L08_00161B0C;
extern short D_L08_00161B10;

// Spawns a debris moby: builds position/velocity vectors with random ranges and creates it.
void func_L08_002E0008(char *m, char *pos) {
    float v10[4];
    float v20[4];
    float v30[4];
    float v40[4];
    float v50[4];
    float v60[4];
    int a, b, c, d, e;
    char *r;
    FastVecSub(v30, m + 0x10, pos);
    *(u128 *)v60 = 0;
    v60[0] = -2.3f;
    v60[2] = 0.3f;
    func_001F9EC0(v50, v60, m + 0xC0);
    FastVecAdd(v50, v50, m + 0x10);
    FastVecScale(v10, v30, *(float *)&D_L08_00161AD8);
    FastVecScale(v20, v30, *(float *)&D_L08_00161ADC);
    rand_vec(v40, 0.0f, *(float *)&D_L08_00161AE0 * D_0015EE6C);
    FastVecAdd(v20, v20, v40);
    v10[3] = random_float_between(*(float *)&D_L08_00161AF4, *(float *)&D_L08_00161AF8);
    v20[3] = random_float_between(*(float *)&D_L08_00161AFC, *(float *)&D_L08_00161B00);
    a = FastTweenColor(*(int *)&D_L08_00161B04, *(int *)&D_L08_00161B08, random_float_between(0.0f, 1.0f));
    b = FastTweenColor(*(int *)&D_L08_00161B0C, *(int *)&D_L08_00161B10, random_float_between(0.0f, 1.0f));
    c = func_001FA898_r(func_001F9878((float)*(int *)&D_L08_00161AE4 * random_float_between(0.0f, 1.0f) + 1.0f));
    d = func_001FA898_r(func_001F9878((float)*(int *)&D_L08_00161AE8 * (random_float_between(-*(float *)&D_L08_00161AF0, *(float *)&D_L08_00161AF0) + 1.0f)));
    e = func_001FA898_r(func_001F9878((float)*(int *)&D_L08_00161AEC * (random_float_between(-*(float *)&D_L08_00161AF0, *(float *)&D_L08_00161AF0) + 1.0f)));
    r = func_00219780(v50, v10, v20, a, b, c, d, e, -1);
    if (r != 0) {
        r[9] = func_001FA898_r(8.0f) - 0x70;
    }
}
