/* Shared code following help; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L15_001FFED0);
extern unsigned char D_0013E633[];
extern unsigned char D_0013E15A[];
extern void func_L00_00207948(int, int);

/* Show the indexed help prompt when its flag and message are active. */
void func_L15_00200D20(void) {
    unsigned char *base = D_0013E633 + 0xE1D;
    int index = *(int *)(base + 0x10B8);
    if (index >= 0 && *(D_0013E15A + 0x4C6 + index) != 0) {
        int first = *(int *)(base + 0x1090);
        if (first != 0) {
            func_L00_00207948(first, *(int *)(base + 0x2080));
        }
    }
}
extern void func_L00_00263B78(float, float, char *, float *, float *);
extern void func_001F9EC0(void *, void *, void *);
extern void func_001FA218(float *, float *);
extern void func_001F9EE8(void *, void *, void *);
extern void func_001F9BD8(void *, void *, void *);
extern float D_0015EE6C MACRO_ADDR;
extern float D_L15_0017AD40;
extern void clear_u64_value(void *);
typedef int u128 __attribute__((mode(TI)));

// Per-frame update of the camera-attached moby position.
void func_L15_00200D70(void) {
    unsigned char *base = D_0013E633 + 0xE1D;
    if (*(int *)(base + 0x2084) == 0x6B && *(short *)(base + 0x8BC) == 0) {
        char *m;
        float v[4];
        float w[16];
        func_L00_00263B78(1.1f, D_0015EE6C * 5.2359877f, *(char **)(base + 0x2080),
                          (float *)(base + 0x6A8), (float *)(base + 0x6AC));
        m = *(char **)(base + 0x86C);
        if (m != 0) {
            char *cam;
            cam = *(char **)(base + 0x2080);
            qcopy(m + 0x10, cam + 0x10);
            *(u128 *)v = 0;
            v[2] = 0.21f;
            func_001F9EC0(v, v, cam + 0xC0);
            func_001FA218(w, &D_L15_0017AD40);
            func_001F9EE8(v, v, w);
            func_001F9BD8(*(char **)(base + 0x86C) + 0x10, *(char **)(base + 0x86C) + 0x10, v);
        }
    }
}
extern int D_L15_0015F6A8 MACRO_ADDR;
extern void func_001FFDA0(int arg0, int arg1);
extern void func_L00_00205B50(void);
extern void func_0020D678(void *);
extern void func_L00_00207220(void);
extern void func_L00_00232EA8(void);
extern void func_L15_00217348(int, int);

/* Reset the help prompt state and show the default message unless the level is in a special phase. */
void func_L15_002092E0(void) {
    unsigned char *base = D_0013E633 + 0xE1D;
    unsigned char *b;
    int p;
    void *q;
    char *m;
    if (base[0x20A4] == 2) {
        int v = *(short *)(base + 0x1634);
        if (v != -1) {
            func_001FFDA0(v, 0);
            *(short *)(base + 0x1634) = -1;
        }
    }
    func_L00_00205B50();
    b = D_0013E633 + 0xE1D;
    p = *(int *)(b + 0xA84);
    b[0x20A4] = 0;
    if (p != 0) {
        *(unsigned short *)(p + 0x34) &= 0xFFF9;
    }
    q = *(void **)(b + 0xA8C);
    *(int *)(b + 0xA84) = 0;
    if (q != 0) {
        DeleteMoby(q);
        *(int *)(b + 0xA8C) = 0;
    }
    func_L00_00207220();
    m = *(char **)(b + 0xA88);
    *(char **)(b + 0x2080) = m;
    qcopy(m + 0x10, b + 0x80);
    *(int *)(m + 0x98) = 0;
    *(float *)(b + 0xA94) = 1.0f;
    func_L00_00232EA8();
    if (*(int *)(b + 0x2084) != 100 || (D_L15_0015F6A8 != 2 && D_L15_0015F6A8 != 6)) {
        func_L15_00217348(0, 1);
    }
}
typedef struct {
    u8 pad0[0x80];
    f32 v80[4];
    u8 pad90[0x108];
    s32 i198;
    u8 pad19C[0x74];
    f32 v210[4];
    f32 f220;
    f32 f224;
    f32 f228;
    f32 f22C;
    f32 f230;
    f32 f234;
    f32 f238;
    u8 pad23C[0x1B];
    u8 b257;
    u8 pad258[0xA8];
    s32 i300;
    u8 pad304[0x11A];
    s16 s41E;
    s32 i420;
    u8 pad424[0x10];
    f32 f434;
    u8 pad438[0xEAA];
    u8 b12E2;
    u8 pad12E3;
    u8 b12E4;
    u8 pad12E5[0xD9F];
    s32 i2084;
    u8 pad2088[0x4];
    s32 i208C;
    u8 pad2090[0x4];
    s32 i2094;
    u8 pad2098[0xC];
    u8 b20A4;
} P_209450;
extern P_209450 D_0013F450;
extern f32 D_0013F670[];
extern f32 D_0015EE60 MACRO_ADDR;
extern f32 D_0015EE64 MACRO_ADDR;
extern f32 D_0015EE6C MACRO_ADDR;
f32 func_001F9D48(void *, void *);
f32 func_00214D28(f32, f32, f32 *);
void func_L00_0025C918(f32 *, f32 *, f32, f32, f32, f32);

/* Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/shared/ui_help_001ff938.c, FUN_L15_00209450. */
void func_L15_00209A88(void) {
    switch (D_0013F450.b20A4) {
    case 0:
        D_0013F450.f228 = 0.8f;
        D_0013F450.f22C = 0.7f;
        D_0013F450.f230 = 0.45f;
        break;
    case 2:
        D_0013F450.f228 = 5.25f;
        D_0013F450.f22C = 4.45f;
        D_0013F450.f230 = 3.75f;
        break;
    case 3:
        D_0013F450.f228 = 0.8f;
        D_0013F450.f22C = 0.6f;
        D_0013F450.f230 = 0.45f;
        break;
    }
    if (D_0013F450.i208C == 4) {
        if (D_0013F450.i198 > D_0013F450.i420 && D_0013F450.s41E == 0) D_0013F450.f22C = D_0013F450.f434;
    } else if (D_0013F450.i2084 == 6) {
        D_0013F450.f22C = 0.5f;
    } else if (D_0013F450.i2084 == 4) {
        D_0013F450.f228 = 0.35000002f;
    } else if ((u32)(D_0013F450.i208C - 0x11) < 2) {
        D_0013F450.f228 = 0.0f;
        D_0013F450.f22C = 0.0f;
    } else if (D_0013F450.i2084 == 0x7F) {
        D_0013F450.f230 = 0.8f;
    }
    if (!D_0013F450.b257 || D_0013F450.i2094 == 0x12 || D_0013F450.i208C == 0x11 || D_0013F450.b12E4 || func_001F9D48(D_0013F450.v210, D_0013F450.v80) > D_0013F450.f234 * 0.5f) {
        f32 *q = D_0013F670;
        P_209450 *b = (P_209450 *)((u8 *)q - 0x220);
        func_00214D28(b->f228, D_0015EE60 * 0.02f, q);
        func_00214D28(b->f22C, D_0015EE60 * 0.02f, q + 1);
        func_L00_0025C918(q + 5, q + 6, b->f230, D_0015EE64 * 0.02f, D_0015EE64 * 0.3f, D_0015EE6C * 4.0f);
    }
}
extern char D_0013F4D0[];
typedef struct { float x, y, z, w; } Vx __attribute__((aligned(16)));
extern char D_L15_001744DC[];
extern char D_L15_001744C0[];
extern float func_L00_00234250(float *v);
extern float func_001F9CE8(void *);
extern float func_001F9F90(float);
extern float func_001F9FA8(float);
extern void func_001F9C30(void *, void *, float);
extern int func_L00_001EFFF0(void *, void *, int, int, int);
extern int func_L00_001F3958(void);
extern float func_L00_001FF860(float, float);
extern void func_001252C0(void *, void *);
// Steers the hero's aim vectors toward the current target and snaps momentum to it when close enough.
void func_L15_0020A960(int arg) {
    float a[4] __attribute__((aligned(16)));
    float c[4] __attribute__((aligned(16)));
    float b[4] __attribute__((aligned(16)));
    float d[4] __attribute__((aligned(16)));
    char *base = D_0013E633 + 0xE1D;
    char *b2, *h1;
    float f2, f21, f20;
    int r18, r;
    if (*(short *)(base + 0x308) != 0) return;
    if (func_L00_00234250((float *)(base + 0xE0)) < D_0015EE6C * 0.1f) return;
    f2 = 0.37f;
    f21 = 0.5f;
    if ((unsigned)(*(int *)(base + 0x208C) - 0x11) < 2) {
        f2 = 0.0f;
        f21 = 0.7f;
    } else if (((unsigned char *)base)[0x20A4] == 2) {
        f2 = 1.5f;
        f21 = 5.0f;
    }
    base = D_0013E633 + 0xE9D;
    qcopy(a, base);
    a[2] = a[2] + f2;
    qcopy(b, base);
    b[2] = b[2] + f2 * 0.3f;
    if (arg != 0 || func_001F9CE8(base + 0x60) < 0.01f) {
        h1 = base - 0x80;
        c[0] = func_001F9F90(*(float *)(h1 + 0x98)) * f21;
        c[1] = func_001F9FA8(*(float *)(h1 + 0x98)) * f21;
        c[2] = 0.0f;
        d[0] = func_001F9F90(*(float *)(h1 + 0x98)) * f21 * 1.4f;
        d[1] = func_001F9FA8(*(float *)(h1 + 0x98)) * f21 * 1.4f;
        d[2] = 0.0f;
    } else {
        qcopy(c, base + 0x60);
        c[2] = 0.0f;
        func_001F9C30(c, c, f21 / func_001F9CE8(c));
        qcopy(d, c);
        func_001F9C30(d, d, 1.4f);
    }
    func_001F9BD8(c, c, a);
    r18 = -1;
    func_001F9BD8(d, d, b);
    b2 = D_0013E633 + 0xE1D;
    if (func_L00_001EFFF0(b, d, 4, *(int *)(b2 + 0x2080), 0)) {
        if (*(int *)D_L15_001744DC > 0) r18 = func_L00_001F3958();
    }
    f20 = 0.0f;
    b2 = D_0013E633 + 0xE1D;
    if (func_L00_001EFFF0(a, c, 4, *(int *)(b2 + 0x2080), 0)) {
        char *q = D_L15_001744C0;
        if (*(int *)(q + 0x1C) > 0)
            f20 = func_L00_001FF860(*(float *)(q + 0x48), func_001F9CE8(q + 0x40));
    }
    if (f20 >= 0.87266463f || r18 == 8 || r18 == 12) {
        float f;
        char *b3 = D_0013E633 + 0xE1D;
        char *q2 = D_L15_001744C0;
        *(float *)(q2 + 0x48) = 0.0f;
        *(int *)(b3 + 0x240) = *(int *)(q2 + 0x18);
        func_001252C0(q2 + 0x40, q2 + 0x40);
        f = -*(float *)(b3 + 0xE0) * *(float *)(q2 + 0x40)
            - *(float *)(b3 + 0xE4) * *(float *)(q2 + 0x44);
        if (0.0f < f) {
            func_001F9C30(q2 + 0x40, q2 + 0x40, f);
            func_001F9BD8(b3 + 0xE0, b3 + 0xE0, q2 + 0x40);
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L15_0020ADD8);
INCLUDE_ASM("asm/overlays", func_L15_00216568);
extern void func_L15_00217348(int, int);

/* Select the message associated with the current help mode. */
void func_L15_0021B2C8(void) {
    switch (D_0013E633[0x2EC1]) {
    case 0: func_L15_00217348(0, 1); break;
    case 2: func_L15_00217348(0x5A, 1); break;
    case 3: func_L15_00217348(0x53, 1); break;
    }
}
