/* Shared code following pad; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_00268760);
INCLUDE_ASM("asm/overlays", func_L00_002688A8);
INCLUDE_ASM("asm/overlays", func_L00_002689B0);
INCLUDE_ASM("asm/overlays", func_L00_00268A88);
