/* Shared code following partupd; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L05_002A1098);
INCLUDE_ASM("asm/overlays", func_L05_002A1170);
