/* Shared code following partupd; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

extern unsigned char *func_00218928(int);
extern int func_001FA898(float);
extern int func_002140B0(int);
extern float D_0015EE60 MACRO_ADDR;
extern unsigned char *D_L00_001B24B0;

/* Spawns a type 0x2C particle with position, velocity, colour and scale parameters.
   Adapted from Lombyte (MIT) for PAL: src/overlays/shared/rendering_002712b8.c, FUN_L00_002712b8. */
unsigned char *func_L00_00272158(void *pos, float *vec, int s, int a, int col, int n, float x, float y, float z, float w, float pw) {
    unsigned char *m = func_00218928(0x2C);
    if (m) {
        unsigned char *q;
        float d;
        float t;
        qcopy(m + 0x10, pos);
        *(int *)(m + 4) = (a << 24) | col;
        *(float *)(m + 0x1C) = pw;
        q = m + 0x20;
        m[9] = truncate_float_to_s32(4.0f) + 0x40;
        *(float *)(m + 0xC) = x;
        m[1] = 0;
        m[3] = 0x48;
        m[8] = random_integer_below(0xFF);
        m[2] = *D_L00_001B24B0;
        *(short *)(m + 0xA) = s;
        t = (float)n * D_0015EE60;
        *(float *)(q + 0) = vec[0];
        *(float *)(q + 4) = vec[1];
        *(float *)(q + 8) = vec[2];
        q[0x10] = truncate_float_to_s32(t);
        d = D_0015EE60;
        *(float *)(q + 0xC) = w;
        q[0x12] = col >> 8;
        *(float *)(q + 0x14) = y * d;
        q[0x11] = col;
        q[0x13] = col >> 16;
        *(short *)(q + 0x1C) = s;
        *(short *)(q + 0x1E) = a;
        *(float *)(q + 0x18) = (z - 1.0f) * d + 1.0f;
    }
    return m;
}
typedef struct { float f[4]; } Q __attribute__((aligned(16)));
extern int func_001F9938(void *);
extern void func_L00_002688A8(void *);
extern float func_001FA888(int);
extern void func_001F9BD8(void *, void *, void *);
extern void func_L00_001FF2C8(void *, void *, float);
extern void func_L00_001FF240(void *, void *, void *);
extern void func_001F9C30(void *, void *, float);
extern unsigned char D_0013E633[] NOT_SDA;

/* Per-frame update of a type 0x2C particle: fade colour, move and rotate its velocity.
   Adapted from Lombyte (MIT) for PAL: src/overlays/shared/rendering_002712b8.c, FUN_L00_00271450. */
void func_L00_002722F0(unsigned char *p) {
    float v[4];
    Q t[1];
    Q m[1];
    unsigned char *q;
    unsigned char *r;
    float a;
    int w;

    if (FastDecTimer(p + 0xA)) {
        KillPart(p);
    } else {
        q = p + 0x20;
        r = p + 0x10;
        a = func_001FA888(*(short *)(q + 0x1E));
        w = truncate_float_to_s32(a * ((float)*(short *)(p + 0xA) / func_001FA888(*(short *)(q + 0x1C))));
        w = (w << 24) | (q[0x13] << 16);
        w |= q[0x12] << 8;
        w |= q[0x11];
        *(int *)(p + 4) = w;
        v[0] = *(float *)(p + 0x20);
        v[1] = *(float *)(q + 4);
        v[2] = *(float *)(q + 8);
        *(int *)&v[3] = 0;
        FastVecAdd(r, r, v);
        t[0] = *(Q *)(D_0013E633 + 0xF5D);
        func_L00_001FF2C8(m, t, *(float *)(p + 0x1C));
        func_L00_001FF240(m, r, t);
        FastVecScale(m, D_0013E633 + 0xF5D + 0x150, *(float *)(q + 0xC));
        FastVecAdd(v, v, m);
        FastVecScale(v, v, *(float *)(q + 0x18));
        *(float *)(p + 0x20) = v[0];
        *(float *)(q + 4) = v[1];
        *(float *)(q + 8) = v[2];
        p[8] += q[0x10];
        *(float *)(p + 0xC) += *(float *)(q + 0x14);
    }
}
extern unsigned char *D_L00_001B24B4;
extern unsigned char *func_00218928(int);
extern int func_002140B0(int);
extern int func_001FA898(float);
extern int func_001160D8(void);
extern float func_00214158(void);
extern float func_002140F8(float, float);
extern float func_001F9F90(float);
extern float func_001F9FA8(float);

/* spawn a type-0x2D particle at a position with a velocity scale */
unsigned char *func_L00_00272488(void *pos, int b, int color, float f, float g) {
    unsigned char *r = func_00218928(0x2D);
    if (r != 0) {
        char *v;
        float t, u, s;
        int c;
        qcopy(r + 0x10, pos);
        if (color == -1) {
            c = ((random_integer_below(6) + 0x14) << 24) | 0x808080;
        } else {
            c = color;
        }
        v = (char *)r + 0x20;
        *(int *)(r + 4) = c;
        r[9] = truncate_float_to_s32(2.0f) + 0x20;
        r[3] = 0x48;
        r[1] = 1;
        r[2] = *D_L00_001B24B4;
        r[8] = func_001160D8();
        *(short *)(r + 0xA) = 4;
        *(float *)(r + 0xC) = f * 210000.0f;
        t = random_angle_radians();
        u = random_float_between(0.0015f, 0.0025f);
        *(float *)(r + 0x20) = FastCos(t) * u;
        s = FastSin(t) * u;
        *(int *)(v + 0x14) = b;
        *(float *)(v + 0x10) = g;
        *(int *)(v + 8) = 0;
        *(float *)(v + 4) = s;
    }
    return r;
}
extern void func_001F9BD8(void *, void *, void *);
extern void func_L00_002688A8(void *);
extern float func_001F9B88(float);

/* updates a type-45 particle: moves it, kills it when out of range or faded */
void func_L00_002725E8(char *m) {
    char *v = m + 0x20;
    int t;
    float *q = (float *)m;
    FastVecAdd(m + 0x10, m + 0x10, v);
    if (q[4] < 2.0f || q[4] > 1021.0f || q[5] < 2.0f || q[5] > 1021.0f || q[6] < 2.0f || q[6] > 1021.0f) {
        KillPart(m);
        return;
    }
    q[3] += *(float *)(v + 0x10);
    m[8]++;
    if (*(float **)(v + 0x14) != 0) {
        if (FastAbsF(q[6] - **(float **)(v + 0x14)) < 0.2f) {
            q[6] = **(float **)(v + 0x14) + 0.02f;
        }
    }
    t = *(unsigned short *)(m + 0xA) - 1;
    *(short *)(m + 0xA) = t;
    if ((t << 16) == 0) {
        *(unsigned short *)(m + 0xA) = 4;
        *(int *)(m + 4) += 0xFF000000;
    }
    if ((*(int *)(m + 4) & 0xFF000000) == 0) {
        KillPart(m);
    }
}
extern unsigned char *D_L00_001B24B8;

/* spawns a type-0x2E particle at a with velocity block b, link c, scale f and drag g */
unsigned char *func_L00_00272770(void *a, void *b, int c, float f, float g) {
    unsigned char *r = func_00218928(0x2E);
    if (r != 0) {
        char *v;
        qcopy(r + 0x10, a);
        v = (char *)r + 0x20;
        *(int *)(r + 4) = ((random_integer_below(10) + 0x26) << 24) | 0x808080;
        r[9] = truncate_float_to_s32(2.0f) + 0x20;
        r[3] = 0x48;
        r[1] = 1;
        r[2] = *D_L00_001B24B8;
        *(short *)(r + 0xA) = 5;
        *(float *)(r + 0xC) = f * 210000.0f;
        qcopy(v, b);
        *(float *)(v + 0x10) = random_float_between(0.0f, 256.0f);
        r[8] = truncate_float_to_s32(*(float *)(v + 0x10));
        *(float *)(v + 0x14) = g;
        *(int *)(v + 0x18) = c;
    }
    return r;
}
extern void func_001F9BD8(void *, void *, void *);
extern int func_001FA898(float);
extern float func_001F9B88(float);
extern void func_L00_002688A8(void *);

/* Particle update: move, spin, ease toward a target value, fade, die. */
void func_L00_00272890(char *m) {
    char *v = m + 0x20;
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(float *)(m + 0xC) += 5880.0f;
    *(float *)(v + 0x14) *= 0.98f;
    *(float *)(v + 0x10) += *(float *)(v + 0x14);
    m[8] = truncate_float_to_s32(*(float *)(v + 0x10));
    if (*(float **)(v + 0x18) != 0) {
        if (FastAbsF(*(float *)(m + 0x18) - **(float **)(v + 0x18)) < 0.2f) {
            *(float *)(m + 0x18) = **(float **)(v + 0x18) + 0.02f;
        }
    }
    *(short *)(m + 0xA) -= 1;
    if (*(short *)(m + 0xA) == 0) {
        *(unsigned *)(m + 4) += 0xFF000000;
        *(short *)(m + 0xA) = 1;
    }
    if ((*(unsigned *)(m + 4) & 0xFF000000) == 0) KillPart(m);
}
extern char *D_L00_001B24BC;
extern unsigned char *func_00218928(int);
extern int func_002140B0(int);
extern int func_001FA898(float);

unsigned char *func_L00_002729B8(void *a, void *b, float f) {
    unsigned char *r = func_00218928(0x2F);
    if (r != 0) {
        qcopy(r + 0x10, a);
        *(int *)(r + 4) = ((random_integer_below(8) + 0x28) << 24) | 0x808080;
        r[9] = truncate_float_to_s32(2.0f) + 0x20;
        r[3] = 0x48;
        r[1] = 0;
        r[2] = *(unsigned char *)D_L00_001B24BC;
        *(float *)(r + 0xC) = f;
        qcopy(r + 0x20, b);
        r[8] = random_integer_below(0x100);
    }
    return r;
}
extern void func_001F9C30(void *, void *, float);
extern void func_001F9BD8(void *, void *, void *);
extern void func_L00_002688A8(void *);
void func_L00_00272A88(char *m) {
    char *v = m + 0x20;
    int t;
    FastVecScale(v, v, 0.975f);
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(float *)(m + 0xC) += 14700.0f;
    m[8] += v[0x10];
    t = *(int *)(m + 4) + 0xFE000000;
    *(int *)(m + 4) = t;
    if (t < 0) {
        KillPart(m);
    }
}
extern void func_001F9BD8(void *, void *, void *);
extern float func_001FA888(int);
extern float func_001F9B88(float);
extern int func_001FA8A8(int, int, float);
extern int func_001F9938(void *);
extern void func_L00_002688A8(void *);
void func_L00_00272B28(char *m) {
    char *v = m + 0x20;
    m[8] += v[0x1C];
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(int *)(m + 4) = FastTweenColor(*(int *)(v + 0x18), *(int *)(v + 0x14),
        FastAbsF(func_001FA888(*(short *)(m + 0xA)) * *(float *)(v + 0x10) - 1.0f));
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
    }
}
typedef u32 u128 __attribute__((mode(TI), aligned(16)));
extern void func_001F9BD8_72BC0b(void *, void *, void *) __asm__("func_001F9BD8");
extern void func_L00_002688A8_72BC0b(void *) __asm__("func_L00_002688A8");
extern void func_001F9BD8_72BC0c(void *, void *, void *) __asm__("func_001F9BD8");
extern void func_L00_002688A8_72BC0c(void *) __asm__("func_L00_002688A8");
typedef union { u128 q; f32 f[4]; s32 i[4]; } V00271d20;
typedef struct { u8 pad[0xA]; s16 xa; u8 pc[4]; V00271d20 pos; V00271d20 vel; V00271d20 acc; } O00271d20;
extern V00271d20 D_L00_00173F60_72BC0 __asm__("D_L00_00173F60");
void func_001F9BD8_72BC0d(void *, void *, void *) __asm__("func_001F9BD8");
s32 func_001F9938_72BC0b(void *) __asm__("func_001F9938");
void func_L00_002688A8_72BC0d(void *) __asm__("func_L00_002688A8");
s32 func_L00_001EFFF0_72BC0(void *, void *, s32, s32, s32) __asm__("func_L00_001EFFF0");
s32 func_001F9938_72BC0c(void *) __asm__("func_001F9938");
void func_L00_002688A8_72BC0e(void *) __asm__("func_L00_002688A8");
extern int func_001F9938_72BC0d(void *) __asm__("func_001F9938");
extern void func_L00_002688A8_72BC0f(void *) __asm__("func_L00_002688A8");
void func_L00_002688A8_72BC0g(void *) __asm__("func_L00_002688A8");
void func_001F9BD8_72BC0e(void *, void *, void *) __asm__("func_001F9BD8");
void func_001F9BD8_72BC0f(void *, void *, void *) __asm__("func_001F9BD8");
void func_L00_002688A8_72BC0h(void *) __asm__("func_L00_002688A8");
void func_001F9BD8_72BC0g(void *, void *, void *) __asm__("func_001F9BD8");
s32 func_001F9938_72BC0e(void *) __asm__("func_001F9938");
void func_L00_002688A8_72BC0i(void *) __asm__("func_L00_002688A8");
extern void func_L00_002688A8_72BC0j(void *) __asm__("func_L00_002688A8");
extern void func_001F9BD8_72BC0h(void *, void *, void *) __asm__("func_001F9BD8");
extern void func_L00_002688A8_72BC0k(void *) __asm__("func_L00_002688A8");
extern void func_L00_002688A8_72BC0l(void *) __asm__("func_L00_002688A8");
extern void func_L00_002688A8_72BC0m(void *) __asm__("func_L00_002688A8");
int func_001F9938_72BC0f(void *) __asm__("func_001F9938");
void func_L00_002688A8_72BC0n() __asm__("func_L00_002688A8");
void func_001F9BD8_72BC0i(void *, void *, void *) __asm__("func_001F9BD8");
s32 func_001F9938_72BC0g(void *) __asm__("func_001F9938");
void func_L00_002688A8_72BC0o(void *) __asm__("func_L00_002688A8");

/* Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/shared/rendering_002712b8.c, FUN_L00_00271d20. */
void func_L00_00272BC0(O00271d20 *o) {
    V00271d20 t;
    V00271d20 *acc = &o->acc;
    V00271d20 *pos = &o->pos;
    V00271d20 *vel = &o->vel;
    t.f[0] = acc->f[0];
    t.f[1] = acc->f[1];
    t.f[2] = acc->f[2];
    t.f[3] = 0.0f;
    func_001F9BD8_72BC0i(pos, pos, &t);
    func_001F9BD8_72BC0i(vel, vel, &t);
    if (func_001F9938_72BC0g(&o->xa)) {
        func_L00_002688A8_72BC0o(o);
    } else if (func_L00_001EFFF0_72BC0(vel, pos, 0x10, acc->i[3], 0)) {
        o->pos.q = D_L00_00173F60_72BC0.q;
        o->xa = 0;
    }
}
extern unsigned char *D_L00_001B24C8;
extern short D_L00_001602D0;
extern float D_0015EE6C MACRO_ADDR;

// particle update: advance position, tick colour, spawn-time drift, kill when done
void func_L00_00272C98(unsigned char *m) {
    unsigned char *v = m + 0x20;
    if (FastDecTimer(m + 0xA)) {
        *(float *)(v + 8) -= *(float *)(v + 0x18);
    }
    FastVecAdd(m + 0x10, m + 0x10, v);
    m[8] += v[0x14];
    if (m[2] == *D_L00_001B24C8) {
        *(float *)(m + 0xC) += *(float *)&D_L00_001602D0 * D_0015EE6C * 210000.0f;
    }
    if (*(float *)(m + 0x18) < *(float *)(v + 0x10)) {
        KillPart(m);
    }
}
extern void func_L00_001FF2C8(void *, void *, float);
extern void func_L00_001FF240(void *, void *, void *);
extern float D_0015EE70 MACRO_ADDR;

// Updates a particle: drifts it with gravity, fades it, kills it when faded or timed out.
void func_L00_00272D68(char *m) {
    char *v = m + 0x20;
    char tmp[16];
    int t;
    func_L00_001FF2C8(tmp, v, 0.95f);
    *(float *)(v + 8) += D_0015EE70 * 5.0f;
    func_L00_001FF240(tmp, m + 0x10, v);
    t = *(int *)(m + 4) + 0xFE000000;
    *(int *)(m + 4) = t;
    if ((unsigned)((t & 0xFF000000) - 1) > 0x5EFFFFFF || FastDecTimer(m + 0xA)) {
        KillPart(m);
    } else {
        *(float *)(m + 0xC) += (210000.0f - *(float *)(m + 0xC)) * 0.07f;
        m[8] += 1;
    }
}
void func_L00_00272E60(char *m) {
    char *v;
    float f;
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
    } else {
        v = m + 0x20;
        f = func_001FA888(*(short *)(m + 0xA)) * *(float *)(v + 0x10);
        *(int *)(m + 4) = FastTweenColor(*(int *)(v + 0xC), *(int *)(v + 8), f);
        *(float *)(m + 0xC) = ((*(float *)(m + 0x20) - *(float *)(v + 4)) * f + *(float *)(v + 4)) * 210000.0f;
    }
}
extern int D_L00_001B24D4;

/* spawns a type 53 particle */
unsigned char *func_L00_00272F00(float *pos, int a, int col, int mode, int b, float *vel, float f0, float f1, float f2) {
    unsigned char *r = func_00218928(0x35);
    unsigned char *q;
    float *w;
    if (r != 0) {
        q = r + 0x20;
        qcopy(r + 0x10, pos);
        *(float *)(r + 0x18) += 0.05f;
        *(int *)(r + 4) = col;
        r[3] = 0x48;
        r[9] = truncate_float_to_s32(0.4f) + 0x20;
        r[1] = 0;
        r[2] = *(unsigned char *)D_L00_001B24D4;
        *(short *)(r + 0xA) = a;
        *(float *)(r + 0xC) = f0 * 210000.0f;
        if (mode == 0) {
            r[8] = 0;
        } else if (mode == 1) {
            r[8] = 0x20;
        } else {
            r[8] = random_integer_below(0xFF);
        }
        *(float *)q = *(float *)(r + 0xC);
        *(short *)(q + 8) = a;
        q[0xA] = b;
        *(float *)(q + 4) = f1 * 210000.0f;
        q[0xB] = col >> 24;
        *(float *)(q + 0x18) = f2;
        w = (float *)(q + 0xC);
        w[0] = vel[0];
        w[1] = vel[1];
        w[2] = vel[2];
    }
    return r;
}
INCLUDE_ASM("asm/overlays", func_L00_00273090);
typedef struct { int a[4]; } V54 __attribute__((aligned(16)));
typedef struct { int i0; float f4; float f8; float fc; void *p10; void *p14; } Q54;
extern void func_L00_002633D8(int, float *, float *, void *, float, float);
extern int func_001F9850(int);
extern int func_L00_0025D038(float, float, float, float);
extern int func_L00_001F2BE8(float, void *, int, void *, int);
extern void func_L00_0025BA50(void *, void *, void *, int, int, int, int, int, float, float, float);
extern int *D_L00_00178000[];

/* Part type 54 update: advances a particle, fades its color near the end of life and spawns a light effect at its position. Adapted from Lombyte (MIT) for PAL: overlays/shared/rendering_002712b8.c, FUN_L00_00272438. */
void func_L00_002732D8(unsigned char *m) {
    V54 *pos = (V54 *)(m + 0x10);
    Q54 *q = (Q54 *)(m + 0x20);
    V54 old;
    V54 t;
    float x, y;
    int r;
    old = *pos;
    q->f4 += q->f8;
    func_L00_002633D8(q->i0, &x, &y, pos, q->f4, q->fc);
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
        return;
    }
    if ((float)*(short *)(m + 0xA) < (float)scale_ticks(0x1E) * 0.25f) {
        float a = func_001FA888(*(short *)(m + 0xA));
        *(int *)(m + 4) = func_L00_0025D038(0.7f, 0.7f, 0.7f, a * 0.08f / ((float)scale_ticks(0x1E) * 0.25f));
    }
    r = coll_sphere_mobys(0.15f, pos, 0x10, q->p14, 0);
    t = *pos;
    func_L00_0025BA50(q->p14, (void *)&t, D_L00_00178000, r, 0, 0x810001, 2, 1, 2.0f, 1.0f, 1.0f);
}
int func_001FA898(float);
typedef struct { u8 *o; u8 *b; s32 k; f32 f; } S_2725d8;
typedef struct {
    u8 b0;
    u8 b1;
    u8 b2;
    u8 b3;
    s32 w4;
    u8 b8;
    u8 b9;
    u8 padA[2];
    s32 wC;
    u8 v10[16];
    u8 v20[12];
    f32 f2C;
    S_2725d8 s;
} P_2725d8;
extern u8 * D_L00_001B24DC;
P_2725d8 *func_00218928_73478(s32) __asm__("func_00218928");
s32 func_001FA898_73478b(f32) __asm__("func_001FA898");
void func_L00_00250800_73478(u8 *, u8 *, void *) __asm__("func_L00_00250800");
int func_001FA898_73478c(float) __asm__("func_001FA898");
s32 func_001FA898_73478d(f32) __asm__("func_001FA898");

/* Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/shared/rendering_002712b8.c, FUN_L00_002725d8. */
P_2725d8 *func_L00_00273478(u8 *a0, u8 *a1, s32 a2, s32 a3, f32 a4, f32 a5) {
    P_2725d8 *p = func_00218928_73478(0x37);
    a3++;
    a3--;
    if (p) {
        S_2725d8 *s;
        p->w4 = a2;
        p->wC = a3;
        p->b9 = func_001FA898_73478d(0.4f) + 0x20;
        p->b3 = 0x48;
        p->b1 = 3;
        p->b2 = *D_L00_001B24DC;
        func_L00_00250800_73478(a0, a1, p->v10);
        qcopy(p->v20, p->v10);
        p->f2C = a5;
        *(f32 *)((u8 *)p + 0x1C) = a4;
        s = &p->s;
        p->s.o = a0;
        s->k = *(s16 *)(a0 + 0xA6);
        s->b = a1;
        s->f = a4;
    }
    return p;
}
extern void func_001F9BD8_273578(void *, void *, void *) __asm__("func_001F9BD8");
extern void func_L00_002688A8_273578(void *) __asm__("func_L00_002688A8");
typedef unsigned int u128_2726d8 __attribute__((mode(TI), aligned(16)));
typedef struct { u8 *owner; s32 x4; s32 x8; f32 xC; } Q_2726d8;
typedef struct { u8 pad0[0x10]; u128_2726d8 pos; u8 pad20[0xC]; f32 f2C; Q_2726d8 q; } P_2726d8;
extern f32 func_002140F8_273578(f32, f32) __asm__("func_002140F8");
extern void func_L00_00250800_273578(void *, s32, void *) __asm__("func_L00_00250800");
extern void func_001F9BF0_273578(void *, void *, void *) __asm__("func_001F9BF0");
extern f32 func_001F9CB8_273578(void *) __asm__("func_001F9CB8");
extern void func_L00_001FF4B0_273578(void *, void *, f32) __asm__("func_L00_001FF4B0");
/* Particle update. Adapted from Lombyte (MIT) for PAL: overlays/shared/rendering_002712b8.c, FUN_L00_002726d8. */
void func_L00_00273578(P_2726d8 *p) {
    Q_2726d8 *q = &p->q;
    u128_2726d8 t;
    f32 save, sc, r2, f;
    if (p->q.owner == 0 || *(s16 *)(p->q.owner + 0xA6) != q->x8 || p->q.owner[0x20] == 0xFE || p->q.owner[0x20] == 0xFD) {
        func_L00_002688A8_273578(p);
        return;
    }
    sc = q->xC * func_002140F8_273578(0.5f, 1.0f);
    save = p->f2C;
    qcopy(&t, &p->pos);
    func_L00_00250800_273578(p->q.owner, q->x4, &p->pos);
    func_001F9BF0_273578(&t, &t, &p->pos);
    r2 = func_002140F8_273578(-0.021f, 0.021f);
    if (func_001F9CB8_273578(&t) < 0.0625f) {
        f = r2 + 0.0625f;
    } else {
        f = func_001F9CB8_273578(&t) + r2;
    }
    func_L00_001FF4B0_273578(&t, &t, f);
    func_001F9BD8_273578((u8 *)p + 0x20, &p->pos, &t);
    *(f32 *)((u8 *)p + 0x1C) = sc;
    p->f2C = save;
}
/* Updates a fading particle: damps velocity, moves, dims colour, kills at zero. */
void func_L00_002736D8(char *m) {
    char *v = m + 0x20;
    int t;
    FastVecScale(v, v, 0.975f);
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(float *)(m + 0xC) += 6300.0f;
    t = *(unsigned char *)(m + 4) - 4;
    if (t <= 0) {
        KillPart(m);
    } else {
        { int u = (t << 8) | 0x60000000; int w = t << 16; *(int *)(m + 4) = (w | u) | t; }
    }
}
// particle update: drift, fade colour in and out over the timer
void func_L00_00273788(char *m) {
    char *v = m + 0x20;
    int t;
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(float *)(m + 0xC) += 5880.0f;
    *(float *)(v + 0x14) *= 0.98f;
    *(float *)(v + 0x10) += *(float *)(v + 0x14);
    m[8] = truncate_float_to_s32(*(float *)(v + 0x10));
    if (--*(short *)(m + 0xA) <= 0) {
        KillPart(m);
    }
    t = *(short *)(m + 0xA);
    if (t > 0x40) {
        *(int *)(m + 4) = ((0x80 - t) << 24) | 0x808080;
    } else {
        *(int *)(m + 4) = (t << 24) | 0x808080;
    }
}
extern void func_00215C00(void *, float, float, float);
extern unsigned char *D_L00_001B24E8;

/* Spawn a type-0x3A particle of kind a1 at pos. */
unsigned char *func_L00_00273868(float *pos, unsigned char a1, unsigned char a2, unsigned char a3,
    unsigned char a4, unsigned char a5, int a6, float f0, float f1) {
    unsigned char *r = func_00218928(0x3A);
    unsigned char *v;
    int k;
    if (r != 0) {
        qcopy(r + 0x10, pos);
        v = r + 0x20;
        r[9] = truncate_float_to_s32(0.0f) + 0x70;
        r[1] = 0;
        r[3] = 0x44;
        r[2] = D_L00_001B24E8[func_001160D8() & 7];
        *(float *)(r + 0xC) = 21000.0f;
        r[8] = func_001160D8();
        v[0x10] = a1;
        v[0x12] = a3;
        v[0x13] = a4;
        *(int *)(v + 0x18) = a6;
        *(float *)(v + 0x1C) = f0;
        v[0x11] = a2;
        k = v[0x10];
        v[0x15] = a5;
        switch (k) {
        case 0:
        case 1:
            *(short *)(r + 0xA) = a2;
            *(int *)(r + 4) = 0xFF808080;
            v[0x14] = 0;
            break;
        case 2: {
            float x = random_float_between(3.0f, 9.0f) * f1;
            float y, z;
            x = x * D_0015EE6C;
            y = random_angle_radians();
            z = random_float_between(1.3439035f, 1.7976891f);
            func_00215C00(v, x, y, z);
            *(float *)(r + 0xC) = 42000.0f;
            v[0x16] = (func_001160D8() & 0x1F) + 0x10;
            *(int *)(r + 4) = (v[0x16] << 24) | 0x808080;
            *(short *)(r + 0xA) = a5;
            v[0x14] = k;
            break;
        }
        }
    }
    return r;
}
extern void func_L00_00260958(float *v, float s);
extern float func_001F9D48(void *, void *);
extern void func_001F9BF0(void *, void *, void *);
extern void func_L00_001FF4B0(void *, void *, float);
extern void func_L00_0025AC00(int, int, int, void *, void *, float);
typedef float V_272bc0[4] __attribute__((aligned(16)));
typedef struct { char p0[0x88]; float f88; char p1[0x2080 - 0x8C]; int i2080; } P_272bc0;
extern unsigned char *D_L00_0016022C MACRO_ADDR;

/* part type 58 update: fade in, hold spawning sparks, then fall and fade out. Adapted from Lombyte (MIT) for PAL: overlays/shared/rendering_002712b8.c, FUN_L00_00272bc0. */
void func_L00_00273A60(unsigned char *p) {
    V_272bc0 t;
    unsigned char *q;
    unsigned char *c;
    P_272bc0 *g;
    int i;
    float a;
    float k;

    q = p + 0x20;
    switch (q[0x14]) {
    case 0:
        {
            float n = func_001FA888(q[0x11]);
            *(int *)(p + 4) = FastTweenColor(0xFF4080FF, 0, (n - func_001FA888(*(short *)(p + 0xA))) / n);
        }
        if (FastDecTimer(p + 0xA)) {
            if (q[0x10] == 1) {
                KillPart(p);
            } else {
                q[0x14] = 1;
                *(short *)(p + 0xA) = q[0x12];
            }
        }
        break;
    case 1:
        {
        float m;
        for (i = 0; i < q[0x13]; i++) {
            qcopy(t, p + 0x10);
            m = 1.0f;
            func_L00_00260958(t, 0.05f);
            if (*(short *)(p + 0xA) < scale_ticks(10)) {
                m = func_001FA888(*(short *)(p + 0xA)) / (float)scale_ticks(10);
            }
            func_L00_00273868(t, 2, q[0x11], q[0x12], q[0x13], q[0x15], *(int *)(q + 0x18), *(float *)(q + 0x1C), m);
        }
        }
        if (FastDecTimer(p + 0xA)) {
            KillPart(p);
        }
        c = D_0013E633 + 0xE9D;
        if (func_001F9D48(p + 0x10, c) < 0.3f) {
            g = (P_272bc0 *)(c - 0x80);
            if (g->f88 < *(float *)(p + 0x18) + 1.2f) {
                FastVecSub(t, c, p + 0x10);
                func_L00_001FF4B0(t, t, 1.0f);
                t[2] = 1.0f;
                func_L00_0025AC00(g->i2080, *(int *)(q + 0x18), 1, p + 0x10, t, *(float *)(q + 0x1C));
            }
        }
        break;
    case 2:
        FastVecAdd(p + 0x10, p + 0x10, q);
        a = func_001FA888(q[0x15]);
        k = a - func_001FA888(*(short *)(p + 0xA));
        k = k / a;
        *(int *)(p + 4) = FastTweenColor((q[0x16] << 24) | 0x4060, 0x8FAFFF, k);
        if (k < 0.6f) {
            *(float *)(p + 0xC) += D_0015EE60 * 0.043f * 210000.0f;
        } else {
            *(float *)(p + 0xC) -= D_0015EE60 * 0.08f * 210000.0f;
        }
        p[2] = D_L00_001B24E8[func_001160D8() & 7];
        if (((p - D_L00_0016022C) >> 6) & 1) {
            p[8]++;
        } else {
            p[8]--;
        }
        if (FastDecTimer(p + 0xA)) {
            KillPart(p);
        }
        break;
    }
}
extern void func_001F9BF0(void *, void *, void *);
extern char D_0013F4D0[];
extern unsigned char *D_L00_001B2400[];

/* spawns particle type 0x3B from a position, colour index and flags */
unsigned char *func_L00_00273E08(float f, void *pos, int a1, unsigned char a2, int idx, int flag, int s, int mode) {
    unsigned char *r = func_00218928(0x3B);
    if (r != 0) {
        char *v = (char *)r + 0x20;
        *(int *)(v + 0x10) = mode;
        if (mode == 1) {
            FastVecSub(v, pos, gHeroPos);
        }
        qcopy(r + 0x10, pos);
        *(int *)(r + 4) = a1;
        r[9] = truncate_float_to_s32(1.0f) + 0x20;
        if (flag != 0) {
            r[3] = 0x44;
        } else {
            r[3] = 0x48;
        }
        r[8] = a2;
        r[1] = 0;
        *(float *)(r + 0xC) = f * 210000.0f;
        r[2] = *D_L00_001B2400[idx];
        *(short *)(r + 0xA) = s;
    }
    return r;
}
extern unsigned char D_0013E633[] NOT_SDA;

// Particle update: registers the velocity vector once, then kills the particle when its timer expires.
void func_L00_00273F28(char *m) {
    char *v = m + 0x20;
    if (*(int *)(v + 0x10) == 1) {
        FastVecAdd(m + 0x10, D_0013E633 + 0xE9D, v);
    }
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
    }
}
typedef struct { char p0[0x80]; float x, y, z; } G_2730e0;
extern unsigned char *D_L00_001B24D4_p __asm__("D_L00_001B24D4") NOT_SDA;
extern int func_001FA898_r(float) __asm__("func_001FA898");

/* Spawns an effect record at a position inside the level bounds; Adapted from Lombyte (MIT) for PAL: overlays/shared/rendering_002712b8.c, FUN_L00_002730e0. */
unsigned char *func_L00_00273F80(float *pos, char *vel, int color, unsigned char life, unsigned char b, int mode, float scale)
{
    unsigned char *m;
    float *v;
    if (pos[0] < 2.0f || 1021.0f < pos[0] || pos[1] < 2.0f || 1021.0f < pos[1] || pos[2] < 2.0f || 1021.0f < pos[2])
        return 0;
    m = func_00218928(0x3C);
    if (m) {
        v = (float *)(m + 0x20);
        qcopy(m + 0x10, pos);
        qcopy(v, vel);
        *(int *)(v + 7) = mode;
        if (mode == 1) {
            G_2730e0 *g = (G_2730e0 *)(D_0013E633 + 0xE1D);
            v[4] = *(float *)(m + 0x10) - g->x;
            v[5] = *(float *)(m + 0x14) - g->y;
            v[6] = *(float *)(m + 0x18) - g->z;
        }
        *(int *)(m + 4) = color;
        m[9] = func_001FA898_r(1.0f) + 0x20;
        m[3] = 0x48;
        m[8] = b;
        m[1] = 0;
        *(float *)(m + 0xC) = scale * 210000.0f;
        m[2] = *D_L00_001B24D4_p;
        *(short *)(m + 0xA) = life;
    }
    return m;
}
/* Particle update: move with the camera offset when flagged, kill it when off the map or its timer ends, else fade its colour. */
void func_L00_00274138(char *m) {
    char *v = m + 0x20;
    int col;
    float a;
    if (*(int *)(v + 0x1C) == 1) {
        char *g = (char *)D_0013E633 + 0xE1D;
        *(float *)(m + 0x10) = *(float *)(g + 0x80) + *(float *)(v + 0x10);
        *(float *)(m + 0x14) = *(float *)(g + 0x84) + *(float *)(v + 0x14);
        *(float *)(m + 0x18) = *(float *)(g + 0x88) + *(float *)(v + 0x18);
        FastVecAdd(m + 0x10, m + 0x10, v);
        *(float *)(v + 0x10) = *(float *)(m + 0x10) - *(float *)(g + 0x80);
        *(float *)(v + 0x14) = *(float *)(m + 0x14) - *(float *)(g + 0x84);
        *(float *)(v + 0x18) = *(float *)(m + 0x18) - *(float *)(g + 0x88);
    } else {
        FastVecAdd(m + 0x10, m + 0x10, v);
    }
    if (*(float *)(m + 0x10) < 2.0f || *(float *)(m + 0x10) > 1021.0f ||
        *(float *)(m + 0x14) < 2.0f || *(float *)(m + 0x14) > 1021.0f ||
        *(float *)(m + 0x18) < 2.0f || *(float *)(m + 0x18) > 1021.0f ||
        FastDecTimer(m + 0xA) != 0) {
        KillPart(m);
        return;
    }
    col = *(int *)(m + 4) & 0xFFFFFF;
    a = func_001FA888(*(short *)(m + 0xA) - 1);
    *(int *)(m + 4) = FastTweenColor(col, *(int *)(m + 4), a / func_001FA888(*(short *)(m + 0xA)));
}
extern void func_L00_00250800(void *, int, void *);
extern void func_L00_001FF4B0(void *, void *, float);
extern unsigned char *D_L00_001B24F4;
extern float D_L00_00166EC0[];

typedef struct {
    unsigned char pad0[0x20];
    signed char b20;
} T_m;
typedef struct {
    T_m *m;
    float f4;
    float f8;
    short hC;
    short hE;
    float f10;
    float f14;
} E_p;
typedef struct {
    unsigned char b0, b1, b2, b3;
    unsigned int w4;
    unsigned char b8, b9;
    short hA;
    float fC;
    float pos[4] __attribute__((aligned(16)));
    E_p e;
} P_p;

/* Updates a fading, pulsing particle: animates its phase, colour and scale, then orients it. Adapted from Lombyte (MIT) for PAL: src/overlays/shared/rendering_002712b8.c, FUN_L00_00273448. */
void func_L00_002742E8(P_p *p) {
    E_p *e;
    float lim;
    float a[4] __attribute__((aligned(16)));
    float v[4] __attribute__((aligned(16)));
    if (p == 0) {
        return;
    }
    e = &p->e;
    if (FastDecTimer(&p->hA) || e->m == 0 || e->m->b20 < 0) {
        goto kill;
    }
    e->hC = (e->hC + 1) & 0xF;
    if (p->fC < 159600.0f) {
        p->fC += D_0015EE60 * 3989.99976f;
        if (159600.0f < p->fC) {
            p->fC = 159600.0f;
        }
    } else if (159600.0f < p->fC) {
        p->fC -= D_0015EE60 * 15959.999f;
        if (p->fC < 159600.0f) {
            p->fC = 159600.0f;
        }
    }
    e->f8 += D_0015EE60 * 0.001f;
    p->b8 = truncate_float_to_s32(e->f8 * 255.0f);
    p->b2 = D_L00_001B24F4[e->hC];
    if (p->fC <= 159600.0f || 0.0f < e->f10) {
        float *q = &e->f4;
        *q += q[3];
    }
    {
        float x;
        if (p->fC <= 159600.0f) {
            x = e->f4;
            lim = 0.3f;
        } else {
            x = e->f4;
            lim = 0.15f;
        }
        if (!(lim < x)) {
            if (x < 0.0f) {
            kill:
                KillPart(p);
                return;
            }
        } else {
            e->f10 = -e->f10;
            e->f4 = x + e->f10;
        }
    }
    p->w4 = (p->w4 & 0xFFFFFF) + (truncate_float_to_s32(e->f4 * 256.0f) << 24);
    e->f14 += (1.0f - e->f14) * (D_0015EE60 * 0.175f);
    func_L00_00250800(e->m, e->hE, a);
    FastVecSub(v, D_L00_00166EC0, a);
    func_L00_001FF4B0(v, v, e->f14);
    FastVecAdd(p->pos, a, v);
}
extern unsigned char *D_L00_001B24F8;

// Spawns a type-62 particle at a position with a lifetime and a colour index.
unsigned char *func_L00_002745A8(void *a, int b, int c) {
    unsigned char *r = func_00218928(0x3E);
    if (r != 0) {
        unsigned char *v = r + 0x20;
        qcopy(r + 0x10, a);
        *(int *)(r + 4) = 0x7F7F4040;
        r[9] = truncate_float_to_s32(4.0f) + 0x40;
        r[1] = 0;
        r[3] = 0x48;
        *(float *)(r + 0xC) = 30000.0f;
        r[8] = random_integer_below(0xFF);
        *(short *)(v + 2) = c;
        if (c >= 2) c = 0;
        r[2] = D_L00_001B24F8[c];
        *(short *)(r + 0x20) = truncate_float_to_s32(127.0f / func_001FA888(b));
        *(short *)(r + 0xA) = b;
    }
    return r;
}
void func_L00_002746A0(char *a) {
    char *s = a + 0x20;
    int w;
    int t;
    if (*(short *)(s + 2) == 1) {
        return;
    }
    if (*(short *)(s + 2) == 2) {
        *(float *)(a + 0x10) = *(float *)(*(char **)(s + 4) + 0x10) + *(float *)(s + 0x10);
        *(float *)(a + 0x14) = *(float *)(*(char **)(s + 4) + 0x14) + *(float *)(s + 0x14);
        *(float *)(a + 0x18) = *(float *)(*(char **)(s + 4) + 0x18) + *(float *)(s + 0x18);
    }
    w = *(int *)(a + 4);
    t = w >> 24;
    t -= *(short *)(a + 0x20);
    if (t <= 0) {
        KillPart(a);
    } else {
        *(int *)(a + 4) = (w & 0xFFFFFF) | (t << 24);
    }
}
extern unsigned char *D_L00_001B2500;

/* Spawns a type-64 particle at pos moving with vel, sprite size chosen by distance to the hero. */
unsigned char *func_L00_00274788(void *pos, void *vel, float scale, int life, float f1, int col, float f2, int a4, int big) {
    unsigned char *r = func_00218928(0x40);
    unsigned char *u;
    if (r != 0) {
        u = r + 0x20;
        qcopy(r + 0x10, pos);
        if (func_001F9D48(D_0013E633 + 0xE9D, pos) < 80.0f) {
            r[9] = truncate_float_to_s32(1.0f) + 0x30;
        } else {
            r[9] = truncate_float_to_s32(1.0f) + 0x20;
        }
        r[3] = big ? 0x48 : 0x44;
        r[1] = 0;
        r[2] = D_L00_001B2500[1];
        *(int *)(r + 4) = col;
        *(float *)(r + 0xC) = scale * 210000.0f;
        r[8] = (int)random_float_between(0.0f, 255.0f);
        *(short *)(r + 0xA) = life;
        qcopy(u, vel);
        *(float *)(u + 0x10) = f1;
        *(float *)(u + 0x14) = f2;
        *(int *)(u + 0x18) = a4;
    }
    return r;
}
typedef u32 u128_74908 __attribute__((mode(TI), aligned(16)));
typedef union {
    u128_74908 q;
    f32 f[4];
    s32 i[4];
} Vec4;
unsigned char *func_L00_00272488(void *pos, int x, int color, float size, float w);
f32 func_002140F8(f32, f32);
void func_L00_001FF4B0(void *, void *, f32);
s32 func_002140B0(s32 arg0);
struct EmberMotion {
    Vec4 vel; /* 0x0 */
    f32 floor_z; /* 0x10: bursts once pos.z drops below this */
    f32 gravity; /* 0x14 */
    s32 color2; /* 0x18: smoke end colour */
};
struct EmberParticle {
    u8 unk0;
    u8 unk1;
    u8 tex; /* 0x2: passed on to the smoke puff (FUN_L00_0026bb70) */
    u8 blend; /* 0x3: passed on to the smoke puff */
    s32 color; /* 0x4: 0xAABBGGRR */
    u8 spin; /* 0x8 */
    u8 unk9;
    s16 life; /* 0xA: frames left (FUN_001f9770) */
    f32 size; /* 0xC */
    Vec4 pos; /* 0x10 */
    struct EmberMotion m; /* 0x20 */
};
extern s32 func_L00_00258BC8(s32, s32);
extern s32 func_001F9850(s32);
extern unsigned char *func_L00_0026CA10(void *a, void *b, int c, int d, float f, int n, int e, int g, int h);
extern unsigned char *func_L00_0026CD70(void *a, void *b, int c, int d, float f, int n, int k);
extern int func_L00_00237B70_74908(int, int, float) __asm__("func_L00_00237B70");
extern short D_L00_001602E8;
extern f32 D_0015EE6C MACRO_ADDR;
extern s32 D_0015EE84 MACRO_ADDR;

/* Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/shared/rendering/002712b8.c, FUN_L00_00273a68. */
void func_L00_00274908(struct EmberParticle *p) {
    struct EmberMotion *m = &p->m;
    Vec4 t;
    s32 cr, cg, cb;
    s32 n, c1, c2;
    f32 f;

    if (FastDecTimer(&p->life))
        m->vel.f[2] -= m->gravity;
    FastVecAdd(&p->pos, &p->pos, &m->vel);
    p->spin += 2;
    if (!(p->pos.f[2] < m->floor_z))
        return;
    cr = p->color & 0xFF;
    cg = (p->color & 0xFF00) >> 8;
    cb = ((u32)p->color >> 16) & 0xFF;
    if (!random_integer_below((*(u32 *)&D_L00_001602E8) - 1)) {
        p->pos.f[2] = m->floor_z;
        m->vel.f[0] *= random_float_between(1.0f, 3.5f);
        m->vel.f[1] *= random_float_between(1.0f, 3.5f);
        m->vel.f[2] *= random_float_between(-1.0f, -1.5f);
        f = p->size;
        f *= 0.5f;
        n = rand_range(scale_ticks(0x3C), scale_ticks(0x78));
        func_L00_0026CA10(&p->pos, &m->vel, p->color, m->color2, f, n, 0, p->tex, p->blend);
    } else {
        p->pos.f[2] = m->floor_z;
        m->vel.f[0] += random_float_between(-5.0f, 5.0f) * D_0015EE6C;
        m->vel.f[1] += random_float_between(-5.0f, 5.0f) * D_0015EE6C;
        m->vel.f[2] *= random_float_between(-0.5f, -1.0f);
        f = p->size;
        f *= 0.25f;
        n = rand_range(scale_ticks(0x1E), scale_ticks(0x3C));
        func_L00_0026CA10(&p->pos, &m->vel, p->color, m->color2, f, n, 0, p->tex, p->blend);
    }
    if (D_0015EE84 == 10) {
        if (!random_integer_below(0x13)) {
            t.q = p->pos.q;
            t.f[2] += 0.1f;
            func_L00_00272488(&t, 0, ((random_integer_below(6) + 0x34) << 24) | (cb << 16) | (cg << 8) | cr,
                             0.05f, 10500.0f);
        }
        if (!random_integer_below(9)) {
            c1 = func_L00_00237B70_74908(0x7F000000, 0x7F000000 | (cb << 16) | (cg << 8) | cr,
                                  random_float_between(0.25f, 1.0f));
            c2 = func_L00_00237B70_74908(0, 0x5F00, random_float_between(0.5f, 1.0f));
            m->vel.f[0] = random_float_between(-1.0f, 1.0f);
            m->vel.f[1] = random_float_between(-1.0f, 1.0f);
            m->vel.f[2] = 0.0f;
            func_L00_001FF4B0(&m->vel, &m->vel, random_float_between(1.5f, 3.0f) * D_0015EE6C);
            m->vel.f[2] = D_0015EE6C * 3.0f;
            t.q = p->pos.q;
            t.f[2] -= 1.5f;
            f = random_float_between(420000.0f, 630000.0f);
            n = rand_range(scale_ticks(0x5A), scale_ticks(0x96));
            func_L00_0026CD70(&t, &m->vel, c1, c2, f, n, 3);
        }
    }
    KillPart(p);
}
typedef struct { int a[4]; } V __attribute__((aligned(16)));
extern float D_0015EE64 MACRO_ADDR;
extern V D_L00_00173F60;
extern int func_L00_001EFFF0(void *, void *, int, void *, int);
extern void func_001F9BC0(void *);

/* Particle type 65 update: fall under gravity, bounce off the world, fade the colour and die when spent. Adapted from Lombyte (MIT) for PAL: overlays/shared/rendering_002712b8.c, FUN_L00_00273ee0. */
void func_L00_00274D80(unsigned char *o) {
    V out;
    float *c;
    unsigned char *b;
    float d;
    if (!o) return;
    c = (float *)(o + 0x20);
    b = o + 0x10;
    d = D_0015EE60;
    c[7] += d * 0.0f;
    *(float *)(o + 0xC) += d * -100.0f;
    FastVecAdd(&out, b, c);
    if (*(float *)(o + 0x20) != 0.0f || c[1] != 0.0f || c[2] != 0.0f) {
        if (func_L00_001EFFF0(o + 0x10, &out, 2, o, 0)) {
            *(V *)(o + 0x10) = D_L00_00173F60;
            clear_u64_value(c);
            *(float *)(o + 0xC) += *(float *)(o + 0xC);
        } else {
            *(V *)(o + 0x10) = out;
            if (c[3] != 0.0f) {
                c[2] += c[3];
            } else {
                c[2] += D_0015EE64 * -0.006300000008195639f;
            }
        }
    }
    if (c[7] <= 0.0f || FastDecTimer(o + 0xA) || *(float *)(o + 0xC) < 0.0f ||
        ((float *)&out)[0] < 0.01f || ((float *)&out)[1] < 0.01f || ((float *)&out)[2] < 0.01f) {
        KillPart(o);
        return;
    }
    c[4] += D_0015EE60 * -0.01f;
    if (c[4] < 0.0f) c[4] = 0.0f;
    c[5] += D_0015EE60 * -0.030009999871253967f;
    if (c[5] < 0.0f) c[5] = 0.0f;
    c[6] += D_0015EE60 * -0.05f;
    if (c[6] < 0.0f) c[6] = 0.0f;
    c[7] += D_0015EE60 * 0.0f;
    if (c[7] < 0.0f) c[7] = 0.0f;
    *(int *)(o + 4) = func_L00_0025D038(c[4], c[5], c[6], c[7]);
    o[8]--;
}
extern unsigned char *D_L00_001B2508;

/* spawns a type-0x42 particle moving in a random direction */
unsigned char *func_L00_00275040(void *pos, int color, float f, float speed) {
    unsigned char *r = func_00218928(0x42);
    if (r != 0) {
        float ang, sp;
        int c;
        char *v;
        qcopy(r + 0x10, pos);
        if (color == -1) {
            c = ((random_integer_below(6) + 0x14) << 24) | 0x808080;
        } else {
            c = color;
        }
        *(int *)(r + 4) = c;
        r[9] = truncate_float_to_s32(2.0f) + 0x20;
        r[3] = 0x48;
        r[1] = 1;
        if (random_integer_below(0x100) & 1) {
            r[2] = D_L00_001B2508[0];
        } else {
            r[2] = D_L00_001B2508[1];
        }
        r[8] = func_001160D8();
        v = (char *)r + 0x20;
        *(float *)(r + 0xC) = f * 210000.0f;
        *(short *)(r + 0xA) = 4;
        ang = random_angle_radians();
        sp = random_float_between(0.0015f, 0.0025f);
        *(float *)v = FastCos(ang) * sp;
        *(float *)(v + 4) = FastSin(ang) * sp;
        *(float *)(v + 0x10) = speed;
        *(int *)(v + 8) = 0;
    }
    return r;
}
void func_L00_002751A8(char *m) {
    char *v = m + 0x20;
    int t;
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(float *)(m + 0xC) += *(float *)(v + 0x10);
    m[8] += 1;
    t = *(unsigned short *)(m + 0xA) - 1;
    *(unsigned short *)(m + 0xA) = t;
    if ((short)t == 0) {
        *(int *)(m + 4) += 0xFF000000;
        *(short *)(m + 0xA) = 2;
    }
    if ((*(int *)(m + 4) & 0xFF000000) == 0) {
        KillPart(m);
    }
}
extern unsigned char *D_L00_001B250C;

/* spawns particle type 0x43 at a position with a colour, timer and optional velocity */
unsigned char *func_L00_00275248(float f0, float f1, int a0, void *pos, int timer, int flag, int col, float *vel) {
    unsigned char *r = func_00218928(0x43);
    if (r != 0) {
        unsigned char *v = r + 0x20;
        qcopy(r + 0x10, pos);
        *(int *)(v + 0xC) = a0;
        *(float *)(v + 0x10) = f0;
        *(float *)(v + 0x14) = f1;
        *(int *)(r + 4) = col | 0x409B9B00;
        r[9] = truncate_float_to_s32(4.0f) + 0x40;
        r[1] = 0;
        r[3] = 0x48;
        *(float *)(r + 0xC) = 52500.0f;
        r[8] = random_integer_below(0xFF);
        *(short *)(v + 0x1C) = flag;
        *(short *)(v + 0x18) = 0;
        r[2] = flag == 0 ? D_L00_001B250C[0] : D_L00_001B250C[1];
        if (flag == 0) {
            *(short *)(v + 0x1A) = truncate_float_to_s32(127.0f / func_001FA888(timer));
        }
        if (vel != 0) {
            *(float *)(v + 0) = vel[0];
            *(float *)(v + 4) = vel[1];
            *(float *)(v + 8) = vel[2];
        }
        *(short *)(r + 0xA) = timer;
    }
    return r;
}
extern int func_L00_0025A468_q(void *, int) __asm__("func_L00_0025A468");
extern char *func_L00_00275248_2753B8(float, void *, void *, float, int, int, int, void *) __asm__("func_L00_00275248");
extern void func_001FA218(void *, void *);
extern void func_001F9EE8(void *, void *, void *);
extern void func_001F9EC0(void *, void *, void *);
extern float func_001FA748(float, float);

// Update for an attached particle: follows its owner moby, spawns a child and orients itself.
void func_L00_002753B8(char *m) {
    char *s = m + 0x20;
    float vv[28];
    char *q;
    char *o;
    float z;
    float t, u, e;
    if (*(short *)(s + 0x1C) == 0) {
        if (func_L00_0025A468_q(m + 4, *(short *)(s + 0x1A))) {
            KillPart(m);
            return;
        }
        if (*(int *)(s + 0xC) == 0) return;
        vv[0] = *(float *)(m + 0x20);
        vv[1] = *(float *)(s + 4);
        vv[2] = *(float *)(s + 8);
        FastVecScale(vv, vv, func_001FA888(*(short *)(s + 0x18)));
        FastVecAdd(m + 0x10, *(char **)(s + 0xC) + 0x10, vv);
        return;
    }
    if (FastDecTimer(m + 0xA) ||
        (*(short *)(m + 0xA) < scale_ticks(10) && func_L00_0025A468_q(m + 4, 0x10))) {
        KillPart(m);
        return;
    }
    if (*(short *)(s + 0x1C) == 1) {
        z = 0.0f;
        func_L00_00275248_2753B8(z, 0, m + 0x10, z, scale_ticks(10), 0, *(signed char *)(m + 7), 0);
        q = m + 0x10;
    } else {
        vv[0] = *(float *)(s + 0);
        vv[1] = *(float *)(s + 4);
        vv[2] = *(float *)(s + 8);
        z = 0.0f;
        o = func_L00_00275248_2753B8(z, *(void **)(s + 0xC), m + 0x10, z, scale_ticks(10), 0, *(signed char *)(m + 7), vv);
        q = m + 0x10;
        if (o != 0) *(short *)(o + 0x38) = *(unsigned short *)(s + 0x18);
    }
    if (*(short *)(s + 0x1C) != 1) return;
    qcopy(q, *(char **)(s + 0xC) + 0x10);
    vv[0] = FastCos(*(float *)(s + 0x10)) * 2.25f;
    vv[1] = FastSin(*(float *)(s + 0x10)) * 2.25f;
    vv[2] = vv[0];
    *(int *)&vv[0] = 0;
    vv[4] = FastCos(*(float *)(s + 0x14)) * 0.28f;
    vv[5] = FastSin(*(float *)(s + 0x14)) * 0.28f;
    vv[6] = vv[4];
    *(int *)&vv[4] = 0;
    clear_u64_value((vv + 8));
    vv[9] = *(float *)(s + 0x10);
    func_001FA218((vv + 12), (vv + 8));
    func_001F9EE8((vv + 4), (vv + 4), (vv + 12));
    FastVecAdd(vv, vv, (vv + 4));
    func_001F9EC0(vv, vv, *(char **)(s + 0xC) + 0xC0);
    FastVecAdd(q, q, vv);
    t = FastAddRots(*(float *)(s + 0x10), D_0015EE6C * 0.9599311f);
    u = D_0015EE6C * 4.3633232f;
    e = *(float *)(s + 0x14);
    *(float *)(s + 0x10) = t;
    *(float *)(s + 0x14) = FastAddRots(e, u);
}
extern float func_002140F8(float, float);
extern void func_L00_00250800(void *, int, void *);
extern void func_0020DAF8(void *, int, void *);
extern void func_L00_001FF4B0(void *, void *, float);

/* part type 68 update: follows its owner, scaling velocity until the owner goes away */
void func_L00_002756B8(char *m) {
    float v[16];
    float v2[4];
    unsigned char *p = (unsigned char *)m + 0x30;
    unsigned char *t = *(unsigned char **)(m + 0x30);
    float a, b, f;
    if (t == 0 || *(short *)(t + 0xA6) != *(short *)(p + 6) || t[0x20] == 0xFE || t[0x20] == 0xFD) {
        KillPart(m);
        return;
    }
    a = *(float *)(p + 8) * random_float_between(0.05f, 1.0f);
    b = *(float *)(m + 0x2C);
    func_L00_00250800(*(void **)(m + 0x30), p[4], m + 0x10);
    func_0020DAF8(*(void **)(m + 0x30), p[4], v);
    f = func_001FA888(p[5]);
    f = (random_float_between(-f, f) / 100.0f - 1.0f) * *(float *)(p + 0xC);
    func_L00_001FF4B0(v2, v, f);
    FastVecAdd(m + 0x20, m + 0x10, v2);
    *(float *)(m + 0x1C) = a;
    *(float *)(m + 0x2C) = b;
}
extern int func_L00_00258BC8(int, int);
extern int func_001F9850(int);
extern unsigned char *D_L00_001B2514;

/* spawns a particle at a with velocity b, colour byte c and payload d */
unsigned char *func_L00_002757E8(void *a, void *b, int c, int d) {
    unsigned char *r = func_00218928(0x45);
    char *v;
    int x;
    float t;
    if (r != 0) {
        qcopy(r + 0x10, a);
        v = (char *)r + 0x20;
        r[9] = truncate_float_to_s32(4.0f) + 0x70;
        r[1] = 0;
        r[3] = 0x48;
        *(float *)(r + 0xC) = random_float_between(8000.0f, 50000.0f);
        r[8] = random_integer_below(0x100);
        r[2] = *D_L00_001B2514;
        x = scale_ticks(rand_range(10, 30));
        *(short *)(r + 0xA) = x;
        t = func_001FA888((short)x);
        *(int *)(v + 0x1C) = d;
        *(short *)(v + 0x14) = c;
        *(int *)(v + 0x18) = 0x7F7F7F;
        *(short *)(v + 0x16) = 0;
        *(float *)(v + 0x10) = 1.0f / t;
        qcopy(v, b);
        *(int *)(r + 4) = (c << 24) | 0x7F7F7F;
    }
    return r;
}
extern float func_L00_00258C80(float, float);

/* Per-frame update of a particle that follows a moby's joint, kills itself when out of range or expired. */
void func_L00_00275910(char *p) {
    char *v = p + 0x20;
    float z;
    int t;
    int x;

    if (*(float *)(p + 0x10) < 2.0f || *(float *)(p + 0x10) > 1021.0f ||
        *(float *)(p + 0x14) < 2.0f || *(float *)(p + 0x14) > 1021.0f ||
        (z = *(float *)(p + 0x18)) < 2.0f || z > 1021.0f) {
        KillPart(p);
        return;
    }
    t = *(short *)(v + 0x16);
    if (t == 1) {
        qcopy(p + 0x10, *(char **)(*(char **)(v + 0x1C) + 0x78) + 0xD0);
    } else if (t == 3) {
        qcopy(p + 0x10, *(char **)(*(char **)(v + 0x1C) + 0x78) + 0xE0);
    } else if (t == 2) {
        qcopy(p + 0x10, *(char **)(*(char **)(v + 0x1C) + 0x78) + 0x1F0);
    } else if (t == 4) {
        qcopy(p + 0x10, *(char **)(v + 0x1C) + 0x10);
        *(float *)(p + 0x18) = z + 0.2f;
    } else {
        FastVecAdd(p + 0x10, p + 0x10, v);
    }
    if (*(float *)(p + 0x10) < 2.0f || *(float *)(p + 0x10) > 1021.0f ||
        *(float *)(p + 0x14) < 2.0f || *(float *)(p + 0x14) > 1021.0f ||
        *(float *)(p + 0x18) < 2.0f || *(float *)(p + 0x18) > 1021.0f) {
        KillPart(p);
        return;
    }
    x = *(unsigned char *)(p + 8);
    x += truncate_float_to_s32(randf_sym(0.0f, 64.0f));
    if (x >= 0x100) {
        x -= 0xFF;
    }
    *(unsigned char *)(p + 8) = x;
    if (FastDecTimer(p + 0xA)) {
        KillPart(p);
        return;
    }
    *(int *)(p + 4) = (truncate_float_to_s32(func_001FA888(*(short *)(p + 0xA)) * *(float *)(v + 0x10) * func_001FA888(*(short *)(v + 0x14))) << 24) | *(int *)(v + 0x18);
}
extern int func_001F9850(int);
extern unsigned char *D_L00_001B2518;

/* spawns a particle at pos with a colour byte taken from a table and a heading */
unsigned char *func_L00_00275B98(void *a, int idx, float ang) {
    unsigned char *r = func_00218928(0x46);
    if (r != 0) {
        qcopy(r + 0x10, a);
        *(int *)(r + 4) = 0x80404040;
        r[9] = truncate_float_to_s32(2.0f) + 0x20;
        r[3] = 0x44;
        r[1] = 1;
        r[2] = D_L00_001B2518[idx];
        r[8] = truncate_float_to_s32(ang * 128.0f / 3.14159274f) - 0x20;
        *(float *)(r + 0xC) = 147000.0f;
        *(short *)(r + 0xA) = scale_ticks(0x78);
    }
    return r;
}
extern void func_L00_002688A8(void *);
void func_L00_00275C80(char *a) {
    int t = *(unsigned short *)(a + 0xA) - 1;
    *(short *)(a + 0xA) = t;
    if ((short)t == 0) {
        *(int *)(a + 4) += 0xFF000000;
        *(short *)(a + 0xA) = 2;
    }
    if ((*(int *)(a + 4) & 0xFF000000) == 0) KillPart(a);
}
extern int D_L00_0015F6B0 MACRO_ADDR;
extern float func_001F9D10(void *, void *);
extern float func_001F9CB8(void *);
extern void func_002158E8(float *v, int *out);
extern void func_00215A10(float *arg0, int *arg1);
extern void func_001F9C08(void *, void *, void *, float);
// Advances a particle that homes on a target: steers toward it, fades the colour and steps its keyframes.
void func_L00_00275CE8(char *m) {
    float x[4] __attribute__((aligned(16)));
    float y[4] __attribute__((aligned(16)));
    float z[4] __attribute__((aligned(16)));
    char *v = m + 0x20;
    float f;
    if (D_L00_0015F6B0 & 1) m[8]++;
    f = FastVecDist(m + 0x10, D_0013E633 + 0xEED);
    if (f < 5.0f) {
        char *t = *(char **)(v + 0x18);
        if (0.0f < *(float *)(t + 8)) {
            FastVecSub(y, t, m + 0x10);
            if (0.5f < FastVecLength(y)) {
                func_L00_001FF4B0(y, y, 0.1f / f);
                FastVecAdd(m + 0x10, m + 0x10, y);
            } else {
                func_L00_001FF4B0(y, y, 0.005f);
                func_002158E8(y, (int *)(m + 0x24));
            }
        }
    }
    f = (2.5f - (f - 0.5f)) / 2.5f;
    if (1.0f < f) f = 1.0f;
    else if (f < 0.0f) f = 0.0f;
    *(int *)(m + 4) = FastTweenColor(*(int *)(v + 8), *(int *)(v + 0xC), f);
    if (*(short *)(v + 0x10) != 0) {
        *(volatile int *)0x10000000 = 0;
        load_display_text_resource_entry(x, (int *)v);
        FastVecAdd(m + 0x10, m + 0x10, x);
        f = func_001FA888(*(short *)(m + 0xA));
        f = f / func_001FA888(*(short *)(v + 0x10));
        {
            int c = *(int *)(m + 4);
            *(int *)(m + 4) = FastTweenColor(c & 0xFFFFFF, c, 1.0f - f);
        }
        if (FastDecTimer(m + 0xA)) {
            *(short *)(v + 0x10) = 0;
            *(unsigned short *)(m + 0xA) = *(unsigned short *)(v + 0x12);
        }
    } else if (*(short *)(v + 0x12) != 0) {
        load_display_text_resource_entry(y, (int *)v);
        load_display_text_resource_entry(z, (int *)(v + 4));
        f = func_001FA888(*(short *)(m + 0xA));
        func_001F9C08(x, z, y, f / func_001FA888(*(short *)(v + 0x12)));
        FastVecAdd(m + 0x10, m + 0x10, x);
        if (FastDecTimer(m + 0xA)) {
            *(short *)(v + 0x12) = 0;
            *(unsigned short *)(m + 0xA) = *(unsigned short *)(v + 0x14);
        }
    } else {
        int c;
        load_display_text_resource_entry(x, (int *)(v + 4));
        FastVecAdd(m + 0x10, m + 0x10, x);
        c = *(int *)(m + 4) & 0xFFFFFF;
        f = func_001FA888(*(short *)(m + 0xA));
        f = f / func_001FA888(*(short *)(v + 0x14));
        *(int *)(m + 4) = FastTweenColor(c, *(int *)(m + 4), f);
        if (FastDecTimer(m + 0xA)) KillPart(m);
    }
}
extern unsigned char *D_L00_001B2520;

/* spawns a type-72 particle with a signed spin and a scaled lifetime */
unsigned char *func_L00_00275FF8(char *a, char *b, int c, float f) {
    unsigned char *p = func_00218928(0x48);
    unsigned char *u;
    if (p) {
        qcopy(p + 0x10, a);
        *(int *)(p + 4) = 0x7FFFFFFF;
        p[9] = truncate_float_to_s32(4.0f) + 0x40;
        p[3] = 0x48;
        p[1] = 0;
        if (c >= 0) {
            *(float *)(p + 0xC) = random_float_between(20000.0f, 40000.0f);
        } else {
            *(float *)(p + 0xC) = random_float_between(40000.0f, 80000.0f);
        }
        u = p + 0x20;
        p[8] = random_integer_below(8) + 0x1C;
        p[2] = *D_L00_001B2520;
        *(int *)(u + 0x10) = c;
        qcopy(u, b);
        *(int *)(u + 0x14) = 0;
        *(int *)(u + 0x18) = random_integer_below(0xC) - 6;
        *(float *)(u + 0xC) = f;
        *(float *)(u + 0x1C) = *(float *)(p + 0xC) * 0.1f;
        if (c >= 0) {
            *(float *)(u + 0x1C) = *(float *)(p + 0xC) * 0.05f;
            if (random_integer_below(0x1E) == 0) {
                *(int *)(u + 0x14) = -0x28;
            } else if (random_integer_below(0x1E) == 0) {
                *(int *)(u + 0x14) = -1;
            }
        }
    }
    return p;
}
extern void func_L00_002688A8(void *);
void func_L00_00276180(char *a) {
    *(unsigned char *)(a + 8) = *(unsigned char *)(a + 8) + *(unsigned char *)(a + 0x38);
    if (*(float *)(a + 0xC) <= 0.0f) {
        *(float *)(a + 0xC) = 0.0f;
        KillPart(a);
    }
}
typedef int OvlQuad __attribute__((mode(TI)));
typedef union {
    OvlQuad q;
    float f[4];
} V_275320;
typedef struct {
    unsigned char pad0[0x10];
    V_275320 pos;
    V_275320 vel;
} O_275320;
extern float D_L00_00160310[];
extern float D_L00_00160318 MACRO_ADDR;
extern float D_L00_00160320 MACRO_ADDR;
extern float func_L00_002644E0(void *);
extern void func_L00_00264570(void *);

/* Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/shared/rendering/002712b8.c, FUN_L00_00275320. */
void func_L00_002761C0(O_275320 *o) {
    V_275320 tmp;
    V_275320 t2;
    V_275320 t3;
    V_275320 *vel = &o->vel;
    float h;
    int ix;
    int iy;
    V_275320 *p;

    h = vel->f[3];
    if (o->pos.f[0] < 0.0f || o->pos.f[1] < 0.0f || 512.0f < o->pos.f[0] || 512.0f < o->pos.f[1]) {
        KillPart(o);
        return;
    }
    if (o->pos.f[2] < h) {
        tmp.q = o->pos.q;
        func_L00_00264570(&tmp);
        KillPart(o);
        return;
    }
    tmp.q = o->vel.q;
    ix = o->pos.f[0];
    iy = o->pos.f[1];
    tmp.f[3] = 0.0f;
    FastVecAdd(&o->pos, &o->pos, &tmp);
    FastVecAdd(&o->pos, &o->pos, D_L00_00160310);
    if (ix != (int)o->pos.f[0] || iy != (int)o->pos.f[1]) {
        t2.q = o->pos.q;
        h = func_L00_002644E0(&t2);
        if (h < D_L00_00160320) {
            h = D_L00_00160320;
        } else {
            t3.q = o->pos.q;
            h = func_L00_002644E0(&t3);
        }
        if (o->pos.f[2] < h) {
            t2.q = o->pos.q;
            func_L00_00264570(&t2);
            KillPart(o);
            return;
        }
    }
    tmp.f[0] = 0.0f;
    tmp.f[1] = 0.0f;
    tmp.f[3] = 0.0f;
    tmp.f[2] = -(D_0015EE70 * 0.5f);
    FastVecAdd(vel, &tmp, vel);
    vel->f[3] = h + D_L00_00160318;
}
extern void func_001F9EC0(void *, void *, void *);
extern int func_L00_00237B70(float, int, int);
extern float D_0015EE60 MACRO_ADDR;

/* Update a particle following a parent moby with a scaled offset. */
void func_L00_002763B0(char *m) {
    char *s = m + 0x20;
    char *d = *(char **)(s + 0x1C);
    float t[3];
    float u[3];
    float w[3];
    char *o;
    float q;
    float r;
    int k;
    k = *(int *)(d + 0xC) - *(short *)(m + 0xA);
    r = func_001FA888(*(short *)(d + 8) * k / *(int *)(d + 0xC) + *(short *)(d + 0xA));
    q = D_0015EE60 * -0.01999998f + 1.0f;
    *(float *)(m + 0xC) = r * 1000.0f;
    t[0] = *(float *)(m + 0x20);
    t[1] = *(float *)(s + 4);
    t[2] = *(float *)(s + 8);
    FastVecScale(t, t, q);
    *(float *)(m + 0x20) = t[0];
    *(float *)(s + 4) = t[1];
    *(float *)(s + 8) = t[2];
    o = *(char **)(s + 0xC);
    if (o != 0 && (unsigned char)o[0x20] != 0xFE && (unsigned char)o[0x20] != 0xFD) {
        u[0] = *(float *)(s + 0x10);
        u[1] = *(float *)(s + 0x14);
        u[2] = *(float *)(s + 0x18);
        FastVecAdd(u, u, t);
        *(float *)(s + 0x10) = u[0];
        *(float *)(s + 0x14) = u[1];
        *(float *)(s + 0x18) = u[2];
        func_001F9EC0(w, u, *(char **)(s + 0xC) + 0xC0);
        FastVecAdd(m + 0x10, *(char **)(s + 0xC) + 0x10, w);
    } else {
        KillPart(m);
        return;
    }
    m[8] = m[8] + 1;
    *(int *)(m + 4) = DefaultVtbl_DeleteMoby(
        (float)*(short *)(m + 0xA) / func_001FA888(*(int *)(d + 0xC)),
        *(int *)(d + 4), *(int *)d);
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
    }
}
extern float func_001F9CE8(void *);
extern int func_L00_0025A468_r(void *, void *) __asm__("func_L00_0025A468");
extern float D_0015EE64 MACRO_ADDR;
extern float D_0015EE60 MACRO_ADDR;

/* particle type 75 update: move, damp, then fade or die */
void func_L00_00276590(char *m) {
    char *v = m + 0x20;
    float s;
    float t;
    m[8] += v[0x12];
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(float *)(v + 8) -= D_0015EE64 * 0.003f;
    t = func_001F9CE8(v);
    s = ((t * 0.97f - 1.0f) * D_0015EE60 + 1.0f) / t;
    *(float *)(m + 0x20) *= s;
    *(float *)(v + 4) *= s;
    if (FastDecTimer(m + 0xA) == 0) {
        *(float *)(m + 0xC) += *(float *)(v + 0x14) * 2.0f;
        if (*(float *)(m + 0xC) < 15000.0f) {
            *(float *)(m + 0xC) = 15000.0f;
        }
    } else {
        if (func_L00_0025A468_r(m + 4, *(void **)(v + 0x1C)) != 0) {
            *(int *)(m + 0xC) = 0;
            KillPart(m);
        }
    }
}
extern void func_L00_0025A468(void *, void *);
extern int func_001F9938(void *);
extern short D_L00_00160300;
void func_L00_002766B0(char *a) {
    func_L00_0025A468(a + 4, *(void **)&D_L00_00160300);
    if (FastDecTimer(a + 0xA) != 0) {
        KillPart(a);
    }
}
typedef struct { float x, y, z, w; } Vx __attribute__((aligned(16)));
extern int func_001FA898(float);

void func_L00_00276700(char *m) {
    Vx v;
    float w, t;
    v = *(Vx *)(m + 0x20);
    w = v.w;
    v.w = 0;
    t = func_001FA888(*(short *)(m + 0xA)) / w;
    *(int *)(m + 4) = (truncate_float_to_s32(t * 38.0f) << 24) | 0x808080;
    *(char *)(m + 8) = truncate_float_to_s32(t * 33.0f);
    FastVecAdd(m + 0x10, m + 0x10, &v);
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
    }
}
extern unsigned char *func_L00_0025D390(int);
extern unsigned char *D_L00_001B2538;

/* Spawns a type 78 particle: position, colour, lifetime and mode, with a trailing record of speeds, id and target. Adapted from Lombyte (MIT) for PAL: overlays/shared/rendering_002712b8.c, FUN_L00_00275910. */
unsigned char *func_L00_002767B0(void *pos, int s, int col, int mode, int b, float *vec, int h, float x, float y) {
    unsigned char *m = func_00218928(0x4E);
    if (m) {
        float *v;
        unsigned char *q = m + 0x20;
        qcopy(m + 0x10, pos);
        *(int *)(m + 4) = col;
        m[3] = 0x48;
        m[9] = truncate_float_to_s32(4.0f) + 0x20;
        m[1] = 0;
        m[2] = *D_L00_001B2538;
        *(short *)(m + 0xA) = s;
        *(float *)(m + 0xC) = x * 210000.0f;
        if (mode == 0) {
            m[8] = 0;
        } else if (mode == 1) {
            m[8] = 0x20;
        } else {
            m[8] = random_integer_below(0xFF);
        }
        *(float *)(q + 0) = *(float *)(m + 0xC);
        *(float *)(q + 4) = y * 210000.0f;
        *(short *)(q + 8) = s;
        q[0xA] = b;
        q[0xB] = col >> 24;
        *(int *)(q + 0x18) = h;
        *(float *)(q + 0x1C) = 0;
        if (h) {
            unsigned char *r = func_L00_0025D390(h);
            if (r) *(float *)(q + 0x1C) = *(float *)(r + 0x10);
        }
        v = (float *)(q + 0xC);
        v[0] = vec[0];
        v[1] = vec[1];
        v[2] = vec[2];
    }
    return m;
}
INCLUDE_ASM("asm/overlays", func_L00_00276940);
// Particle update: move by velocity, fade color over remaining lifetime.
void func_L00_00276C08(char *m) {
    char *v = m + 0x20;
    int c;
    if (*(int *)(v + 0x1C) != 0) {
        *(float *)(m + 0x20) += *(float *)(v + 0x10);
        *(float *)(v + 4) += *(float *)(v + 0x14);
        *(float *)(v + 8) += *(float *)(v + 0x18);
        FastVecAdd(m + 0x10, (char *)*(int *)(v + 0x1C) + 0x10, v);
    } else {
        *(float *)(m + 0x10) += *(float *)(v + 0x10);
        *(float *)(m + 0x14) += *(float *)(v + 0x14);
        *(float *)(m + 0x18) += *(float *)(v + 0x18);
    }
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
        return;
    }
    if (*(int *)(v + 0x1C) != 0) {
        c = *(int *)(m + 4) & 0xFFFFFF;
        *(int *)(m + 4) = FastTweenColor(c, *(int *)(m + 4),
            func_001FA888(*(short *)(m + 0xA) - 1) / func_001FA888(*(short *)(m + 0xA)));
    } else {
        *(int *)(m + 4) = FastTweenColor(0, *(int *)(m + 4),
            func_001FA888(*(short *)(m + 0xA) - 1) / func_001FA888(*(short *)(m + 0xA)));
    }
}
/* Per-frame update of a fading particle: kills it when out of range or expired, else fades its colour. */
void func_L00_00276D50(char *m) {
    float a = *(float *)(m + 0x10);
    if (a < 2.0f || a > 1021.0f
        || *(float *)(m + 0x14) < 2.0f || *(float *)(m + 0x14) > 1021.0f
        || *(float *)(m + 0x18) < 2.0f || *(float *)(m + 0x18) > 1021.0f
        || FastDecTimer(m + 0xA) != 0) {
        KillPart(m);
        return;
    }
    if (*(int *)(m + 0x20) != 0) {
        float f;
        *(float *)(m + 0xC) = *(float *)(m + 0xC) * 0.99f;
        f = func_001FA888(*(short *)(m + 0xA) - 1);
        *(int *)(m + 4) = FastTweenColor(0x30FFFFFF, *(int *)(m + 4), f / func_001FA888(*(short *)(m + 0xA)));
    } else {
        float f;
        *(float *)(m + 0xC) = *(float *)(m + 0xC) * 0.95f;
        f = func_001FA888(*(short *)(m + 0xA) - 1);
        *(int *)(m + 4) = FastTweenColor(0x603F1008, *(int *)(m + 4), f / func_001FA888(*(short *)(m + 0xA)));
    }
}
LINKER_REMNANT("asm/overlays", func_L00_00276EB0);
typedef struct { int a; int n; } Ent;
typedef struct { char pad[0xF8]; Ent e[20]; } Tab;
typedef struct { char pad[0x158]; int o[20]; } Out;
extern Tab D_00137C80;
extern Out D_L00_001BA070;
extern int D_L00_00160390;
extern int D_L00_00173F08;
extern int func_002176C8(int, int, int);
extern int func_00234158(int arg0, int arg1, int arg2, int arg3);

// loads the 20 table entries from the resident table into the level's slots
// Adapted from Lombyte (MIT) for PAL: overlays/shared/rendering_002712b8.c, FUN_L00_00276078.
void func_L00_00276F18(void) {
    int h = D_L00_00173F08;
    int i;
    for (i = 0; i < 20; i++) {
        int sz = D_00137C80.e[i].n << 7;
        if (sz) {
            Load(h, D_00137C80.e[i].a, D_00137C80.e[i].n);
            D_L00_001BA070.o[i] = Stash_SendData(h, sz, sz, (int)&D_L00_00160390);
        }
    }
}
