/* Shared code following pause; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_00277208);
INCLUDE_ASM("asm/overlays", func_L00_002777C0);
typedef unsigned int PQ __attribute__((mode(TI), aligned(16)));
typedef union { PQ q; float f[4]; } V;

typedef struct Mth Mth;
typedef struct NO NO;
typedef struct HEnt HEnt;
typedef struct Own Own;
struct Ent3;

struct Mth {
    unsigned char pad0[8];
    void (*f8)(Mth *, int);
    void (*fC)(Mth *, int);
};
struct NO {
    int (*f0)(NO *);
    int f4;
    void (*f8)(NO *, int);
    void (*fC)(NO *, int);
    unsigned char pad10[4];
    HEnt *f14;
};
struct Own {
    int ids[14];
    Own *unk38;
    int unk3C;
    Mth *unk40;
    NO *objs[14];
    unsigned char pad7C[4];
    Mth *unk80;
};
typedef struct {
    int state;
    Own *owner;
    Own *unk8;
    int unkC;
    int unk10;
    int unk14;
    unsigned char pad18[0x28];
    V v40;
    V v50;
    unsigned char pad60[0x70];
    Own *unkD0;
    unsigned char padD4[0x10];
    void *unkE4;
    float unkE8;
    unsigned char padEC[0x104 - 0xEC];
    int unk104;
    int unk108;
    int unk10C;
    int progress;
    unsigned char pad114[0x130 - 0x114];
    int unk130;
    unsigned char pad134[0x140 - 0x134];
    int unk140;
    int unk144;
    int unk148;
    int unk14C;
    int unk150;
    int unk154;
} GS_t;

typedef struct Ent2 { unsigned char pad0[0x48]; struct Ent3 *unk48[1]; } Ent2;
struct Ent3 { unsigned char pad0[0x10]; unsigned char unk10; };
struct HEnt { unsigned char pad0[0x24]; Ent2 *unk24; unsigned char pad28[0x30]; float unk58; };

extern GS_t GS __asm__("D_L00_001BA070");
extern HEnt *D_L00_001BA220[];
extern float D_L00_00166EC0[];
extern Own D_L00_001B7570;
extern Own D_L00_001B8150;
extern Own D_L00_001B8460;
extern Own D_L00_001B6778;
extern Own D_L00_001B7C70;
extern Own D_L00_001B6BA0;
extern char D_L00_001842F0[];
extern char D_001517D0[];
extern char D_0013D390[];
extern int D_0015EFD8 MACRO_ADDR;
extern int D_0015EFB4_m __asm__("D_0015EFB4") MACRO_ADDR;
extern int D_L00_0015F690 MACRO_ADDR;
extern short D_L00_0015F658;
extern short D_L00_001600CC;
extern short D_L00_0015F6AC;
extern int D_L00_0015F6BC MACRO_ADDR;
extern int D_L00_0015F6A8 MACRO_ADDR;
extern float D_L00_0016CBF0;
extern unsigned char D_L00_001E9530[];

extern void func_002348B8(void);
extern void func_L00_00235FF8(int);
extern void func_00205270(int, int);
extern void func_001F2930(void);
extern int func_001E9730();
extern void func_L00_00290030(int);
extern int func_001F9850(int);
extern void func_001F4E08(int);
extern void func_L00_0029A7D0(int);
extern void func_L00_0029A8D0(int);
extern void func_L00_0029A868(int);
extern void func_L00_00299B68(int);
extern void func_L00_0029ADD8(void);
extern void func_0012E558(int);
extern void func_00216F28(void);
extern int func_0012DDC0(void);
extern int func_0022DD68(void); /* sound update: ends in `return 0`, so it returns a value */
extern void func_L00_00277208(void);
extern void func_001FBC80(int, void *, int);
extern void func_L00_00284410(void);
extern void func_0022ED80(int, int, void *);
extern void func_00213D28(void *, int, int);
extern void func_00213C78(void);
extern void func_L00_002777C0(void);

// Page-menu (pause/map/planet-select) per-frame update: state machine over the menu pages.
// Adapted from Lombyte (MIT) for PAL: src/overlays/shared/audio_voices_00276368.c, FUN_L00_00276bd0.
void func_L00_00277A88(void) {
    Own *u8p;
    Mth *m;
    NO *obj;
    int v;
    int i, tmp;
    int flag;
    int k;
    int j;
    NO **objs;
    char *q;

    GS.progress = GS.progress + 1;
    if (GS.progress >= 0x7D01) {
        GS.progress = 0x7D00;
    }
    if (GS.unk148 != 0) {
        GS.unk148 = GS.unk148 - 1;
    }
    q = D_0013D390;
    if (*(int *)(q + 0xDC) < 3 && *(int *)(q + 0xE4) < 0) {
        GS.unk154 = GS.unk154 + 1;
    } else {
        GS.unk154 = 0;
    }
    switch (GS.state) {
    case 2:
    case 0x1A:
    case 0x1E:
    case 0x1F:
        D_L00_0015F690 = 1;
        break;
    }
    if (GS.state == 0x14) {
        if (GS.unk14 != 0) {
            GS.unk14 = GS.unk14 - 1;
            if (GS.unk14 != 0) {
                return;
            }
        }
        if (*(short *)(D_001517D0 + 8) != 0) {
            return;
        }
        *(int *)&D_L00_0015F658 = 0x1E000;
        func_002348B8();
        qcopy(D_L00_00166EC0, &GS.v40);
        qcopy(D_L00_00166EC0 + 4, &GS.v50);
        D_L00_0016CBF0 = GS.unkE8;
        func_L00_00235FF8(0);
        if (GS.unk140 != 0) {
            *(int *)&D_L00_001600CC = -1;
            func_00205270(GS.unk140, GS.unk144);
        }
        UpdateFog();
        D_L00_0015F6BC = 1;
        GS.unk108 = 0;
        GS.unk10C = 0;
        GS.unk104 = 0;
        GS.unk10 = 0;
        if (GS.unkC == 2) {
            char *w = D_L00_001842F0;
            STUB_printf(D_L00_001E9530, *(int *)(w + 0x224));
            func_L00_00290030(*(int *)(w + 0x224));
        } else if (GS.unkC == 3) {
            tmp = D_0015EFD8;
            D_0015EFD8 = 2;
            GS.unk130 = tmp;
            FadeToBlack(scale_ticks(0x10));
            D_L00_0015F6A8 = 0;
            func_L00_0029A7D0((int)GS.unkE4);
        } else if (GS.unkC == 4) {
            tmp = D_0015EFD8;
            D_0015EFD8 = 1;
            GS.unk130 = tmp;
            FadeToBlack(scale_ticks(0x10));
            D_L00_0015F6A8 = 0;
            func_L00_0029A8D0((int)GS.unkE4);
        } else if (GS.unkC == 6) {
            tmp = D_0015EFD8;
            D_0015EFD8 = 1;
            GS.unk130 = tmp;
            FadeToBlack(scale_ticks(0x10));
            D_L00_0015F6A8 = 0;
            func_L00_0029A868((int)GS.unkE4);
        } else if (GS.unkC == 5) {
            tmp = D_0015EFD8;
            D_0015EFD8 = 1;
            GS.unk130 = tmp;
            FadeToBlack(scale_ticks(0x10));
            D_L00_0015F6A8 = 0;
            func_L00_00299B68((int)GS.unkE4);
        } else if (GS.unkC == 7) {
            tmp = D_0015EFD8;
            GS.unk130 = tmp;
            FadeToBlack(scale_ticks(0x10));
            D_L00_0015F6A8 = 0;
            func_L00_0029ADD8();
        } else {
            D_L00_0015F6A8 = 0;
        }
        func_0012E558(0x1D);
        if (GS.unkC != 2) {
            music_Unpause();
        }
        func_0012DDC0();
        sound_update();
        return;
    }
    v = GS.state;
    if (v == 0 || v == 0xA || v == 0xE || v == 0x11 || v == 0x21 || v == 0x2D ||
        v == 0x23) {
        func_L00_00277208();
    }
    if ((D_0015EFB4_m & 1) && !(*(int *)&D_L00_0015F6AC < 8)) {
        func_001FBC80(3, GS.owner, 0);
        return;
    }
    func_L00_00284410();
    if (GS.state == 1) {
        GS.unk14 = (GS.unk14 < 1) ? 0 : GS.unk14 - 1;
        if (GS.unk14 == 0) {
            u8p = GS.unk8;
            GS.unk8 = 0;
            GS.owner = u8p;
            GS.state = u8p->unk3C;
            for (i = 0; i < 14; i++) {
                obj = GS.owner->objs[i];
                if (obj != 0 && obj->f8 != 0) {
                    obj->f8(obj, 0);
                }
            }
            goto L2;
        }
    } else if (GS.unk8 != 0) {
        if (GS.owner == GS.unk8) {
            func_0022ED80(3, 0x11, D_L00_001BA220[0]);
        } else {
            func_0022ED80(4, 0x11, D_L00_001BA220[0]);
        }
        for (i = 0; i < 14; i++) {
            obj = GS.owner->objs[i];
            if (obj != 0 && obj->fC != 0) {
                obj->fC(obj, 0);
            }
        }
        flag = (GS.unk8 == GS.owner->unk38);
        if (GS.owner == GS.unk8 && GS.owner != &D_L00_001B7570 &&
            GS.owner != &D_L00_001B8150 && GS.owner != &D_L00_001B8460 &&
            GS.owner != &D_L00_001B6778 && GS.owner != &D_L00_001B7C70 &&
            GS.owner != &D_L00_001B6BA0) {
            if (GS.state != 0x23) {
                flag = flag ^ 1;
            }
        }
        for (j = 0; j < 14; j++) {
            if (GS.unk8->objs[j] != 0) {
                GS.unk8->objs[j]->f14 = D_L00_001BA220[j];
            }
            if (flag) {
                int n = GS.owner->ids[j];
                HEnt *e = D_L00_001BA220[j];
                func_00213D28(e, n, e->unk24->unk48[n]->unk10 - 1);
                D_L00_001BA220[j]->unk58 = -1.0f;
            } else {
                func_00213D28(D_L00_001BA220[j], GS.unk8->ids[j], 0);
                D_L00_001BA220[j]->unk58 = 1.0f;
            }
        }
        GS.state = 1;
        GS.unk14 = 12;
        GS.unkD0 = GS.owner;
        GS.owner = 0;
    }
L2:
    if (GS.owner != 0) {
        objs = GS.owner->objs;
        for (k = 0; k < 14; k++) {
            if (objs != 0 && objs[k] != 0 && objs[k]->f0 != 0) {
                if (objs[k]->f0(objs[k]) != 0) {
                    GS.unkC = ((unsigned int)(GS.state - 15) < 2) ? 2 : 1;
                }
            }
        }
        if (GS.owner != 0 && GS.owner->unk80 != 0) {
            m = GS.owner->unk40;
            if (m->fC != 0) {
                m->fC(m, 1);
            }
            GS.owner->unk40 = GS.owner->unk80;
            GS.owner->unk80 = 0;
            m = GS.owner->unk40;
            if (m->f8 != 0) {
                m->f8(m, 1);
            }
        }
    }
    func_00213C78();
    sound_update();
    if (GS.unkC != 0) {
        func_L00_002777C0();
    }
}
typedef int u128 __attribute__((mode(TI)));
extern void func_001FB530(void);
extern void func_L00_002A2258(int a, int b, int n);
extern void func_001F3C10(void);
extern void func_001F55C0(int, int, int, int);
extern void func_00234C98(int, long);
extern void func_0020E0C8(void);
extern void func_0020E040(void);
extern void func_0020E068(void);
extern void func_0020E180(int, int);
extern void func_00238D90(void *, void *, int *, int *, int *, int *);
extern void func_00201640(int, int, int, int, long, long);
extern void func_001F7A50(int a, int b, int flag, float f);
extern void func_002017C8(int arg0, int arg1, int arg2, int arg3, long arg4, int arg5, int arg6);
extern void func_001F7B40(void);
extern void func_001F5800(int, int, int, int, int, int, int, int, long, long);
extern void func_0020E098(void);
extern void func_0020E200(void);
extern void func_00234AC8(int);
extern void func_0020DD48(void);
extern void func_001F4630(int);
extern void func_002250B8(int);
extern void func_001F4748(void);
typedef struct PageMenu {
    int state;
    char *owner;
    int unk8;
    int unkC;
    int unk10;
    char pad14[0xC4];
    int unkD8;
} PageMenu;
extern PageMenu PM __asm__("D_L00_001BA070");
extern int D_0015EF84 MACRO_ADDR;
extern int D_0013E15A[];
extern int D_L00_001B2740[];
extern long D_0015EFD0 MACRO_ADDR;
extern int D_L00_00160330 SDATA(D_L00_00160330);
typedef struct PageMobyData {
    u128 row[4];
    char pad40[0x10];
    int x;
    int y;
    int w;
    int h;
} PageMobyData;

/* draws the pause menu pages: lays out each page moby's screen rect, then renders each page's texture */
void func_L00_002781D8(int arg0) {
    u128 c[4];
    u128 pad[5];
    u128 box[2];
    struct {
        int w;
        int h;
        int x;
        int y;
    } rect;
    char **pp;
    int i;
    int k;
    int j;
    int n;
    int pass;
    int flags;

    framebuf_appendLargeSetup();
    pp = 0;
    func_L00_002A2258(PM.unk10, D_0015EF84, *(int *)((char *)D_0013E15A + 0x4AA) << 11);
    if (arg0 != 0) {
        return;
    }
    ResetGsRegisters();
    emit_rgba_draw_packet(0, 0, 0, 0x30);
    if (PM.state == 0x14) {
        return;
    }
    VU1_addGSregister(0x47, 0x5360B);
    DrawMobysSetup();
    InitMobyClassDists();
    StashMobyClassDists();
    for (i = 0; i < 14; i++) {
        if (D_L00_001B2740[i] != 0 && D_L00_001BA220[i] != 0 && (i != 6 || PM.unkD8 != 0)) {
            DrawMobyList((int)D_L00_001BA220[i], 1);
        }
    }
    if (PM.owner != 0) {
        pp = (char **)(PM.owner + 0x44);
    }
    for (k = 0; k < 14; k++) {
        PageMobyData *d;
        if (D_L00_001BA220[k] == 0 || D_L00_001B2740[k] == 0) {
            continue;
        }
        if (k == 6 && PM.unkD8 == 0) {
            continue;
        }
        d = *(PageMobyData **)((char *)D_L00_001BA220[k] + 0x78);
        qcopy(&c[0], d);
        qcopy(&c[1], &d->row[1]);
        qcopy(&c[2], &d->row[2]);
        qcopy(&c[3], &d->row[3]);
        box[0] = c[0];
        box[1] = c[3];
        func_00238D90(&box[0], &box[1], &rect.w, &rect.h, &rect.x, &rect.y);
        flags = rect.w;
        rect.x++;
        rect.y++;
        if (pp != 0 && pp[k] != 0) {
            *(int *)(pp[k] + 0x20) = flags;
            *(int *)(pp[k] + 0x24) = rect.h;
            *(int *)(pp[k] + 0x18) = rect.x;
            *(int *)(pp[k] + 0x1C) = rect.y;
        }
        d->x = rect.x;
        d->y = rect.y;
        d->w = rect.w;
        d->h = rect.h;
        func_00201640(rect.x + 1, rect.y + 1, rect.x + rect.w - 1, rect.y + rect.h - 1, D_L00_00160330, 0);
    }
    for (pass = 0; pass < 2; pass++) {
        HEnt **mobys = D_L00_001BA220;
        for (j = 0; j < 14; j++) {
            char *m = (char *)mobys[j];
            int pw, ph, px, py;
            int tw, th, su, sv;
            int r, u, v, u1, v1;
            char *d;
            if (m == 0 || pp == 0 || pp[j] == 0) {
                continue;
            }
            flags = *(int *)(pp[j] + 0x10);
            if (flags & 4) {
                continue;
            }
            if (D_L00_001B2740[j] == 0 || *(int *)(pp[j] + 4) == 0) {
                continue;
            }
            if (j == 6 && PM.unkD8 == 0) {
                continue;
            }
            if (pass == 0 && !(flags & 2)) {
                continue;
            }
            if (pass == 1 && (flags & 2)) {
                continue;
            }
            if (flags & 1) {
                (*(int (**)(char *))(pp[j] + 4))(pp[j]);
                continue;
            }
            d = *(char **)(m + 0x78);
            px = *(int *)(d + 0x50);
            py = *(int *)(d + 0x54);
            pw = *(int *)(d + 0x58);
            ph = *(int *)(d + 0x5C);
            tw = 7;
            while ((1 << tw) < pw) {
                tw++;
            }
            th = 7;
            while ((1 << th) < ph) {
                th++;
            }
            while (tw + th >= 18) {
                th--;
            }
            func_001F7A50(tw, th, pass != 0, 1.0f);
            su = 1 << tw;
            sv = 1 << th;
            func_002017C8(0, 0, su, sv, D_L00_00160330, 0, 0);
            r = (*(int (**)(char *))(pp[j] + 4))(pp[j]);
            func_001F7B40();
            VU1_addGSregister(0x42, 0x8000000064L);
            VU1_addGSregister(0x47, 0x43);
            if (r & 1) {
                continue;
            }
            u = 0;
            u1 = su;
            v = 0;
            v1 = sv;
            if (r & 2) {
                u1 = pw;
                v1 = ph;
            } else if (r & 8) {
                u = (u1 - pw) / 2;
                v = (v1 - ph) / 2;
                u1 -= u;
                v1 -= v;
                if (u < 0) {
                    u = 0;
                }
                if (v < 0) {
                    v = 0;
                }
                if (u1 > su) {
                    u1 = su;
                }
                if (v1 > sv) {
                    v1 = sv;
                }
            } else if (r & 4) {
                if (pw < ph) {
                    u = u1 / 2 - (pw * u1) / (ph * 2);
                    u1 -= u;
                } else {
                    v = v1 / 2 - (ph * v1) / (pw * 2);
                    v1 -= v;
                }
            } else if (!(r & 0x10)) {
                continue;
            }
            DrawTexturedQuad(px, py, pw, ph, u, v, u1 - u, v1 - v, 0x80808080L, D_0015EFD0);
        }
        if (pass == 0) {
            RestoreMobyClassDists();
            DrawMobysCleanUp();
            VU1_syncChain(0x10);
            PatchMobyGifs();
        }
    }
    SetupGifPaging(0);
    for (n = 0; n < 14; n++) {
        if (D_L00_001B2740[n] != 0 && (n != 6 || PM.unkD8 != 0)) {
            func_002250B8((int)D_L00_001BA220[n]);
        }
    }
    DoGifPaging();
}
LINKER_REMNANT("asm/overlays", func_L00_002788C8);
INCLUDE_ASM("asm/overlays", func_L00_002788E0);
INCLUDE_ASM("asm/overlays", func_L00_00278904);
INCLUDE_ASM("asm/overlays", func_L00_00278930);
INCLUDE_ASM("asm/overlays", func_L00_0027895C);
extern char D_L00_001BA070[] NOT_SDA;

// Skips the linked menu entries the two active pause filters exclude and, if it moved, makes the entry it stopped on the current one.
int func_L00_0027A398(char *arg0, int arg1) {
    int ok = 0;
    int found = 0;

    if (arg1 != 0) {
        return 0;
    }
    {
        char *g = D_L00_001BA070;
        if (*(int *)(g + 0x134) != 0 && (*(int *)(arg0 + 0x30) & 8)) {
            ok = 1;
        }
        if (*(int *)(g + 0x138) != 0 && (*(int *)(arg0 + 0x30) & 4)) {
            ok = 1;
        }
    }
    while (ok) {
        char *g = D_L00_001BA070;
        found = 1;
        arg0 = *(char **)(arg0 + 0x4C);
        ok = 0;
        if (*(int *)(g + 0x134) != 0 && (*(int *)(arg0 + 0x30) & 8)) {
            ok = 1;
        }
        if (*(int *)(g + 0x138) != 0 && (*(int *)(arg0 + 0x30) & 4)) {
            ok = 1;
        }
    }
    if (found) {
        char *g2 = D_L00_001BA070;
        *(char **)(*(char **)(g2 + 4) + 0x80) = arg0;
    }
    return 0;
}
INCLUDE_ASM("asm/overlays", func_L00_0027A3AC);
INCLUDE_ASM("asm/overlays", func_L00_0027D3D8);
INCLUDE_ASM("asm/overlays", func_L00_0027D454);
INCLUDE_ASM("asm/overlays", func_L00_0027D464);
INCLUDE_ASM("asm/overlays", func_L00_00280708);
extern unsigned char D_0013A5E0[] NOT_SDA;
extern char D_L00_001BA070[] NOT_SDA;
int func_L00_00280740(void) {
    int f = *(int *)(D_0013A5E0 + 0x2604);
    if (f & 0x20) {
        char *p = D_L00_001BA070;
        char *q;
        *(int *)(p + 0xD4) = 0;
        q = *(char **)(p + 4);
        *(int *)(p + 8) = *(int *)(q + 0x38);
        *(int *)(q + 0x84) = 1;
    } else if (f & 0x10) {
        char *p = D_L00_001BA070;
        char *q = *(char **)(p + 4);
        *(int *)(p + 8) = *(int *)(q + 0x38);
        *(int *)(q + 0x84) = 0;
    }
    return 0;
}
INCLUDE_ASM("asm/overlays", func_L00_00284410);
extern void *func_00226720_a(int) __asm__("func_00226720");
extern int func_00226EA8(int);
extern void func_001E9768(void *);
extern char D_L00_00166D80[];

/* sets up a pause-menu helper moby in front of the camera */
int func_L00_00284620(char *h) {
    char *m;
    int r;
    m = func_00226720_a(0x7A5);
    *(int *)(h + 0x34) = 0;
    if (m != 0) {
        char *d;
        char *g = D_L00_00166D80;
        *(char **)(h + 0x44) = m;
        *(short *)(m + 0x34) = 0;
        *(float *)(m + 0x10) = *(float *)(g + 0x140) + 2.2f;
        *(float *)(m + 0x14) = *(float *)(g + 0x144) + 0.0f;
        *(float *)(m + 0x18) = *(float *)(g + 0x148) + -1.6f;
        d = *(char **)(m + 0x78);
        *(void **)(m + 0x74) = func_001E9768;
        *(float *)(m + 0x48) = 3.1415927f;
        *(char **)d = h;
        *(int *)(d + 4) = 0;
        *(int *)(d + 8) = 0;
    } else {
        *(int *)(h + 0x34) = 3;
    }
    r = func_00226EA8(1);
    *(int *)(h + 0x3C) = r;
    if (r == 0) {
        *(int *)(h + 0x34) = 3;
    }
    return 0;
}
extern int D_L00_001BA548[];
// Finds one of five entries and returns its flag-selected size.
int func_L00_00284E20(int id) {
    int *p = D_L00_001BA548;
    int i;
    for (i = 0; i < 5; i++, p += 2) {
        if (p[0] == id) {
            int result = 0x11800;
            if (p[1] & 1) result = 0x4F000;
            return result;
        }
    }
    return -1;
}
INCLUDE_ASM("asm/overlays", func_L00_00284E5C);
INCLUDE_ASM("asm/overlays", func_L00_00284E70);
INCLUDE_ASM("asm/overlays", func_L00_00284EA0);
INCLUDE_ASM("asm/overlays", func_L00_00284EB8);
typedef struct { int f[14]; } Rec;
extern int D_L00_001604D0 MACRO_ADDR;
extern Rec D_L00_001BA350[];

/* appends one 13-argument record to the queue of 8 entries; returns 0, or -1 when full */
int func_L00_00285698(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7, int s0, int s1, int s2, int s3, int s4) {
    int n = D_L00_001604D0;
    Rec *r;
    if (n >= 8) {
        return -1;
    }
    D_L00_001604D0 = n + 1;
    r = &D_L00_001BA350[n];
    r->f[1] = a0;
    r->f[2] = a1;
    r->f[3] = a2;
    r->f[4] = a3;
    r->f[5] = a4;
    r->f[6] = a5;
    r->f[7] = a6;
    r->f[8] = a7;
    r->f[9] = s0;
    r->f[10] = s1;
    r->f[11] = s2;
    r->f[0] = 0;
    r->f[12] = s3;
    r->f[13] = s4;
    return 0;
}
INCLUDE_ASM("asm/overlays", func_L00_00286068);
extern void func_L00_001FF040(int, void *, unsigned short);

/* level data, not declared anywhere else yet */
typedef struct { unsigned char h[0x404]; unsigned char f[0x7FF]; } B_00284e50;
extern B_00284e50 D_L00_001BA9B0;
extern B_00284e50 D_L00_001BB610;
extern int D_L00_001BA860[];
extern char D_0013F450[];
extern char D_0013E650[];
extern char D_001517D0[];
extern unsigned char D_0014C150[][16] NOT_SDA;
extern int D_0014C290[][64] NOT_SDA;
extern unsigned char D_L00_001BB5C0[0xC58];

/* core data, big blobs addressed with lui/addiu, never through $gp */
extern unsigned char D_0014171B NOT_SDA;
extern unsigned char D_0013E633 NOT_SDA;
extern int D_0015EE84_m __asm__("D_0015EE84") MACRO_ADDR;

/* Seeds the pause-menu snapshot: copies the header, marks valid entries in the bitmasks, fills the state record. Adapted from Lombyte (MIT) for PAL: overlays/shared/gameplay_state_00284e50.c, FUN_L00_00284e50. */
void func_L00_00286128(void *a0, void *a1)
{
    unsigned char *src;
    int i;
    int lvl;
    char *g;

    func_L00_001FF040((int)&D_L00_001BB610, &D_L00_001BA9B0, 0x404);
    lvl = D_0015EE84_m;
    for (src = D_L00_001BA9B0.f, i = 0; i < 0x7FF; i++, src++) {
        int v = *src;
        if ((unsigned char)v == 0) continue;
        if ((unsigned char)v != 1 && D_0014C150[lvl][(unsigned char)v - 2] != 0xFF) continue;
        D_L00_001BB610.f[i] = v;
        D_0014C290[lvl][i >> 5] |= 1 << (i & 0x1F);
        D_L00_001BA860[i >> 5] |= 1 << (i & 0x1F);
    }
    g = (char *)D_L00_001BB5C0;
    *(int *)g = 1;
    qcopy(g + 0x10, a0);
    qcopy(g + 0x20, a1);
    {
        char *hero = D_0013F450;
        char *stat = D_0013E650;
        char *fb = D_001517D0;
        char *p = *(char **)(hero + 0x2080);
        signed char v = *(signed char *)(fb + 0x22);

        *(int *)(g + 0x30) = *(int *)((char *)p + 0x38);
        *(int *)(g + 0x34) = *(int *)((char *)p + 0x3C);
        *(int *)(g + 0x38) = *(int *)((char *)p + 0x80);
        *(int *)(g + 0x44) = *(unsigned char *)(hero + 0x20A4);
        *(int *)(g + 0x48) = (int)p;
        *(int *)(g + 0x4C) = *(short *)(hero + 0x22CC);
        *(int *)(g + 0x3C) = *(int *)(stat + 0x64);
        *(unsigned char *)(g + 0x40) = *(unsigned char *)(stat + 0x68);
        *(unsigned char *)(g + 0x41) = *(unsigned char *)(stat + 0x69);
        *(unsigned char *)(g + 0x42) = *(unsigned char *)(stat + 0x6A);
        if (v != -1) {
            *(int *)(g + 0xC54) = v;
        } else {
            *(int *)(g + 0xC54) = *(short *)(fb + 0x38);
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L00_002862E0);
INCLUDE_ASM("asm/overlays", func_L00_00286498);
INCLUDE_ASM("asm/overlays", func_L00_002864CC);
typedef struct { int off; int pad; unsigned short len; short kind; short a; short b; } Ent;
extern int func_L00_00286498(int, int);
extern void func_L00_001FF040(int, void *, unsigned short);

void func_L00_002864E0(int *h) {
    int i;

    for (i = 0; i < *h; i++) {
        int m = func_L00_00286498(((Ent *)(h + 1))[i].b, ((Ent *)(h + 1))[i].a);
        if (m != 0) {
            int dst;
            if (((Ent *)(h + 1))[i].kind == 1) {
                dst = ((Ent *)(h + 1))[i].off + m;
            } else {
                dst = ((Ent *)(h + 1))[i].off + *(int *)(m + 0x78);
            }
            func_L00_001FF040(dst, &((Ent *)(h + 1))[i].pad, ((Ent *)(h + 1))[i].len);
        }
    }
}
