/* Shared code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

extern char *func_0020D348(int);
extern int func_001F9850(int);
extern float func_L00_001FF860(float, float);
extern float func_001F9CE8(void *);

// Creates a class 0x31 moby that looks along a direction, copying owner data and position.
char *func_L16_002A1B58(char *owner, float *pos, char *vec) {
    char *moby = CreateMoby(0x31);
    if (moby != 0) {
        char *data;
        float a;
        float b;
        ((unsigned char *)moby)[0x30] = 0xFF;
        *(short *)(moby + 0x32) = 0xFF;
        moby[0x31] = 1;
        moby[0x20] = 0;
        *(unsigned long *)(moby + 0x38) = *(unsigned long *)(owner + 0x38);
        *(float *)(moby + 0x2C) = *(float *)(moby + 0x2C) * 3.0f;
        qcopy(moby + 0x10, vec);
        data = *(char **)(moby + 0x78);
        qcopy(data, pos);
        *(int *)(data + 0x14) = scale_ticks(0xF0);
        *(char **)(data + 0x18) = owner;
        *(int *)(data + 0x10) = 0;
        *(float *)(moby + 0x48) = func_L00_001FF860(pos[0], pos[1]);
        a = func_001F9CE8(pos);
        b = func_L00_001FF860(a, pos[2]);
        *(float *)(moby + 0x44) = -b;
        moby[0x31] = 0;
        *(unsigned short *)(moby + 0x34) |= 1;
    }
    return moby;
}
extern float func_001F9D10_2E7198(void*,void*) __asm__("func_001F9D10");
extern int func_L00_0028EF68(int,int,int,int);
extern void func_L15_0029BFF8(char*);
extern void func_001F9BF0(void*,void*,void*);
extern float func_L00_001FF860(float,float);
extern float func_001F9CE8(void*);
extern float func_001FA748(float,float);
extern void func_00215C00(void*,float,float,float);
extern int func_001F9908(int*);
extern float func_001FA888(int);
extern void func_001F9C08(void*,void*,void*,float);
extern void func_001F9BD8(void*,void*,void*);
extern int func_L00_001EFFF0(void*,void*,int,void*,void*);
extern float func_001F9CB8(void*);
extern void func_L00_0025A8E8(int,float,void*,int,float,float,int,int,int);
extern void func_L00_0025F4A8(void*,void*,void*,float,float,int,int,int,float,float,float,int,float,float,int,int,int,int);
extern void func_0020D678(void*);
extern char D_L16_00167240[],D_0013E633[];
/* Steer a projectile toward its target and emit its impact effects. */
void func_L16_002A1C50(char *m) {
    float desired[4],next[4],delta[4],blend[4];
    char *d=*(char**)(m+0x78);
    void *remaining;
    float yaw,pitch;
    if(*(int*)(d+0x34)==0 && func_001F9D10_2E7198(m+0x10,D_L16_00167240)<15.0f) {
        *(int*)(d+0x34)=1;func_L00_0028EF68(5,0,(int)m,0x54C);
    }
    if(*(unsigned char*)(m+0x20)!=0) return;
    func_L15_0029BFF8(m);
    func_001F9BF0(delta,d+0x10,m+0x10);
    yaw=func_L00_001FF860(delta[0],delta[1]);
    pitch=func_L00_001FF860(func_001F9CE8(delta),delta[2]);
    yaw=func_001FA748(yaw,*(float *)(d+0x28));
    pitch=func_001FA748(pitch,*(float *)(d+0x2C));
    if(pitch>1.2217305f) pitch=1.2217305f;
    else if(pitch<-1.2217305f) pitch=-1.2217305f;
    func_00215C00(desired,*(float *)(d+0x24),yaw,pitch);
    if(func_001F9908((int*)(d+0x20))==0) {
        float a=func_001FA888(*(int*)(d+0x20));
        float b=func_001FA888(*(int*)(d+0x30));
        func_001F9C08(blend,desired,d,a/b);
        func_001F9BD8(next,m+0x10,blend);
        *(float *)(m+0x48)=func_L00_001FF860(blend[0],blend[1]);
        *(float *)(m+0x44)=-func_L00_001FF860(func_001F9CE8(blend),blend[2]);
    } else {
        func_001F9BD8(next,m+0x10,desired);
        *(float *)(m+0x48)=yaw;*(float *)(m+0x44)=pitch;
    }
    remaining=delta;
    if(func_L00_001EFFF0((m+0x10),next,0,m,0)!=0 || func_001F9CB8(remaining)<*(float *)(d+0x24)) {
        if(*(unsigned char*)(D_0013E633+0x2EC1)==2) func_L00_0025A8E8((int)m,2.0f,(m+0x10),3,2.0f,1.0f,0,1,0);
        func_L00_0028EF68(4,0,(int)m,0x54C);
        func_L00_0025F4A8(m,d,(m+0x10),4.0f,4.0f,10,3,16,4.0f,2.0f,9.0f,-1,1.0f,15.0f,1,1,-1,0);
        func_0020D678(m);
    } else qcopy((m+0x10),next);
}
extern struct Moby *func_0020D348_m(int) __asm__("func_0020D348");
extern float func_001F9CB8(void *);
extern float func_002140F8(float, float);
extern short D_L16_001614A8;
extern short D_L16_001614AC;

/* spawn a moby of class 0x32 thrown along a vector with random spin */
char *func_L16_002A1F78(char *owner, char *vec, void *pos, void *vel, int c) {
    char *m = (char *)func_0020D348_m(0x32);
    char *d;
    float len, x, t, y;
    if (m) {
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0xFF;
        m[0x31] = 1;
        m[0x20] = 0;
        *(long *)(m + 0x38) = *(long *)(owner + 0x38);
        *(float *)(m + 0x2C) = *(float *)(m + 0x2C) * 3.0f;
        qcopy(m + 0x10, pos);
        d = *(char **)(m + 0x78);
        qcopy(d, vec);
        qcopy(d + 0x10, vel);
        *(int *)(d + 0x30) = c;
        *(int *)(d + 0x20) = c;
        len = FastVecLength(vec);
        x = *(float *)&D_L16_001614A8;
        *(float *)(d + 0x24) = len;
        t = random_float_between(-x, x) * 0.017453292f;
        y = *(float *)&D_L16_001614AC;
        *(float *)(d + 0x28) = t;
        *(float *)(d + 0x2C) = random_float_between(0.0f, y) * 0.017453292f;
        *(int *)(d + 0x34) = 0;
        *(float *)(m + 0x48) = func_L00_001FF860(*(float *)vec, *(float *)(vec + 4));
        *(float *)(m + 0x44) = -func_L00_001FF860(func_001F9CE8(vec), *(float *)(vec + 8));
        m[0x31] = 0;
        *(unsigned short *)(m + 0x34) |= 1;
    }
    return m;
}
extern void func_L16_002D4C78(char *);
extern void func_L00_00264BB0(void *, float);
extern float func_00214158(void);
extern float func_001F9878(float);
extern int func_001FA898(float);
extern int func_002140B0(int);
extern void func_001F9EC0(void *, void *, void *);
extern void func_001F9BD8(void *, void *, void *);
extern void func_001F9BF0(void *, void *, void *);
extern float func_001FA748(float, float);
extern int func_001F9938(void *);
extern void func_L00_001FF4B0(void *, void *, float);
extern float func_L16_002D5280_update(char *, void *, int) __asm__("func_L16_002D5280");
extern float func_L00_0025CE58(float *, float *, float, float, float, float);
extern void func_00213DE0(void *, int, int, int);
extern void func_L16_002D5438(char *);
extern int func_00215B18(char *, float);
extern void func_L00_00250800(void *, int, void *);
extern char *func_L16_002A1B58(char *, float *, char *);
extern int func_L00_0025D6F0(void *, void *);
extern int func_0022ED80_update(int, int, void *) __asm__("func_0022ED80");
extern void func_0020D678(void *);
extern float func_00214D28(float *, float, float);
extern float func_001F9FA8(float);
extern float func_001F9D10_update(void *, void *) __asm__("func_001F9D10");
extern int func_L00_0028EB98(void *, int);
extern char D_0013E633[];
extern unsigned char D_0015EEB4_update[4] __asm__("D_0015EEB4") MACRO_ADDR;
extern float D_0015EE6C MACRO_ADDR;
extern float D_0015EE70 MACRO_ADDR;
extern int D_0015EE84 MACRO_ADDR;
extern int D_L16_0015F6A8 MACRO_ADDR;
extern int D_L16_0016CD10;
extern char *D_L16_001B0C30[];
extern char D_L16_00167240[];
extern short D_L16_00161B34;
extern short D_L16_00161B38;
extern short D_L16_00161B3C;

/* Update the floating enemy's patrol, attack and death states. */
void func_L16_002D40B8(char *m) {
    float target[4], temp[4], delta[4];
    char *d = *(char **)(m + 0x78);
    char *source, *owner;
    float distance, angle;
    float *heading, *movement;
    int ticks;
    int cls;
    func_L16_002D4C78(m);
    owner = *(char **)(d + 0x110);
    cls = *(short *)(owner + 0xA6);
    if (cls == 0 || cls == 0x1A3) {
        qcopy(target, D_0013E633 + 0xEDD);
    } else {
        qcopy(target, owner + 0x10);
    }
    if (D_0015EEB4_update[3]) func_L00_00264BB0(d + 0x130, 2.5f);
    switch (((unsigned char *)m)[0x20]) {
    case 0:
        *(int *)(d + 0x2EC) = 0;
        d[0x29] = 1;
        *(short *)(d + 0x24) = 3;
        d[0x28] = 2;
        *(float *)(d + 0x30) = 1.5f;
        *(float *)(d + 0x20) = 3.0f;
        *(float *)(d + 0x2F4) = func_00214158();
        *(float *)(d + 0x2FC) = func_00214158();
        *(float *)(d + 0x2E8) = func_00214158();
        *(float *)(d + 0x2F0) = func_002140F8(90.0f, 180.0f) * 0.017453292f * D_0015EE6C;
        *(float *)(d + 0x2F8) = func_002140F8(90.0f, 180.0f) * 0.017453292f * D_0015EE6C;
        *(float *)(d + 0x2E4) = func_002140F8(90.0f, 180.0f) * 0.017453292f * D_0015EE6C;
        *(short *)(d + 0x302) = func_001FA898(func_001F9878(func_002140F8(180.0f, 360.0f)));
        if (func_002140B0(2)) *(unsigned short *)(m + 0x34) |= 0x8000;
        else *(unsigned short *)(m + 0x34) &= 0x7FFF;
        {
            char *position = m + 0x10;
            if (*(int *)(d + 0x120) >= 0) {
                int node = func_001FA898(func_002140F8(0.0f, (float)(*(int *)D_L16_001B0C30[*(int *)(d + 0x120)] - 1)));
                *(short *)(d + 0x300) = node;
                qcopy(position, D_L16_001B0C30[*(int *)(d + 0x120)] + (short)node * 16 + 0x10);
            }
            *(int *)(d + 0x308) = 1;
            qcopy(d + 0x2C0, position);
            qcopy(d + 0x2B0, position);
        }
        if (*(int *)(d + 0x128)) {
            m[0x20] = 10;
            m[0x31] = 0;
            *(unsigned short *)(m + 0x34) = (*(unsigned short *)(m + 0x34) | 1) & 0xEFFF;
            *(int *)(m + 0x94) = 0;
            if (((unsigned char *)m)[0x53] != 1) {
                func_00213DE0(m, 1, 0, func_001F9850(20));
            }
        } else goto idle;
        break;
    case 10:
        if (*(char **)(d + 0x2D0)) {
            m[0x31] = 1;
            *(unsigned short *)(m + 0x34) &= 0xFFFE;
            movement = temp;
            func_001F9EC0(movement, d + 0x2C0, *(char **)(d + 0x2D0) + 0xC0);
            func_001F9BD8(m + 0x10, movement, *(char **)(d + 0x2D0) + 0x10);
            *(float *)(m + 0x48) = func_001FA748(*(float *)(*(char **)(d + 0x2D0) + 0x48), *(float *)(d + 0x2CC));
        }
        break;
    case 1:
        if (!func_001F9938(d + 0x2DC)) {
            func_L00_001FF4B0(temp, m + 0xC0, *(short *)(d + 0x2DC) * 0.1f);
            func_001F9BD8(temp, temp, m + 0x10);
            func_L16_002D5280_update(m, temp, 1);
        } else {
            heading = (float *)(m + 0x48);
            angle = func_L00_001FF860(*(float *)(d + 0x2B0) - *(float *)(m + 0x10), *(float *)(d + 0x2B4) - *(float *)(m + 0x14));
            func_L00_0025CE58(heading, (float *)(d + 0x2D8), angle, D_0015EE70 * 12.566371f, D_0015EE70 * 12.566371f, D_0015EE6C * 12.566371f);
            distance = func_L16_002D5280_update(m, d + 0x2B0, 1);
            if (((unsigned char *)m)[0x53] != 0) func_00213DE0(m, 0, 0, func_001F9850(10));
            if (distance < 1.0f) m[0x20] = 2;
        }
        break;
    case 2:
        func_001F9938(d + 0x2DC);
        if (*(int *)(d + 0x114) != 2) {
            if (*(short *)(d + 0x2DC) == 0) {
                if (*(int *)(d + 0x120) >= 0) {
                    m[0x20] = 7;
                    *(short *)(d + 0x2DC) = func_001FA898(func_001F9878(func_002140F8(30.0f, 90.0f)));
                    *(short *)(d + 0x300) = (*(short *)(d + 0x300) + 1) % 2;
                    func_L16_002D5438(m);
                } else if (!func_002140B0(20)) {
                    m[0x20] = 4;
                    if (((unsigned char *)m)[0x53] != 2) { func_00213DE0(m, 2, 0, func_001F9850(10)); }
                }
            }
        } else if (func_001F9938(d + 0x302)) {
            if (*(int *)(d + 0x120) >= 0) {
                *(short *)(d + 0x300) = (*(short *)(d + 0x300) + 1) % 2;
                m[0x20] = 3;
                *(short *)(d + 0x302) = func_001F9850(180);
                func_L16_002D5438(m);
            }
        }
        break;
    case 3: {
        float path_distance = func_L16_002D5280_update(m, D_L16_001B0C30[*(int *)(d + 0x120)] + (*(short *)(d + 0x300) * 16 + 0x10), 1);
        if (path_distance < 0.01f) {
            m[0x20] = 2;
            if (((unsigned char *)m)[0x53] != 0) func_00213DE0(m, 0, 0, func_001F9850(10));
            *(short *)(d + 0x302) = func_001FA898(func_001F9878(func_002140F8(180.0f, 360.0f)));
        } else if (func_001F9938(d + 0x302)) {
            m[0x20] = 2;
            if (((unsigned char *)m)[0x53] != 0) func_00213DE0(m, 0, 0, func_001F9850(10));
            *(short *)(d + 0x302) = func_001FA898(func_001F9878(func_002140F8(180.0f, 360.0f)));
        }
        if (*(float *)(d + 0x2D4) < 2.0f * D_0015EE6C && path_distance < 0.5f) {
            if (((unsigned char *)m)[0x53] != 0) { ticks = 30; goto animate_idle; }
        }
        break;
    }
    case 4:
        heading = (float *)(m + 0x48);
        angle = func_L00_001FF860(target[0] - *(float *)(m + 0x10), target[1] - *(float *)(m + 0x14));
        func_L00_0025CE58(heading, (float *)(d + 0x2D8), angle, D_0015EE70 * 12.566371f, D_0015EE70 * 12.566371f, D_0015EE6C * 12.566371f);
        if (((unsigned char *)m)[0x70] & 2) {
            m[0x20] = 5;
            if (((unsigned char *)m)[0x53] != 3) { func_00213DE0(m, 3, 0, func_001F9850(10)); }
        }
        break;
    case 5:
        heading = (float *)(m + 0x48);
        angle = func_L00_001FF860(target[0] - *(float *)(m + 0x10), target[1] - *(float *)(m + 0x14));
        func_L00_0025CE58(heading, (float *)(d + 0x2D8), angle, D_0015EE70 * 12.566371f, D_0015EE70 * 12.566371f, D_0015EE6C * 12.566371f);
        if (func_00215B18(m, 2.0f) || func_00215B18(m, 17.0f) || func_00215B18(m, 32.0f)) {
            func_L00_00250800(m, 0, temp);
            func_001F9BF0(delta, target, temp);
            func_L00_001FF4B0(delta, delta, D_0015EE6C * 20.0f);
            func_L16_002A1B58(m, delta, (char *)temp);
        } else if (func_00215B18(m, 10.0f)) {
            int count = *(unsigned short *)(d + 0x2DE) + 1;
            *(unsigned short *)(d + 0x2DE) = count;
            if ((short)count >= 3) {
                m[0x20] = 2;
                if (((unsigned char *)m)[0x53] != 0) func_00213DE0(m, 0, 0, func_001F9850(10));
                *(short *)(d + 0x2DC) = func_001F9850(60);
                *(unsigned short *)(d + 0x2DE) = 0;
            }
        }
        break;
    case 7:
        distance = func_L16_002D5280_update(m, D_L16_001B0C30[*(int *)(d + 0x120)] + (*(short *)(d + 0x300) * 16 + 0x10), 1);
        func_001F9938(d + 0x2DC);
        if (distance < 0.01f || *(short *)(d + 0x2DC) == 0) {
            m[0x20] = 4;
            if (((unsigned char *)m)[0x53] != 2) func_00213DE0(m, 2, 0, func_001F9850(30));
        }
        if (distance < 0.5f && *(float *)(d + 0x2D4) < 2.0f * D_0015EE6C) {
            if (((unsigned char *)m)[0x53] != 2) { func_00213DE0(m, 2, 0, func_001F9850(30)); }
        }
        break;
    case 8:
        if (((unsigned char *)m)[0x70] & 2) {
idle:
            m[0x20] = 2;
            if (((unsigned char *)m)[0x53] != 0) { ticks = 10;
animate_idle:
                func_00213DE0(m, 0, 0, func_001F9850(ticks));
            }
        } else {
            func_L00_001FF4B0(temp, m + 0xC0, -D_0015EE6C);
            func_001F9BD8(m + 0x10, m + 0x10, temp);
        }
        break;
    case 9:
        {
            char *position;
            movement = temp;
            position = m + 0x10;
            qcopy(movement, position);
            if (func_L00_0025D6F0(m, d + 0x70) & 0x160) {
                func_L16_002D55C0(m, position);
                func_0022ED80_update(0, 0, m);
                func_0020D678(m);
                return;
            }
            func_001F9BF0(movement, position, movement);
            func_001F9BD8(d + 0x2C0, d + 0x2C0, movement);
        }
        break;
    case 6:
    default:
        break;
    }
    if (*(int *)&D_L16_00161B34) {
        *(float *)(d + 0x2BC) = *(float *)(m + 0x18);
        if (((unsigned char *)m)[0x20] != 0 && ((unsigned char *)m)[0x20] != 10) {
            func_00214D28((float *)(d + 0x2EC), 0.25f, D_0015EE6C * 0.25f);
            *(float *)(d + 0x2F4) = func_001FA748(*(float *)(d + 0x2F4), *(float *)(d + 0x2F0));
            *(float *)(d + 0x2FC) = func_001FA748(*(float *)(d + 0x2FC), *(float *)(d + 0x2F8));
            *(float *)(d + 0x2E8) = func_001FA748(*(float *)(d + 0x2E8), *(float *)(d + 0x2E4));
            *(float *)(m + 0x10) = *(float *)(d + 0x2C0) + *(float *)(d + 0x2EC) * func_001F9FA8(*(float *)(d + 0x2F4));
            *(float *)(m + 0x14) = *(float *)(d + 0x2C4) + *(float *)(d + 0x2EC) * func_001F9FA8(*(float *)(d + 0x2FC));
            *(float *)(m + 0x18) = *(float *)(d + 0x2C8) + *(float *)(d + 0x2EC) * func_001F9FA8(*(float *)(d + 0x2E8));
        }
        if (func_001F9D10_update(m + 0x10, D_L16_00167240) < 32.0f && !func_L00_0028EB98(m, *(int *)(d + 0x304)))
            *(int *)(d + 0x304) = func_0022ED80_update(7, 4, m);
    }
    if (*(int *)&D_L16_00161B38) func_L16_002D5958(m);
    if (*(int *)&D_L16_00161B3C && *(int *)(D_0013E633 + 0x2EA9) != 22) func_L16_002D5CD0(m);
    if (D_0015EE84 == 18 && D_L16_0015F6A8 == 2 && (unsigned int)(D_L16_0016CD10 - 3) < 3U) func_0020D678(m);
}
extern char *func_L00_0025B478(void *, int, int);
extern int func_L00_0025B4D0(void *, void *, void *, int, int *, float *, int, int);
extern void func_L16_002D5340(void *, int, int);
extern int func_001FA898(float);
extern void func_L00_0025BBA0(void *, float *, void *, void *);
extern void func_L00_0025D5B0(float, void *, void *, int, int, int);
extern int func_0022EE28(int, int, int);
extern void func_L00_00264DB8(int, int);
extern void func_L00_002584A8(void *, int, int);
extern void func_L00_0025E4B0(void *, void *);
extern void func_L00_0025E590(void *, void *);
extern int func_001F9908(int *);
extern float func_001F9878(float);
extern int func_L00_00260FB0(float, char *, void *, int, int, void *, int);
extern int func_L00_00260D30(float, char *, void *);
extern float func_001F9D48(void *, void *);
extern float D_0015EE70 MACRO_ADDR;
extern float D_0015EE6C MACRO_ADDR;
extern int D_0015EE84 MACRO_ADDR;
extern short D_0015EF10;
extern char D_0013E633[];
extern char D_0013D50F[];
extern char *D_L16_001B0C30[];

typedef struct {
    char pad00[0x20];
    float health;
    char pad24[0x14];
    int reset_timer;
    char pad3C[0x24];
    short damage[3];
    unsigned char pad66;
    unsigned char animation;
    char pad68[8];
    float knockback[4];
    float impulse_time;
    float vertical_impulse;
    float forward_impulse;
    float lateral_impulse;
    int sound_timer;
    int active;
    float damping;
    char pad9C[0x11];
    unsigned char pending;
    char padAE[0x12];
    float blend_start;
    float blend_end;
    char padC8[8];
    float target[4];
    char padE0[0x30];
    int owner;
    int pursuit_mode;
    char pad118[0xC];
    float pursuit_range;
    char pad128[4];
    int path_index;
    char pad130[0x1B0];
    int pursuit_timer;
    char pad2E4[0x24];
    int reward_hits;
} L16DamageData;
typedef struct {
    unsigned long long vector;
    int status;
    float amount;
    float angle;
    float fatal_angle;
} L16DamageScratch;
typedef struct {
    char pad00[0x2080];
    int owner;
    char pad2084[8];
    int mode;
    char pad2090[0x14];
    unsigned char difficulty;
} L16DamageResident;
typedef struct { unsigned char pad00[0x1D]; unsigned char awarded; } L16DamageReward;
extern L16DamageResident D_L16DamageState __asm__("D_0013E633");
/* Handle damage and knockback, then update the pursuit target and timer. */
void func_L16_002D4C78(char *m) {
    L16DamageScratch scratch;
    L16DamageData *d = *(L16DamageData **)(m + 0x78);
    char *hit;
    unsigned int response;
    float range;
    float time_scale;
    *(float *)(m + 0x2C) = *(float *)(*(char **)(m + 0x24) + 0x24);
    scratch.amount = 0.0f;
    hit = func_L00_0025B478(m, 0x330000, 0);
    if (hit) {
        if (*(char **)(hit + 0x20)) {
            char *source = *(char **)(hit + 0x20);
            hit = *(short *)(source + 0xA6) != 0x31 ? hit : 0;
        }
    }
    response = func_L00_0025B4D0(m, hit, &d->health, 0, &scratch.status, &scratch.amount, 0, 4);
    if (scratch.status != 1 && ((unsigned char *)m)[0x20] != 9) {
        func_L16_002D5340(m, 0x12C, 0x168);
        if (hit && *(char **)(hit + 0x20) &&
            *(short *)(*(char **)(hit + 0x20) + 0xA6) != 0x47) {
            d->reward_hits = 0;
        }
        d->health -= scratch.amount;
        if (d->health <= 0.0f) response = 1;
        d->sound_timer = func_001FA898(512.0f);
        d->impulse_time = D_0015EE70 * 20.0f;
        d->damping = 0.5f;
        d->vertical_impulse = 0.0f;
        d->active = 1;
        d->pending = 0;
        switch (response) {
        case 9:
        case 10:
            d->animation = 0xFA;
            break;
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8: {
            float impulse = D_0015EE6C * 6.0f;
            char *source;
            d->blend_start = -1.0f;
            d->blend_end = -1.0f;
            d->forward_impulse = impulse;
            d->lateral_impulse = impulse;
            source = *(char **)(hit + 0x20);
            {
                float heading = func_L00_001FF860(*(float *)(m + 0x10) - *(float *)(source + 0x10),
                *(float *)(m + 0x14) - *(float *)(source + 0x14));
                scratch.vector = *(unsigned long long *)(hit + 0x10);
                scratch.angle = heading;
            }
            func_L00_0025BBA0(&scratch.vector, &scratch.angle, &d->forward_impulse, &d->lateral_impulse);
            func_L00_0025D5B0(scratch.angle, m, d->knockback, 6, 1, 0);
            m[0x20] = 8;
            d->animation = 0x78;
            break;
        }
        case 1:
        case 2: {
            char *source;
            if (D_0015EE84 == 18 && d->reward_hits) {
                ++*(int *)&D_0015EF10;
                if (*(int *)&D_0015EF10 >= 10) {
                    if (((L16DamageReward *)(D_0013D50F + 1))->awarded == 0) {
                        ((L16DamageReward *)(D_0013D50F + 1))->awarded = 1;
                        func_0022EE28(1, 0, 0);
                        func_L00_00264DB8(0x53DB, -1);
                    }
                }
            }
            time_scale = D_0015EE70 * 20.0f;
            *(unsigned short *)(m + 0x34) &= 0xEFFF;
            d->impulse_time = time_scale;
            if (((L16DamageResident *)((char *)&D_L16DamageState + 0xE1D))->difficulty == 2) {
                float impulse = D_0015EE6C;
                *(float *)(m + 0x58) = 0.5f;
                d->forward_impulse = impulse * 24.0f;
                d->lateral_impulse = impulse * 8.0f;
            } else {
                float impulse = D_0015EE6C * 8.0f;
                d->forward_impulse = impulse;
                d->lateral_impulse = impulse;
            }
            d->blend_start = -1.0f;
            d->blend_end = -1.0f;
            source = *(char **)(hit + 0x20);
            {
                float heading = func_L00_001FF860(*(float *)(m + 0x10) - *(float *)(source + 0x10),
                *(float *)(m + 0x14) - *(float *)(source + 0x14));
                scratch.vector = *(unsigned long long *)(hit + 0x10);
                scratch.fatal_angle = heading;
            }
            func_L00_0025BBA0(&scratch.vector, &scratch.fatal_angle, &d->forward_impulse, &d->lateral_impulse);
            func_L00_0025D5B0(scratch.fatal_angle, m, d->knockback, 7, 1, 0);
            m[0x20] = 9;
            d->animation = 0xF0;
            func_L00_002584A8(m, 0, -1);
            break;
        }
        case 0:
        case 11:
        default:
            break;
        }
        func_L00_0025E4B0(m, d->damage);
    }
    ((unsigned char *)m)[0xA4] = 0xFF;
    func_L00_0025E590(m, d->damage);
    func_001F9908(&d->pursuit_timer);
    if (d->reset_timer) {
        d->pursuit_timer = func_001FA898(func_001F9878(func_002140F8(180.0f, 240.0f)));
    }
    d->reset_timer = 0;
    range = 255.0f;
    if (d->pursuit_timer == 0) range = d->pursuit_range;
    if (((L16DamageResident *)((char *)&D_L16DamageState + 0xE1D))->mode == 22) {
        d->pursuit_mode = 2;
    } else if (d->path_index >= 0 && d->pursuit_timer == 0) {
        char *path = D_L16_001B0C30[d->path_index];
        func_L00_00260FB0(24.0f, m, d->target, 0, 0, path + 0x10, *(int *)path);
    } else {
        func_L00_00260D30(24.0f, m, d->target);
    }
    if (range < func_001F9D48(m + 0x10, d->target)) d->pursuit_mode = 2;
    if (d->owner == 0) d->owner = ((L16DamageResident *)((char *)&D_L16DamageState + 0xE1D))->owner;
}
void func_L16_002D5188(char *moby, void *owner, void *position, char *vector) {
    char *data = *(char **)(moby + 0x78);
    *(void **)(data + 0x2D0) = owner;
    qcopy(data + 0x2C0, position);
    *(float *)(data + 0x2CC) = *(float *)(vector + 8);
}
extern int func_001F9850(int);
extern void func_00213DE0(void *, int, int, int);
extern float D_0015EE6C MACRO_ADDR;

// Starts the moby's state-10 setup: sets its animation, flags, and copies position and timing into its data block.
void func_L16_002D51A8(char *moby, int arg) {
    char *d = *(char **)(moby + 0x78);
    if (((unsigned char *)moby)[0x20] == 10) {
        moby[0x20] = 1;
        if (((unsigned char *)moby)[0x53] != 1) {
            func_00213DE0(moby, 1, 0, scale_ticks(0x14));
        }
        moby[0x31] = 1;
        *(unsigned short *)(moby + 0x34) &= 0xFFFE;
        *(int *)(moby + 0x94) = *(int *)(*(char **)(moby + 0x24) + 0x10);
        *(unsigned short *)(moby + 0x34) |= 0x1000;
        *(short *)(d + 0x2DC) = arg;
        *(float *)(d + 0x2BC) = *(float *)(moby + 0x18);
        qcopy(d + 0x2C0, moby + 0x10);
        *(float *)(d + 0x2D4) = D_0015EE6C * 5.0f;
    }
}
extern float func_001F9D10(void *);
extern float func_00214D88(float *, float *, float, float, float, float);
extern void func_001F9BF0(void *, void *, void *);
extern void func_L00_001FF4B0(void *, void *, float);
extern void func_001F9BD8(void *, void *, void *);
extern float D_0015EE70 MACRO_ADDR;
extern float D_0015EE6C MACRO_ADDR;

/* steers the moby's vector toward the target and returns the distance */
float func_L16_002D5280(char *moby, float *target) {
    char *data = *(char **)(moby + 0x78);
    char *p = data + 0x2C0;
    float d = FastVecDist(p);
    float b = D_0015EE70 * 4.0f;
    int zero[1];
    float vec[4];
    zero[0] = 0;
    func_00214D88((float *)zero, (float *)(data + 0x2D4), d, b, b, D_0015EE6C * 5.0f);
    FastVecSub(vec, target, p);
    func_L00_001FF4B0(vec, vec, *(float *)(data + 0x2D4));
    FastVecAdd(p, p, vec);
    return d;
}
extern short *D_L16_001ABFC0[];
extern char *D_L16_00160098 MACRO_ADDR;
extern float func_002140F8(float,float);
extern float func_001F9878_timer(float) __asm__("func_001F9878");
extern int func_001FA898_timer(float) __asm__("func_001FA898");
typedef struct {char pad00[0x2E0];int timer;} L16GroupTimer;
typedef struct {char pad00[0x20];signed char state;unsigned char group;char pad22[0x56];L16GroupTimer *data;} L16GroupMoby;
/* Randomize the timers of active mobys in the selected linked group. */
void func_L16_002D5340(void *arg, int lower, int upper) {
    L16GroupMoby *m = arg;
    L16GroupTimer *d;
    short *p;
    if (m->group == 255) {
        d=m->data;
        d->timer=func_001FA898_timer(func_001F9878_timer(func_002140F8((float)lower,(float)upper)));
    } else {
        L16GroupMoby *other;
        p=D_L16_001ABFC0[m->group];
next:
        other=(L16GroupMoby *)(((*(unsigned short *)p&0x7FFF)<<8)+(int)D_L16_00160098);
        if (other->state>=0) {
            d=other->data;
            d->timer=func_001FA898_timer(func_001F9878_timer(func_002140F8((float)lower,(float)upper)));
        }
        if (*p++ >= 0) goto next;
    }
}
extern char *D_L16_001B0C30[];
extern float func_L00_001FF860(float, float);
extern float func_001FA790(float, float);
extern int func_001F9850(int);
extern void func_00213DE0(void *, int, int, int);
void func_L16_002D5438(char *moby) {
    char *data = *(char **)(moby + 0x78);
    char *target = D_L16_001B0C30[*(int *)(data + 0x120)] + (*(short *)(data + 0x300) << 4);
    float angle = func_L00_001FF860(*(float *)(target + 0x10) - *(float *)(moby + 0x10), *(float *)(target + 0x14) - *(float *)(moby + 0x14));
    float delta = func_001FA790(angle, *(float *)(moby + 0x48));
    if (delta < 0.78539819f && -0.78539819f < delta) {
        if ((unsigned char)moby[0x53] != 1) {
            func_00213DE0(moby, 1, 0, func_001F9850(0x14));
        }
    } else if (delta < 0.0f) {
        if (*(unsigned short *)(moby + 0x34) & 0x8000) {
            if ((unsigned char)moby[0x53] != 4) func_00213DE0(moby, 4, 0, func_001F9850(0x14));
        } else {
            if ((unsigned char)moby[0x53] != 5) func_00213DE0(moby, 5, 0, func_001F9850(0x14));
        }
    } else if (*(unsigned short *)(moby + 0x34) & 0x8000) {
        if ((unsigned char)moby[0x53] != 5) func_00213DE0(moby, 5, 0, func_001F9850(0x14));
    } else {
        if ((unsigned char)moby[0x53] != 4) func_00213DE0(moby, 4, 0, func_001F9850(0x14));
    }
}
extern void func_L00_00250800(void *,int,void *);
extern void func_001F9BC0(void *);
extern int func_002140B0(int);
extern int func_L00_00258BC8(int,int);
extern void func_L00_0026B890(void *,void *,int,int,int,int,int,int,float,float);
extern void func_L00_002ADBB0(void *,void *,void *,float,int,int,int,int,int);
extern char D_L16_00167240[];
extern short D_L16_0015F6B4;
typedef struct {int values[6];} L16ParticleChoices;
extern L16ParticleChoices D_L16_001E8600,D_L16_001E8618;
/* Spawn randomized hit particles at joint two, with extra bursts for distant hits. */
void func_L16_002D55C0(void *m) {
    float delta[4],velocity[4],position[4];
    L16ParticleChoices first,second;
    float distance,range,delay;
    int count;
    void *origin;
    float *joint=position;
    void *movement;
    func_L00_00250800(m,2,joint);
    func_001F9BF0(delta,D_L16_00167240,joint);
    func_001F9BC0(velocity);
    distance=func_001F9CB8(delta);
    if(distance<8.0f) count=func_001FA898(distance)+2;
    else count=10;
    range=0.0f;
    if(distance<7.0f) range=7.0f-distance;
    origin=position;
    movement=velocity;
    if(count>0) {
    int remaining=count;
    do {
        float sample;
        int *a,*b,duration1,duration2;
        remaining--;
        sample=func_002140F8(8.0f,10.0f);
        first=D_L16_001E8600;
        second=D_L16_001E8618;
        delay=sample*D_0015EE6C-range*D_0015EE6C;
        a=&first.values[func_002140B0(6)];
        b=&second.values[func_002140B0(6)];
        {int lo=func_001F9850(15),hi=func_001F9850(20);
        duration1=func_L00_00258BC8(lo,hi);
        }
        {int lo=func_001F9850(25),hi=func_001F9850(30);
        duration2=func_L00_00258BC8(lo,hi);
        }
        func_L00_0026B890(origin,movement,*a,*b,duration1,duration2,0,0,400000.0f,delay);
    } while(remaining!=0);
    }
    if(*(float *)&D_L16_0015F6B4<0.95f && distance>9.0f) {
        func_L00_002ADBB0(m,origin,movement,4.0f,func_001F9850(15),127,127,127,32);
        func_L00_002ADBB0(m,origin,movement,4.0f,func_001F9850(24),127,32,0,32);
    }
    func_L00_002ADBB0(m,origin,movement,4.0f,func_001F9850(20),127,64,0,48);
    func_L00_002ADBB0(m,origin,movement,3.5f,func_001F9850(27),96,16,0,64);
    func_L00_002ADBB0(m,origin,movement,3.0f,func_001F9850(29),32,0,0,32);
}
extern void func_001FA4A0(void*,void*);
extern void func_001F9BF0(void*,void*,void*);
extern void func_001F9EC0(void*,void*,void*);
extern float func_L00_001FF860(float,float);
extern float func_001F9CE8(void*);
extern void func_L00_001FF4B0(void*,void*,float);
extern void func_001F9BD8(void*,void*,void*);
extern void func_L00_00263950(char*,char*,int,float,float);
extern float D_0015EE64 MACRO_ADDR;
/* Aim paired joints toward the owner or player, then smooth their rotations. */
void func_L16_002D5958(char *m) {
    float position[4],target[4],matrix[16],delta[4],aim[4],aimDelta[4],velocity[4];
    char *d=*(char**)(m+0x78);
    if(*(int*)(d+0x114)!=2) {
        float *savedTarget,*savedMatrix;
        float yaw,pitch;
        qcopy(position,m+0x10);position[2]+=2.0f;
        if(*(short*)(*(char**)(d+0x110)+0xA6)==0) qcopy(target,D_0013E633+0xEED);
        else qcopy(target,d+0xD0);
        savedTarget=target;
        func_001FA4A0(matrix,m+0xC0);
        func_001F9BF0(delta,savedTarget,position);
        func_001F9EC0(delta,delta,matrix);
        yaw=func_L00_001FF860(delta[0],delta[1]);
        pitch=-func_L00_001FF860(func_001F9CE8(delta),delta[2]);
        if(yaw>0.7853982f) yaw=0.7853982f;
        else if(yaw<-0.7853982f) yaw=-0.7853982f;
        if(pitch>0.7853982f) pitch=0.7853982f;
        else if(pitch<-0.7853982f) pitch=-0.7853982f;
        {float halfYaw=yaw*0.5f,halfPitch=pitch*0.5f;
        *(float *)(d+0x198)=halfYaw;*(float *)(d+0x194)=halfPitch;*(float *)(d+0x218)=halfYaw;*(float *)(d+0x214)=halfPitch;}
        if((unsigned int)(*(unsigned char*)(m+0x20)-4)<2) {
            float yaw2,pitch2,bound;
            func_L00_001FF4B0(aim,m+0xC0,1.0f);
            func_L00_001FF4B0(velocity,m+0xD0,0.5f);
            func_001F9BD8(aim,aim,position);
            func_001F9BD8(aim,aim,velocity);
            func_001F9BF0(aimDelta,savedTarget,aim);
            savedMatrix=matrix;
            func_001F9EC0(aimDelta,aimDelta,savedMatrix);
            pitch2=-func_L00_001FF860(func_001F9CE8(aimDelta),aimDelta[2]);
            yaw2=-func_L00_001FF860(aimDelta[0],aimDelta[1]);
            bound=0.7853982f;
            if(pitch2>bound || pitch2<(bound=-0.7853982f)) pitch2=bound;
            if(yaw2>0.34906584f) yaw2=0.34906584f;
            else if(yaw2<-0.34906584f) yaw2=-0.34906584f;
            *(float *)(d+0x294)=pitch2;*(float *)(d+0x298)=yaw2;
        }
    }
    func_L00_00263950(m,d+0x130,1,D_0015EE64*0.03f,D_0015EE64*0.3f);
    func_L00_00263950(m,d+0x1B0,2,D_0015EE64*0.03f,D_0015EE64*0.3f);
    func_L00_00263950(m,d+0x230,3,D_0015EE64*0.03f,D_0015EE64*0.3f);
}
extern float func_002140F8(float,float);
extern void func_0020DAF8(void*,int,void*);
extern void func_001F9BC0(void*);
extern void func_L00_00258DB0(float*,float,float);
extern int func_001FA8A8(int,int,float);
extern char *func_00219780(void*,void*,void*,int,int,int,int,int,int);
/* Emit randomized joint particles while the moby is active. */
void func_L16_002D5CD0(char *m) {
    float matrix[16],velocity[4],acceleration[4],scatter[4];
    int i;
    if(*(unsigned char*)(m+0x31)==0 || *(unsigned char*)(m+0x20)==10) return;
    for(i=0;i<2;i++) {
        float speed,z;
        int color1,color2,time1,time2,time3;
        if(func_002140F8(0.0f,1.0f)>0.75f) continue;
        func_0020DAF8(m,i+4,matrix);
        speed=(func_002140F8(-0.2f,0.2f)+1.0f)*-3.0f*D_0015EE6C;
        func_L00_001FF4B0(velocity,matrix+8,speed);
        {float component=(func_002140F8(-0.2f,0.2f)+1.0f)*-2.0f;
        z=component*D_0015EE6C;}
        func_001F9BC0(acceleration);
        acceleration[2]=z;
        z=func_002140F8(-1.5f,1.5f)*D_0015EE6C;
        func_L00_00258DB0(scatter,z,z);
        func_001F9BD8(acceleration,acceleration,scatter);
        velocity[3]=func_002140F8(0.2f,0.2f);
        acceleration[3]=func_002140F8(0.4f,0.4f);
        color1=func_001FA8A8(0x801010FF,0x801080FF,func_002140F8(0.0f,1.0f));
        color2=func_001FA8A8(0x400000C0,0x4030FFFF,func_002140F8(0.0f,1.0f));
        time1=func_001FA898(func_001F9878((func_002140F8(-0.1f,0.1f)+1.0f)*5.0f));
        time2=func_001FA898(func_001F9878((func_002140F8(-0.1f,0.1f)+1.0f)*20.0f));
        time3=func_001FA898(func_001F9878((func_002140F8(-0.1f,0.1f)+1.0f)*20.0f));
        func_00219780(matrix+12,velocity,acceleration,color1,color2,time1,time2,time3,-1);
    }
}
typedef union {
    unsigned long long q;
    float f[4];
} L16TransportVector;
extern void func_L16_002E3FC8(char *);
extern void func_L16_002E4408(void *);
extern int func_L16_002E42F0(char *, char *);
extern void func_L16_002E44B8(char *);
extern int func_L00_0025A778(void *, void *, int);
extern float func_001FA850(float, float);
extern void *func_L00_00265050(char *, int, float *, void *, int, int, float, float *, float *, float *);
/* Stand-in: retail passes five arguments and no float; the file's definition (line 101) has a sixth, `float unused`. */
extern float D_0013F4D0[];
extern unsigned char D_001414F4[];
extern float D_L16_001D9950[4];
extern float D_L16_0015F660[] MACRO_ADDR;
extern short D_L16_00161E3C, D_L16_00161E40, D_L16_00161E48, D_L16_00161E4C;

/* Update the armed transport: fly in, set down its four passengers, hover, track and fire; sink and burst when destroyed. */
void func_L16_002E3740(char *m) {
    L16TransportVector vector, rotation;
    char *d = *(char **)(m + 0x78);

    func_L16_002E3FC8(m);
    switch (*(unsigned char *)(m + 0x20)) {
    case 0: {
        char *path;
        float speed;

        *(unsigned short *)(m + 0x32) = 255;
        *(unsigned char *)(m + 0x30) = 255;
        *(float *)(d + 0x20) = 12.0f;
        *(short *)(d + 0x24) = 12;
        d[0x28] = 3;
        if (*(int *)(d + 0xD8) != -1) func_L16_002E4408(D_L16_001B0C30[*(int *)(d + 0xD8)]);
        if (*(int *)(d + 0xDC) != -1) func_L16_002E4408(D_L16_001B0C30[*(int *)(d + 0xDC)]);
        speed = *(float *)&D_L16_00161E40 * D_0015EE6C;
        *(int *)(d + 0x16C) = 0;
        *(int *)(d + 0x168) = 0;
        *(float *)(d + 0x170) = speed;
        *(float *)(d + 0x194) = *(float *)(m + 0x18);
        if (*(int *)(d + 0xD8) == -1) {
            m[0x20] = 6;
            break;
        }
        path = D_L16_001B0C30[*(int *)(d + 0xD8)];
        *(float *)(d + 0x174) = func_001F9D10_update(path + 0x10, path + 0x20);
        qcopy(m + 0x10, path + 0x10);
        m[0x20] = 1;
        m[0x31] = 0;
        *(int *)(m + 0x94) = 0;
        *(unsigned short *)(m + 0x34) = (*(unsigned short *)(m + 0x34) | 1) & 0xEFFF;
        break;
    }
    case 1: {
        int i;

        if (D_L16_0015F6A8 == 0
            && (*(int *)(d + 0xD4) == -1
                || func_L00_0025A778(D_0013F4D0, D_L16_001B0C30[*(int *)(d + 0xD4)] + 0x10,
                                     *(int *)D_L16_001B0C30[*(int *)(d + 0xD4)]))) {
            m[0x20] = 2;
            *(unsigned short *)(m + 0x34) &= 0xFFFE;
            m[0x31] = 1;
            *(int *)(m + 0x94) = *(int *)(*(char **)(m + 0x24) + 0x10);
            *(unsigned short *)(m + 0x34) |= 0x1000;
            vector.q = 0;
            vector.f[2] = 3.14159f;
            for (i = 0; i < 4; i++) {
                if (((int *)(d + 0xC0))[i] >= 0) {
                    func_L16_002D5188(D_L16_00160098 + (((int *)(d + 0xC0))[i] << 8), m, D_L16_001D9950,
                                      (char *)vector.f);
                }
            }
        }
        break;
    }
    case 2: {
        int i, loaded = 0;
        char *path;

        for (i = 0; i < 4; i++) {
            if (((int *)(d + 0xC0))[i] >= 0) loaded = 1;
        }
        path = D_L16_001B0C30[*(int *)(d + 0xD8)];
        if (loaded && (float)(*(int *)path - *(int *)(d + 0x168)) * *(float *)(d + 0x174) < 16.0f) {
            func_00214D88((float *)(d + 0x17C), (float *)(d + 0x180), 1.5707964f, D_0015EE70 * 12.566371f,
                          D_0015EE70 * 12.566371f, D_0015EE6C * 6.2831855f);
        }
        if (func_L16_002E42F0(m, path)) {
            if (loaded) {
                m[0x20] = 3;
            } else if (*(int *)(d + 0xDC) == -1) {
                m[0x20] = 6;
            } else {
                m[0x20] = 4;
            }
        }
        break;
    }
    case 3: {
        int i, *slot;

        if (!func_001F9908((int *)(d + 0x184))) break;
        slot = (int *)(d + 0xC0);
        for (i = 0; i < 4; i++, slot++) {
            if (((int *)(d + 0xC0))[i] >= 0) {
                char *passenger = D_L16_00160098 + (((int *)(d + 0xC0))[i] << 8);

                func_001F9BC0(rotation.f);
                rotation.f[2] = func_001FA748(*(float *)(m + 0x48), 3.14159f);
                func_001F9EC0(vector.f, D_L16_001D9950, m + 0xC0);
                func_001F9BD8(vector.f, vector.f, m + 0x10);
                func_L16_002D51A8(passenger, func_001F9850(90));
                *slot = -1;
                *(int *)(d + 0x184) = func_001F9850(30);
                break;
            }
            if (i == 3) {
                if (*(int *)(d + 0xDC) != -1) {
                    m[0x20] = 4;
                } else {
                    m[0x20] = 6;
                }
            }
        }
        break;
    }
    case 4: {
        float heading = *(float *)(D_L16_001B0C30[*(int *)(d + 0xDC)] + 0x1C);

        func_00214D88((float *)(m + 0x48), (float *)(d + 0x178), heading, D_0015EE70 * 6.2831855f,
                      D_0015EE70 * 6.2831855f, D_0015EE6C * 6.2831855f);
        if (func_001FA850(*(float *)(m + 0x48), heading) < 0.01f) {
            m[0x20] = 5;
            *(int *)(d + 0x168) = 0;
            *(int *)(d + 0x16C) = 0;
        }
        break;
    }
    case 5:
        func_00214D88((float *)(d + 0x17C), (float *)(d + 0x180), 0.0f, D_0015EE70 * 12.566371f,
                      D_0015EE70 * 12.566371f, D_0015EE6C * 6.2831855f);
        if (func_L16_002E42F0(m, D_L16_001B0C30[*(int *)(d + 0xDC)])) {
            if (*(int *)(d + 0xD0) == -1) {
                func_0020D678(m);
                return;
            }
            m[0x20] = 6;
        }
        break;
    case 6: {
        float *yaw = (float *)(m + 0x48);
        float bearing;

        func_00214D88((float *)(d + 0x17C), (float *)(d + 0x180), 0.0f, D_0015EE70 * 12.566371f,
                      D_0015EE70 * 12.566371f, D_0015EE6C * 6.2831855f);
        bearing = func_L00_001FF860(*(float *)(d + 0x70) - *(float *)(m + 0x10),
                                    *(float *)(d + 0x74) - *(float *)(m + 0x14));
        func_00214D88(yaw, (float *)(d + 0x178), bearing, D_0015EE70 * 3.1415927f, D_0015EE70 * 3.1415927f,
                      D_0015EE6C * 6.2831855f);
        func_00214D88((float *)(m + 0x40), (float *)(d + 0x188), 0.0f, D_0015EE70 * 1.5707964f,
                      D_0015EE70 * 1.5707964f, D_0015EE6C * 6.2831855f);
        if (func_001F9908((int *)(d + 0x164)) && *(int *)(d + 0xB4) != 2) m[0x20] = 7;
        break;
    }
    case 7:
        func_L00_00250800(m, 1, vector.f);
        func_001F9BF0(rotation.f, d + 0x70, vector.f);
        func_L00_001FF4B0(rotation.f, rotation.f, *(float *)&D_L16_00161E3C * D_0015EE6C);
        func_0022ED80_update(1, 0, m);
        func_L16_002A1F78(m, (char *)rotation.f, vector.f, d + 0x70, func_001F9850(45));
        m[0x20] = 6;
        *(int *)(d + 0x164) = func_001F9850(180);
        break;
    case 8: {
        float dt = D_0015EE6C;

        *(float *)(d + 0x194) -= dt + dt;
        *(float *)(m + 0x40) += dt * 0.2617994f;
        if (func_001F9908((int *)(d + 0x160)) || D_001414F4[0] == 2) {
            func_L00_0025F4A8(m, D_L16_0015F660, m + 0x10, 0.0f, 0.0f, 20, 12, 8, 4.0f, 2.5f, 9.0f, -1, 2.0f, 0.0f,
                              0, 0, -1, 0);
            func_L00_00265050(m, 0x634, (float *)(m + 0x10), m + 0x40, 0, 0, 0.0f, D_L16_0015F660, D_L16_0015F660,
                              D_L16_0015F660);
            func_L00_00265050(m, 0x635, (float *)(m + 0x10), m + 0x40, 0, 0, 0.0f, D_L16_0015F660, D_L16_0015F660,
                              D_L16_0015F660);
            func_L00_00265050(m, 0x636, (float *)(m + 0x10), m + 0x40, 0, 0, 0.0f, D_L16_0015F660, D_L16_0015F660,
                              D_L16_0015F660);
            func_L00_002584A8(m, 0, -1);
            func_0020D678(m);
            return;
        }
        break;
    }
    }
    *(float *)(d + 0x18C) = func_001FA748(*(float *)(d + 0x18C),
                                          *(float *)&D_L16_00161E48 * 0.017453292f * D_0015EE6C);
    *(float *)(m + 0x18) = *(float *)(d + 0x194) + *(float *)&D_L16_00161E4C * func_001F9FA8(*(float *)(d + 0x18C));
    func_L16_002E44B8(m);
}
extern int func_L00_0028EB98(void*,int);
extern int func_0022ED80_6B70(int,int,void*) __asm__("func_0022ED80");
extern void func_L00_0028EBF0(int);
extern char *func_L00_0025B478(void*,int,int);
extern int func_L00_0025B4D0(void*,void*,void*,int,int*,float*,int,int);
extern float func_L00_00258C80(float,float);
extern void func_L00_0025E4B0(void*,void*);
extern void func_L00_0025E590(void*,void*);
extern int func_L00_00260FB0(float,char*,void*,int,int,void*,int);
extern short D_L16_00161E38;
extern char *D_L16_00160098 MACRO_ADDR;
typedef struct {char pad[0x74];unsigned char active;char pad75[0x13];char *owner;} L16InteractionSlot;
typedef struct {char pad[0x80];float position[4];char pad90[0x1FF0];int owner;} L16PursuitPlayer;
typedef struct {int status;float amount;} L16HitResult;
/* Update interaction ownership, damage responses and pursuit tracking. */
void func_L16_002E3FC8(char *m) {
    L16HitResult hit;
    char *d=*(char**)(m+0x78);
    float zero;
    char *record;
    int response;
    (*(float*)((char*)(m)+(0x2C)))=(*(float*)((char*)(*(char**)(m+0x24))+(0x24)))*(*(float*)&D_L16_00161E38);
    if((unsigned int)((*(unsigned char*)((char*)(m)+(0x20)))-2)<4) {
        if(!func_L00_0028EB98(m,(*(int*)((char*)(d)+(0x190))))) (*(int*)((char*)(d)+(0x190)))=func_0022ED80_6B70(0,4,m);
    } else if(func_L00_0028EB98(m,(*(int*)((char*)(d)+(0x190))))) {
        int slot=(*(int*)((char*)(d)+(0x190)));
        if(slot!=-1) {
            L16InteractionSlot *s=(L16InteractionSlot*)(D_0013E633+0x1D+slot*0x70);
            if(s->owner==m && s->active!=0) func_L00_0028EBF0(slot);
        }
        (*(int*)((char*)(d)+(0x190)))=-1;
    }
    hit.amount=zero=0.0f;
    record=func_L00_0025B478(m,0x330000,0);
    response=func_L00_0025B4D0(m,record,d+0x20,0,&hit.status,&hit.amount,0,4);
    if(hit.status!=1 && (*(unsigned char*)((char*)(m)+(0x20)))!=8) {
        (*(float*)((char*)(d)+(0x20)))-=hit.amount;
        if((*(float*)((char*)(d)+(0x20)))<=zero || ((*(unsigned char*)((char*)(D_0013E633)+(0x2EC1)))==2 && hit.amount>=2.0f)) response=1;
            if(response>0) {
            if(response>=3) {
                if(response<9) {
                func_0022ED80_6B70(3,0,m);
                (*(unsigned char*)((char*)(d)+(0x67)))=120;
                (*(float*)((char*)(d)+(0x188)))=func_L00_00258C80(30.0f,50.0f)*0.017453292f*D_0015EE6C;
                }
            } else {
                func_0022ED80_6B70(3,0,m);
                if((*(unsigned char*)((char*)(D_0013E633)+(0x2EC1)))!=2) func_0022ED80_6B70(2,0,m);
                {int *child=(int*)(d+0xC0),count=3;
                do {
                    char *pool=D_L16_00160098;
                    if(*child>=0) func_0020D678(pool+(*child<<8));
                    child++;
                } while(--count>=0);
                }
                (*(unsigned char*)((char*)(m)+(0x20)))=8;(*(int*)((char*)(d)+(0x160)))=func_001F9850(90);(*(unsigned char*)((char*)(d)+(0x67)))=120;

            }
        }
        func_L00_0025E4B0(m,d+0x60);
    }
    (*(unsigned char*)((char*)(m)+(0xA4)))=255;
    func_L00_0025E590(m,d+0x60);
    if((*(int*)((char*)(d)+(0xD0)))!=-1 && (*(int*)((char*)(D_0013E633)+(0x2EA9)))!=22) {
        char *path=D_L16_001B0C30[(*(int*)((char*)(d)+(0xD0)))];
        func_L00_00260FB0(128.0f,m,d+0x70,0,0,path+0x10,*(int*)path);
    } else (*(int*)((char*)(d)+(0xB4)))=2;
    if((*(int*)((char*)(d)+(0xB0)))==0) {
        L16PursuitPlayer *player=(L16PursuitPlayer*)(D_0013E633+0xE1D);
        (*(int*)((char*)(d)+(0xB0)))=player->owner;
        qcopy(d+0x70,player->position);
    }
}
extern void func_00215CA8_path42(float,void*,int,void*,void*,int) __asm__("func_00215CA8");
extern float func_001F9D10_path42(void*,void*) __asm__("func_001F9D10");
extern float func_00214D88_path42(float,float,float,float,float*,float*) __asm__("func_00214D88");
extern short D_L16_00161E44, D_L16_00161E40;
/* Advance a path segment and ease the remaining travel distance. */
int func_L16_002E42F0(char *m, char *path) {
    char *d = *(char **)(m+0x78);
    float progress = (float)*(int *)(d+0x168) + *(float *)(d+0x16C) + *(float *)(d+0x170) / *(float *)(d+0x174);
    int index = func_001FA898(progress);
    float speed;
    float distance, rate;
    char *position;
    *(int *)(d+0x168)=index;
    *(float *)(d+0x16C)=progress-(float)index;
    if(index<*(int *)path-1) {
    position=m+0x10;
    func_00215CA8_path42(progress,path,0,position,m+0x40,0);
    *(float *)(d+0x194)=*(float *)(m+0x18);
    speed=0.0f;
    distance=func_001F9D10_path42(position,path+(*(int *)path<<4));
    rate=*(float *)&D_L16_00161E44*D_0015EE70;
    func_00214D88_path42(distance,rate,rate,*(float *)&D_L16_00161E40*D_0015EE6C,&speed,(float *)(d+0x170));
    return 0;
    }
    return 1;
}
INCLUDE_ASM("asm/overlays", func_L16_002E4408);
extern float D_0015EE64 MACRO_ADDR;
extern void func_L00_00263950(char *, char *, int, float, float);

void func_L16_002E44B8(char *moby)
{
    float ticks = D_0015EE64;
    float a = ticks * 0.03f;
    float b = ticks * 0.3f;
    char *data = *(char **)(moby + 0x78);
    *(float *)(data + 0x144) = *(float *)(data + 0x17C);
    func_L00_00263950(moby, data + 0xE0, 2, a, b);
}
extern short D_L16_00161EC0;
extern short D_L16_00161EC4;
extern short D_L16_00161EC8;
extern float func_001FA748(float, float);
extern int func_L00_0028EB98(void *, int);
extern int func_0022ED80_6B70(int, int, void *) __asm__("func_0022ED80");
extern void func_001F49B0(void (*)(void), void *);
extern void func_L16_002E6D40();
extern int func_L16_002E7138(int);
extern void func_L16_002E7198(int);

/* Updates a moby effect and advances it when its linked object is ready. */
void func_L16_002E6B70(unsigned char *m) {
    char *d = *(char **)(m + 0x78);
    float cycle;
    int i;
    float *p;
    switch (m[0x20]) {
    case 0:
        m[0x20] = 1;
        m[0x30] = 0xFF;
        break;
    case 1:
        cycle = *(float *)(d + 0xC) + *(float *)&D_L16_00161EC4 * D_0015EE6C;
        *(float *)(d + 0xC) = cycle;
        if (cycle > 1.0f) *(float *)(d + 0xC) = cycle - 1.0f;
        if (func_L00_0028EB98(m, *(int *)(d + 0x24)) == 0) {
            *(int *)(d + 0x24) = func_0022ED80_6B70(0, 4, m);
        }
        *(float *)(d + 8) = func_001FA748(*(float *)(d + 8),
                            *(float *)&D_L16_00161EC0 * 0.017453292f * D_0015EE6C);
        p = (float *)(d + 0x10);
        for (i = 0; i < 4; i++) {
            p[i] = func_001FA748(p[i],
                   ((float *)&D_L16_00161EC8)[i] * 0.017453292f * D_0015EE6C);
        }
        if (m[0x31]) func_001F49B0(func_L16_002E6D40, m);
        if (*(int *)(d + 0x20) != -1 && func_L16_002E7138(*(int *)(d + 0x20))) {
            *(int *)(m + 0x94) = 0;
            m[0x20] = 2;
            func_L16_002E7198(*(int *)(d + 0x20));
        }
        break;
    case 2:
        if (!func_L16_002E7138(*(int *)(d + 0x20))) {
            m[0x20] = 1;
            *(int *)(m + 0x94) = *(int *)(*(char **)(m + 0x24) + 0x10);
        }
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L16_002E6D40);
/* 1 when every moby in list IDX has its byte at 0xBC set; the list ends at the entry with the top
 * bit set. The catalogue cuts this function in three (config/overlays/joined.tsv). */
int func_L16_002E7138(int idx) {
    short *p = D_L16_001ABFC0[idx];
    if (p == 0) return 0;
    do {
        if (*(unsigned char *)(((*(unsigned short *)p & 0x7FFF) << 8) + (int)D_L16_00160098 + 0xBC) == 0) return 0;
    } while (*p++ >= 0);
    return 1;
}
INCLUDE_ASM("asm/overlays", func_L16_002E7160);
extern char D_0013E633[];
extern short *D_L16_001ABFC0[];
extern char *D_L16_00160098 MACRO_ADDR;
extern float func_001F9D10_2E7198(void *, void *) __asm__("func_001F9D10");
extern void func_0022ED80(int, int, int);

/* picks the nearest moby in a list (skipping class 0x5A3) and acts on it */
void func_L16_002E7198(int idx) {
    short *p = D_L16_001ABFC0[idx];
    char *best = 0;
    float bestd = 50000.0f;
    if (p != 0) {
        do {
            char *m = D_L16_00160098 + ((*(unsigned short *)p & 0x7FFF) << 8);
            if (*(short *)(m + 0xA6) != 0x5A3) {
                float d = func_001F9D10_2E7198(D_0013E633 + 0xE9D, m + 0x10);
                if (d < bestd) {
                    bestd = d;
                    best = m;
                }
            }
        } while (*p++ >= 0);
        if (best != 0) {
            func_0022ED80(0, 0, (int)best);
        }
    }
}
extern void func_001F49B0(void (*)(void), void *);
extern void func_L16_002EB158(void);
void func_L16_002EB268(unsigned char *moby) {
    switch (moby[0x20]) {
    case 0:
        moby[0x20] = 1;
        break;
    case 1:
        func_001F49B0(func_L16_002EB158, moby);
        break;
    }
}
